### ISSUE TITLE
Future Features

### ISSUE THREAD

**Issue by BillyBlaze** [BillyBlaze/OctoPrint-TouchUI#1]
- [x] ~~Add some way to change colors~~
- [x] ~~Include Fan icon in font package~~
- [x] ~~Refactor cookie script into localStorage (+ migration script)~~
- [ ] Terminal Highlighter

**Navigation bar**
- [ ] Make the navigation bar appear when scrolling up
- [ ] Add a option to always show the navigation bar

**GCode viewer**
- [ ] Add touch and non-touch zooming
- [ ] Add touch and non-touch layer change

**Webcam**
- [ ] Bind touch and non-touch to current keyboard navigation

**Plugins**
- [ ] Gather most common and most broken

**Comment by derSkimmy** [comment]
Colors would be great :+1:

**Comment by BillyBlaze** [comment]
Colors are add'd in v0.3.0 :smile:

**Comment by derSkimmy** [comment]
Very nice, thank you! I will try it after the holidays :+1:
