### ISSUE TITLE
Misplaced texts on Raspbberry Pi HDMI screen

### ISSUE THREAD

**Issue by trgtylcnky** [BillyBlaze/OctoPrint-TouchUI#103]
Hi,
I am using touch screen on Raspberry Pi. While using TouchUI, some texts are placed in ridiculous positions.
For example, when I am in camera tab:
![p_20170220_095509](https://cloud.githubusercontent.com/assets/23400050/23114917/73c09f0c-f74a-11e6-8933-3642f653e86d.jpg)

Or I am in  main menu, this is not permanent, disappears when I use slider.
![p_20170220_094626](https://cloud.githubusercontent.com/assets/23400050/23114946/9ec65502-f74a-11e6-932f-386493b366fa.jpg)

Do you suggest anything for me to investigate this issue?

**Comment by BillyBlaze** [comment]
Thanks for reporting. 

It seems like TouchUI is having a javascript error and is therefor failing to start-up.
Have you installed additional plugins?

**Comment by trgtylcnky** [comment]
Thanks for replying.
No additional plugin is installed. I realized that in one of my previous installation it was working, I was updated the whole raspbian. Are there any specific package I should upgrade do you think? I thought about epiphany-browser but it is already on the newest version. 
I prefer not to update whole system this time because it takes so long and I am really sorry for saying this.

**Comment by BillyBlaze** [comment]
Could you share your `~/.octoprint/logs/octoprint.log`?

If there is no information then I need to know how you're starting epiphany so you can get the javascript console messages 👍

**Comment by trgtylcnky** [comment]
Sorry for late reply, but I couldn't managed to observe the same bugs. The reason is that other problems are occurred on my system and I had to reinstall everything. I am now running OctoPi image with latest versions and problem seems solved. 
Though I am still observing random problems such as kernel panic or being unable to slide TouchUI panel (random times, after one print is done etc. ), I think this issue can be closed.

**Comment by BillyBlaze** [comment]
Alright, glad you where able to fix this issue!
