### ISSUE TITLE
Login not remembering

### ISSUE THREAD

**Issue by SYC-O** [BillyBlaze/OctoPrint-TouchUI#106]
I have found that no matter what I do every time I login to octoprint on my phone or tablet via the touch ui I have to enter my login details. I've checked the remember details checkbox and yet it still forgets it. Also tried switching to normal view and logging in and then back to the touchui but still forgets my details.

**Comment by bzeeman** [comment]
Same problem here.

**Comment by BillyBlaze** [comment]
Hello,

Thanks for reporting. If you do not provide any information about the devices, browser or any other information, then I can not look into this bug.

I am going to assume you both are on an iOs devices and this bug is already reported in the main repository foosel/OctoPrint/issues/1792

**Comment by BillyBlaze** [comment]
Closed due to inactivity. Please feel free to open a ticket if you can provide me some more details.
