### ISSUE TITLE
Cannot view the Cancel Modal Confirmation Window on 3.5" TFT

### ISSUE THREAD

**Issue by mschraeder** [BillyBlaze/OctoPrint-TouchUI#110]
When I try to cancel a print from a 3.5" Touch screen I cannot see the modal confirmation window so I can't actually cancel a print. 

I'm running the latest version.

**Comment by BillyBlaze** [comment]
Hello,

Thanks for reporting, I am able to get the Confirmation modal on both my 3.5" and 7" touchscreen. Do you perhaps have any additional plugins installed??

**Comment by BillyBlaze** [comment]
closed due to inactivity.
