### ISSUE TITLE
Feature Request: Add a Refresh button to the menu

### ISSUE THREAD

**Issue by mschraeder** [BillyBlaze/OctoPrint-TouchUI#111]
I use Octoprint on a 3.5" TFT with no keyboard / mouse. 

Every once in a while I need to refresh the page because it has a communication error or something else. I can't actually refresh the screen because I dont have a keyboard attached (which is the reason I use TouchUI to being with). 

Please add a "Refresh" button to the menu. Without it I have to shut down and power on the whole unit just to do it.

**Comment by BillyBlaze** [comment]
Hi,

Thanks for submitting the feature request. I will add a refresh button to the TouchUI Settings.

**Comment by BillyBlaze** [comment]
This has been fixed in the latest 0.3.7 release.
