### ISSUE TITLE
"Incompatibility" with the new TEMPSGraph plugin 

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#118]
aka loosing responsiveness when running TouchUI with the plugin enabled.

aka can't scroll the temp window, etc.

Perhaps just an "If touchui=enabled then load.default.tempwindow else load tempsgraph.window"?

**Comment by BillyBlaze** [comment]
Thanks for reporting, I will disable this plugin when TouchUI is active.

**Comment by BillyBlaze** [comment]
This has been fixed in the latest 0.3.7 release.
