### ISSUE TITLE
[ Error writing /etc/X11/xorg.conf.d/99-fbdev.conf: No such file or directory ]

### ISSUE THREAD

**Issue by Shahriar57** [BillyBlaze/OctoPrint-TouchUI#120]
Hello
I tried many time this setup step by step 
https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(OctoPi-or-Jessie-Light)

when i run Run sudo nano /etc/X11/xorg.conf.d/99-fbdev.conf
and add 
Section "Device"  
  Identifier "touchscreen"
  Driver "fbdev"
  Option "fbdev" "/dev/fb1"
EndSection
then CRTL+O , Enter 
get 
 [ Error writing /etc/X11/xorg.conf.d/99-fbdev.conf: No such file or directory 

 i search in Issue and find this issue 
https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/44
then Run sudo apt-get install lxde-core
and after finish reboot 
but again i got same error 
what shall i do ?

**Comment by BillyBlaze** [comment]
Hello, The instructions talk about ```sudo nano /usr/share/X11/xorg.conf.d/99-fbdev.conf``` and not ```/etc/X11/xorg.conf.d/99-fbdev.conf```

**Comment by BillyBlaze** [comment]
Have you had any luck yet?

**Comment by BillyBlaze** [comment]
Closed due to inactivity. Please feel free to resume conversation if needed.
