### ISSUE TITLE
no webcam in the webbrowser

### ISSUE THREAD

**Issue by Lepterois** [BillyBlaze/OctoPrint-TouchUI#128]
Hi!
Sorry I'm new user of octoprint and touch ui.
Since I've added touch ui, I've the webcam stream on the tft screen but not anymore on the webbrowser on the pc.
an idea about what I'm doing wrong?
Thanks

**Comment by Lepterois** [comment]
I've found the solution!
the correct adress is: http://IP_adress/webcam/?action=stream

now I've the stream both on the touch panel and the pc's.

You can close the issue. 

Sorry

**Comment by BillyBlaze** [comment]
No problem, I'm glad you figured out this problem!

Enjoy!
