### ISSUE TITLE
Change the Font-size

### ISSUE THREAD

**Issue by Mte90** [BillyBlaze/OctoPrint-TouchUI#129]
We are using TouchUi with a panel 1024x600 so the actual font-size is very small so I am asking if is possible to add a settings like for the color for change the font size.

**Comment by BillyBlaze** [comment]
Thanks for reporting.

Currently the font-size is inherited from OctoPrint. I will add - as soon as I have some time on my hands - a LESS variable where you can change the font size. Maybe I'll will add font-size in rem values so that you only can change the font-size on the root element.

**Comment by BillyBlaze** [comment]
This has been fixed in the current release 0.3.9

Thanks for reporting!
