### ISSUE TITLE
Missing WebCam on chromium installed by wiki

### ISSUE THREAD

**Issue by Mte90** [BillyBlaze/OctoPrint-TouchUI#131]
I followed your wiki tutorial to install it on the octopi distro and on the chromium running with touch ui connected to raspberry the image result on loading but on a different browser in another computer it is working without problem.
So I think that is missing a package that add the codec but I have no idea what is.

**Comment by BillyBlaze** [comment]
Hi @Mte90 ,

Please take a look at the solution from #128
