### ISSUE TITLE
Feature request : derive TouchUI 'main color' setting from OctoPrint 'Appearance' color, 

### ISSUE THREAD

**Issue by joris57** [BillyBlaze/OctoPrint-TouchUI#133]
I am running multiple instances of OctoPrint on different ports of the same (Ubuntu) server. To differentiate between them, I set a different 'appearance' color in OctoPrint.

For consistency, I would be nice if in TouchUI, the 'main color' setting, could be derived from the OctoPrint 'appearance' color, without having to 'color match' and enter it manually .

**Comment by BillyBlaze** [comment]
Thanks for reporting, as said in #132 I don't have time on my hands for implementing this feature, as it would be an addition to feature request in #132 

Once TouchUI supports multiple instances we could then add this feature request on top of that.
