### ISSUE TITLE
No modal action button

### ISSUE THREAD

**Issue by daorithos** [BillyBlaze/OctoPrint-TouchUI#136]
Platform:
OS: Win10
HW: Tablet 9" 
Layout: portrait and landscape

The action button in the modal are not displayed, go under.
In the inspector i set 90% ehight of modal and everything is ok

**Comment by BillyBlaze** [comment]
Hello,

Thanks for reporting. What browser did you use?

**Comment by BillyBlaze** [comment]
Closed due to inactivity.
