### ISSUE TITLE
New guide needed for HDMI USB touch screens

### ISSUE THREAD

**Issue by bakerboy908** [BillyBlaze/OctoPrint-TouchUI#140]
When following the boot to browser for octopi wiki there are a few changes that need to be made when using a USB HDMI LCD like the one linked below.

First the install-desktop script needs to be run for the touch drivers to be installed

Second step 5. "Register your touchscreen to X11 by creating a new config:" needs to be completely ignored otherwise the pi will boot to command line.

after that everything else should work.

Hopefully this info can help someone out.

https://www.banggood.com/7-Inch-1024-x-600-HDMI-Capacitive-IPS-LCD-Display-For-Raspberry-Pi-Banana-Pi-p-1059318.html

**Comment by lolorc** [comment]
what install-desktop script are you referring to ?
Would you mind giving a bit more information please ?

**Comment by bakerboy908** [comment]
Its a script within octopi to install the raspbian desktop environment 

detailed here
http://octoprint.org/blog/2016/05/02/new-octopi-release-0-13-0/

**Comment by bakerboy908** [comment]
Interestingly ive just run another install from scratch and the touch screen is working without installing the desktop
Please feel free to close this

**Comment by BillyBlaze** [comment]
Hello,

Glad the guide is still working for you. The reason why I dont use the install-desktop script is because it will install alot of libraries that you will never use with TouchUI.

Closing this now.
