### ISSUE TITLE
Menu items not correctly populated

### ISSUE THREAD

**Issue by keybkeybkeyb** [BillyBlaze/OctoPrint-TouchUI#145]
Hi, My installation of TouchUI shows some visual issues,
- The settings menu that is not populated and few items on the right totally misaligned.
- Items on the other pages are misaligned as well (see attached pics)

I'm using a Raspberry PI2 with a 7" touch screen
Octoprint Version 1.3.4 (master branch)
TouchUI (0.3.8) 
Latest Chromium

The same issue is present with my android device

Hope you can help me.

Thank you,
Alessandro
![tui1](https://user-images.githubusercontent.com/31383729/29748939-aa9afea8-8b21-11e7-8860-228db2a40024.PNG)
![tui2](https://user-images.githubusercontent.com/31383729/29748940-aa9bcd6a-8b21-11e7-9ea1-a7bf7bc4b6ca.PNG)
![tui3](https://user-images.githubusercontent.com/31383729/29748941-aa9c2fb2-8b21-11e7-9042-531e3504acaf.PNG)

**Comment by Ipoc78** [comment]
I too am having this issue. not only on my tab, cell, but also on web browser. I had to clean my cookies in order to get it back to desktop version on my laptop.

 I'm running  latest version of octpi 0.14 on a raspberry pi3 and using the official pi 7" touch screen (unable to use touch screen due to touchui  being hung up on boot up, octprint still works fine)

**Comment by 2tri4fun** [comment]
I am having similar issues.  Followed your wiki and was able to get touchui up on 7" Pi Touchscreen but control tab is blank.

**Comment by BillyBlaze** [comment]
Hello, thanks for reporting and sorry for the long delay.

I think you're having the same issues as #144 and this is currently fixed on the maintenaince branch. However I intend to release 0.3.9 in the next hours where this is fixed.

**Comment by keybkeybkeyb** [comment]
Thank you for taking the time for looking into it!

**Comment by BillyBlaze** [comment]
0.3.9 has been released, please let me know if this fixed the issue!

**Comment by Ipoc78** [comment]
Fantastic thank you for your time and dealing with this issue, 
I'm going to fire up my printer here shortly and report back

**Comment by Ipoc78** [comment]
I confirm on my end that it's working correctly

**Comment by BillyBlaze** [comment]
Awesome! Glad this was the issue that is now resolved 👍 

Thanks again for reporting! Closing this, please open a new one if needed!
