### ISSUE TITLE
TouchUI without the need to scroll

### ISSUE THREAD

**Issue by ingmaniac** [BillyBlaze/OctoPrint-TouchUI#148]
Hello!
First of all, thanks for this great plugin.
Is there a chance to get TouchUI running without the need to scroll the lcd?
Especially on the 3,5" tft its a real pain to scroll.
Thanks in advance!

**Comment by BillyBlaze** [comment]
Hello,

Your welcome 👍 and thanks for asking.

Currently this is not possible at all in 0.3.x
Version 1.0.0 has some better optimizations for less scrolling, but I fear that will not be released soon since I don't have much free time on my hands atm.
