### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by ohu07** [BillyBlaze/OctoPrint-TouchUI#149]
After the rpi-update my screen just went white. The pi still boots and I am still able to ssh in, but even with a fresh installation of Jessie Lite the screen still stays white. It shouldn't be hardware issue because it worked before and I haven't change anything on the hardware end. Thanks.

**Comment by ohu07** [comment]
FIXED. Jessie image was corrupted.

**Comment by BillyBlaze** [comment]
Awesome, glad you figured this out 👍
