### ISSUE TITLE
PSUControl Indicator Changes

### ISSUE THREAD

**Issue by kantlivelong** [BillyBlaze/OctoPrint-TouchUI#151]
Referencing #97 

I've made some changes to how the indicator is displayed in 0.1.5 which subsequently broke the compatibility with this plugin.

**Comment by BillyBlaze** [comment]
Thanks for the heads-up! I can take fix this in the upcoming release.

**Comment by BillyBlaze** [comment]
Closing due to misunderstanding 👍
