### ISSUE TITLE
Connecting LCD to octoprint

### ISSUE THREAD

**Issue by nerys71** [BillyBlaze/OctoPrint-TouchUI#153]
Trying to get this working. the lcd works it boots up etc.. and sits at a text prompt saying login

works from the web ui. I installed the touch ui plugin but that is as far as I could get. step 1 stymied me

sudo apt-get update

where do I PUT that? I found a terminal tab on the octoprint ui but I can't alter or enter anything into it.

how do I enter this command? (REAL newb here) do I need to connect a keyboard to the octopi or something?

**Comment by BillyBlaze** [comment]
Hi @nerys71 

You need to login with SSH on your RaspberryPi and run this steps all there in the command interface. I assume you installed OctoPi. In the case of OctoPi, read the "[Getting Started with OctoPi](http://octoprint.org/download/)" and if you're still confused, go watch the video on the same page by Thomas Sanladerer. He explains everything you need to know.

I am closing this issue, please keep responding to this issue if you need something more.
