### ISSUE TITLE
Webcam link not available

### ISSUE THREAD

**Issue by S0rcerer7** [BillyBlaze/OctoPrint-TouchUI#159]
Updated Touch UI last night, & now I don't get an icon to view my webcam anymore.
Now it shows the Files,  Temp,  control, and now where camera was, it has a link for gcode view

How do I get the webcam view back?

I know it's still working, because when I disable Touch UI, it's there in octoprint, still working.

Thanks

**Comment by BillyBlaze** [comment]
Thanks for reporting.

I can confirm I totally overlooked this :(

I have stopped the release (for those who didn't receive it yet) and will add a new release in a few hours.

**Comment by BillyBlaze** [comment]
Thanks again for reporting!

I have released 0.3.10 where this issue is fixed
