### ISSUE TITLE
No camera in V0.3.0

### ISSUE THREAD

**Issue by pcfriend** [BillyBlaze/OctoPrint-TouchUI#16]
Hi there,
I like your plugin very much and I used it on my Raspberry Pi B. But then I wanted to have more power for the grafical UI and I bought a Raspberry Pi 2B. After the installation of your plugin I couldn't see the image of the webcam on the Touch UI. It is still there on the normal Octoprint interface. What's wrong here. Do you have an idea?

Thank you! It's an amazing project! =D

Raphael

**Comment by BillyBlaze** [comment]
Hi Raphael,

Thanks for the compliment and for reporting the bug, could you enlighten me a bit with the OctoPrint version you're running? And can you see any error's in the console of the developer toolbar?

Paul

**Comment by pcfriend** [comment]
Hi Paul
I've running Octoprint 1.2.8. How do I enable the developer toolbar to watch the errors?

Happy new Year! ;D
Raphael

**Comment by BillyBlaze** [comment]
Happy new year :smile: 

Checkout this link on how to open your developer toolbar. https://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

Then open the console and check if you can see any errors after opening your webcam tab.

**Comment by pcfriend** [comment]
I can't see any errors. Maybe the warning is important, but I really don't know a lot about web applications.
![screenshot](https://cloud.githubusercontent.com/assets/16500475/12070347/050a855a-b06f-11e5-8d58-155a96e9277e.PNG)

**Comment by BillyBlaze** [comment]
Awesome, that was exactly what I needed, sadly it doesn't give that much info about your problem, but it does give my information that all scripts are running perfectly fine.

I'll dive some more into this problem and try to fix it in 0.3.1

**Comment by BillyBlaze** [comment]
Ok, it looks like I identified the problem. Apparently there was a refactor of code in OctoPrint 1.2.8 that I missed, I will make a fix for this in 0.3.1 and plan to release it soon.

**Comment by pcfriend** [comment]
Thank you!

**Comment by BillyBlaze** [comment]
I just launched v0.3.1, feel free to open any new tickets if you have any issue's.

**Comment by pcfriend** [comment]
Thank you Paul. It work's!
