### ISSUE TITLE
If screen is rotated from landscape to portrait the menu icons gets stacked on top of each other.

### ISSUE THREAD

**Issue by Linusoderlind** [BillyBlaze/OctoPrint-TouchUI#161]
In the latest release (0.3.10) the icons show if they fit in the menu. But they are not removed if I rotate my phone from landscape to portrait.

I use a Nexus 5x with Android 8.0.0 and the latest Chrome 61.0.3163.98
The images are from reloading the screen in portrait, rotating to landscape and back to portrait.
![screenshot_20171020-141512](https://user-images.githubusercontent.com/32685861/31820758-0179a1ec-b5a3-11e7-9800-2e489b2e2a31.png)
![screenshot_20171020-141520](https://user-images.githubusercontent.com/32685861/31820761-0453c3f2-b5a3-11e7-9a9b-f4887724ebfb.png)
![screenshot_20171020-141533](https://user-images.githubusercontent.com/32685861/31820764-0684f182-b5a3-11e7-8559-aaa3fb0ae2a2.png)

I can reproduce the behavior on my Windows 10 PC with Chrome 62.0.3202.62 if I resize the window small enough so some icons are moved to the drop down. I then maximize the window and then un maximize it again. If I now resize the window by dragging the GUI behaves again.

**Comment by BillyBlaze** [comment]
Hi @Linusoderlind 

Thanks for reporting and for providing the detailed information/screenshots.
I understand where this goes wrong and will fix this in the upcoming release!

**Comment by Linusoderlind** [comment]
Working as a software tester has it's perks. :)
