### ISSUE TITLE
webstream

### ISSUE THREAD

**Issue by stickfisch** [BillyBlaze/OctoPrint-TouchUI#169]
hello have the following problem. have touch ui with octoprint installed on a raspberry pi 3. a Logitech c270 on the touch screen, the webstream is not displayed to me but with an icon that is broken. what should I change that is? thank you for quick help pascal

**Comment by BillyBlaze** [comment]
Hi @stickfisch 

Please setup your webcam as followed: https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#webcam-image-not-working
