### ISSUE TITLE
Accidently turned off touchui on my touch display now it wont start

### ISSUE THREAD

**Issue by supernielsen** [BillyBlaze/OctoPrint-TouchUI#170]
I tried to be as accurate as i could in the title.

I have a 5 inch touch screen on my pi everything have been working perfect, however i accidently turned off touch ui on the display, i didnt care that day and closed everything as normal. 

Then when i started the printer today it says.

                    TOUCHUI
   Octoprint loaded without TouchUI 
                  Tap to retry

No matter how many times i retry it wont work. what to do?

**Comment by BillyBlaze** [comment]
Hi @supernielsen,

Hmm, I guess I have created a soft-block there 🤣 

The easy way to fix this is to reset Chrome:

1. Stop TouchUI:
````
sudo service touchui stop
````

2. Remove default user in Chrome
````
rm -rf ~/.config/chromium/Default
rm -rf ~/.cache/chromium
````

3. Start TouchUI
````
sudo service touchui start
````

**Comment by BillyBlaze** [comment]
Any updates? if not I'm closing this issue.

**Comment by supernielsen** [comment]
so sorry..!!!

Yes it worked a charm thank you so much ! :)

**Comment by BillyBlaze** [comment]
No problem and awesome it works again 👍

**Comment by BillyBlaze** [comment]
Btw. I just released a new version of TouchUI, and in this version I will always enable TouchUI if it's getting loaded with the bootloader. This should prevent issues like this occurring.

**Comment by supernielsen** [comment]
I actually just got that update yesterday so thats just perfect.. :D
