### ISSUE TITLE
move left right buttons and home button in between doesn't work on the Touch Screen

### ISSUE THREAD

**Issue by henrikkoch** [BillyBlaze/OctoPrint-TouchUI#171]
All the buttons except left/right and home in between work when using TouchUI on my Prusa i3MK2s/MM. The home button to the right in between the up and down button works fine.
 
It works fine form the web browser (not touch panel) But only left/right buttons on the Touch screen doen't work.

Any ideas why?  How can this be changed?

I'm using OctoPrint Version 1.3.5 (rc/maintenance branch)

TouchUI (0.3.10)

**Comment by BillyBlaze** [comment]
Hi @henrikkoch,

TouchUI doesn't manipulate the underlying functions of this functionality. So OctoPrint should handle this.

If you press the left/right can you see any activity in your terminal output?

**Comment by henrikkoch** [comment]
Hi BillyBlaze.  When trying up/down I get Z commands like:  Send: G1 Z10 F200

When trying back and forth i get Y commands like:  Send: G1 Y10 F6000

Nothing happens when pressing X the left/right buttons?

This of coarse happens when using the buttons in the browser window (not the one on the touch UI)

**Comment by BillyBlaze** [comment]
Do you see the left/right/home button changing colors when clicking them? Perhaps you have a 3rd party plugin that overlaps these controls?

Also I see you're on an older version of 1.3.5, you should be able now to install the stable version of 1.3.5 now. (e.g. master branch)

**Comment by henrikkoch** [comment]
No - They doesn't seem to change colors when you pushed these buttons. But the others yes

**Comment by henrikkoch** [comment]
Did update to OctoPrint: 1.3.6rc1   Still same problem. No color change on mentioned buttons and no printer functionality

**Comment by henrikkoch** [comment]
BillyBlaze any other ideas how to get my setup to work? :-)

**Comment by BillyBlaze** [comment]
Hmm, for me it works on any test device, do you have any 3rd party plugins installed?

**Comment by BillyBlaze** [comment]
Closing this issue due to lack of information.
