### ISSUE TITLE
[Feature Request] disable camera tab

### ISSUE THREAD

**Issue by ManuelW77** [BillyBlaze/OctoPrint-TouchUI#174]
Hey there,
i have a wish for touch ui. I want to disable the camera tab, and loadings, because it takes a lot of cpu on my pi and i don't need it.

So it would be nice if it could be possible to disable it in settings.

Regards
Manuel

**Comment by BillyBlaze** [comment]
Hi Manuel,

If you want to save CPU then you need to disabling the webcam program itself. The webcam program generates a jpeg image on your Pi and that gets loaded into OctoPrint/TouchUI, so your CPU wont be affected by disabling it in OctoPrint/TouchUI.

You need to disable `mjpg-streamer` and then you can disable the webcam tab in itself by removing your webcam configuration inside the OctoPrint settings.

TouchUI wont show a camera tab once it's disabled.

**Comment by ManuelW77** [comment]
Hey Billy,
on my Pi 3 touchui (with chromium) uses a lot of cpu, not the mjpg-streamer process.
![screenshot_13](https://user-images.githubusercontent.com/5578010/33529780-930af26a-d875-11e7-9eba-45707b921044.png)

**Comment by BillyBlaze** [comment]
Wow, that is alot of CPU usage.

Do you have any extra plugins installed?

**Comment by ManuelW77** [comment]
The CPU usage is not all the time at this, but goes up and down.
I have some plugins installed, but nothing of them came up in the touchui.

Here is the list:
```
2017-12-02 19:20:36,394 - octoprint.plugin.core - INFO - 44 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.6rc1-py2.7.egg/octoprint/plugins/announcements
|  Automatic Shutdown (0.1.4) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_automaticshutdown
|  Autoscroll (0.0.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_autoscroll
|  Autoselect Plugin (0.2.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_autoselect
|  CommandSplitter (0.1.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_commandsplitter
|  Core Wizard (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.6rc1-py2.7.egg/octoprint/plugins/corewizard
|  Cost Estimation (2.0.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_costestimation
| !CuraEngine (<= 15.04) (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.6rc1-py2.7.egg/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_customControl
|  Detailed Progress Plugin (0.1.4) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_detailedprogress
|  Discovery (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.6rc1-py2.7.egg/octoprint/plugins/discovery
|  DisplayZ (0.1.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_displayz
|  Editor Collection (0.1.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_editorcollection
|  EEPROM Marlin Editor Plugin (1.0.4) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Filament Manager (0.4.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_filamentmanager
|  Filament Sensor Reloaded (1.0.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_filamentreload
|  FileManager (0.1.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_filemanager
|  Fullscreen Plugin (0.0.3) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_fullscreen
|  GCODE System Commands (0.1.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_gcodesystemcommands
|  Gcodebar Plugin (0.1.4) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GCodeBar
|  GcodeEditor (0.1.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GcodeEditor
|  Growl (0.1.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_growl
|  HeaterTimeout (0.0.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_HeaterTimeout
|  M117NavBar (0.1.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_M117NavBar
| !Multi Colors (1.0.10) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_multi_colors
|  Nautilus (1.19) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_nautilus
|  Navbar Temperature Plugin (0.8) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_navbartemp
|  Plugin Manager (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.6rc1-py2.7.egg/octoprint/plugins/pluginmanager
|  PortLister (0.1.6) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_portlister
|  Print History Plugin (1.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_printhistory
|  Printer Stats (1.0.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_stats
|  Software Update (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.6rc1-py2.7.egg/octoprint/plugins/softwareupdate
|  Status Line (0.1.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/status_line
|  STL Viewer (0.4.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_stlviewer
|  System Command Editor (0.3.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  Telegram Notifications (1.4.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_telegram
| !TemperatureFailsafe (0.2.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_TemperatureFailsafe
|  Tempsgraph Plugin (0.2.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_tempsgraph
| !Themeify (0.1.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_themeify
|  Title Status (0.0.4) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_title_status
|  TouchUI (0.3.10) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.6rc1-py2.7.egg/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_yamlpatcher
```

**Comment by BillyBlaze** [comment]
That are alot of plugins, they should be loaded into TouchUI.

Can you try disabling these plugins and try again if you have such high CPU usage:
1. STL Viewer
2. Print History

**Comment by ManuelW77** [comment]
I disabled booth plugins, but nothing changed. CPU usage is the same as before.

**Comment by ManuelW77** [comment]
I disables mostly all plugins and can get the cpu usage a bit down to a max of 90%.
I think there is something other wrong.

**Comment by BillyBlaze** [comment]
Hmm, this is weird. So does the CPU drop at all? is it hanging always at +/- 90% now?

Also what version of chromium are you using?

**Comment by ManuelW77** [comment]
Yes, the CPU is dropping also. Going up and down, but while printing it's between 60-120%.

Chromium 60.0.3112.89 Built on Ubuntu 14.04, running on Raspbian 9.1

**Comment by BillyBlaze** [comment]
Thanks for the info! I needed to upgrade some things here in order to see if I can reproduce it.  I am currently stuck on Jessie with Chromium 56. So we know atleast that was stable.

I have a feeling that Chromium 60 on Stretch is not stable yet.

**Comment by BillyBlaze** [comment]
Sorry I still haven't got around to build a new develop environment with Jessie Stretch.

However as I was thinking about this issue, could you check if you're running in touchscreen mode? That mode should disable some CPU heavy things.

**Comment by mmontminy** [comment]
I came here looking for a solution to this, as I'm seeing the same behavior. At first I just assumed chromium was a cpu pig on pi, but when playing around with repetier server, I noticed they also use chromium for the ui, and it sips cpu.

As with the OP, I tried removing most plugins with no real impact. While it's not affected printing, it's a concern that it might.

Per your last comment, I did check that chrome isn't being forced to touchscreen mode via /etc/defaults/touchui. If it's being forced otherwise, I can't say, but I don't see any command line args being passed to chromium that would do so.

I know this is a pretty old issue, but I'm hoping someone's found a solution to this.

**Comment by jph290** [comment]
@mmontminy  I am also seeing the same thing.  Just setup TouchUI with the official raspberry pi touchscreen.  Chromium has gone up to 134% (must be more than 1 cores worth).

**Comment by ksztibor** [comment]
I also experience the high cpu usage (about 120%) of chromium occasionally, when touchui is used.

**Comment by Adrian-at-CrimsonAzure** [comment]
I'd like to ask if we can disable _any_ tab when TouchUI is enabled. If I'm mounting this to my printer, I also don't need to access the Timelapse or Octolapse tabs for example.

**Comment by stepman0** [comment]
Anything new on this issue. I have a similar problem with high load due to camera - which is not needed next to the printer. But I need the camera for remote access...

**Comment by TheRealAlexV** [comment]
This is also a problem for me. I have an rpi4 with the official 7" touchscreen. When the touchui is open chromium runs at around 130%.

@BillyBlaze is this an issue still on your radar?
