### ISSUE TITLE
Cannot get touch ui to boot to browser, goes to login prompt

### ISSUE THREAD

**Issue by DBaker85** [BillyBlaze/OctoPrint-TouchUI#175]
So I have been trying for a couple of days to get this working but I just cannot. 
These are the steps I followed:

### Setup [lcdshow](https://github.com/goodtft/LCD-show)

this results in this message: 
`pi@octopi: sudo ./LCD35-show
   cp: cannot create regular file "/usr/share/X11/xorg.conf.d/": Not a directory
   this is not raspberrypi kernel, no need to update touch configure, reboot`

It works though

### Install touch ui
This works

### Follow install steps
`sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config` 
This step fails

### Reboot:
Everything works but I stay stuck on the login prompt no black or white screen

### Addtitional step
edit `/etc/X11/xorg.conf.d/99-fbdev.conf`

Still nothing but octoprint works fine on network

I have no idea what to do now. Any help would be greatly appreciated

**Comment by BillyBlaze** [comment]
Hi,

Can you share the contents of ```/var/log/Xorg.0.log```

**Comment by DBaker85** [comment]
Here you go,  Also forgot to mention I am using a pi3 and a 3.5inch gpio xpt2046 screen

[    12.236]
X.Org X Server 1.18.4
Release Date: 2016-07-19
[    12.236] X Protocol Version 11, Revision 0
[    12.236] Build Operating System: Linux 4.4.26-v7+ armv7l Raspbian
[    12.236] Current Operating System: Linux octopi 4.9.28-v7+ #998 SMP Mon May 15 16:55:39 BST 2017 armv7l
[    12.236] Kernel command line: 8250.nr_uarts=1 bcm2708_fb.fbwidth=640 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_$
[    12.236] Build Date: 11 November 2016  11:59:59AM
[    12.236] xorg-server 2:1.18.4-2+rpi1 (https://www.debian.org/support)
[    12.237] Current version of pixman: 0.33.3
[    12.237]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[    12.237] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    12.237] (==) Log file: "/var/log/Xorg.0.log", Time: Tue Dec  5 12:08:30 2017
[    12.311] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    12.311] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    12.479] (==) No Layout section.  Using the first Screen section.
[    12.479] (==) No screen section available. Using defaults.
[    12.480] (**) |-->Screen "Default Screen Section" (0)
[    12.480] (**) |   |-->Monitor "<default monitor>"
[    12.509] (==) No device specified for screen "Default Screen Section".
        Using the first device section listed.
[    12.509] (**) |   |-->Device "touchscreen"
[    12.509] (**) |   |-->GPUDevice "touchscreen"
[    12.509] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[    12.509] (==) Automatically adding devices
[    12.509] (==) Automatically enabling devices
[    12.509] (==) Automatically adding GPU devices
[    12.539] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    12.548] (WW) The directory "/usr/share/fonts/X11/misc" does not exist.
[    12.548]    Entry deleted from font path.
[    12.548] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    12.548]    Entry deleted from font path.
[    12.548] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    12.548]    Entry deleted from font path.
[    12.548] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    12.548]    Entry deleted from font path.
[    12.549] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    12.549]    Entry deleted from font path.
[    12.549] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    12.549]    Entry deleted from font path.
[    12.549] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    12.549]    Entry deleted from font path.
[    12.549] (==) FontPath set to:
        built-ins
[    12.549] (==) ModulePath set to "/usr/lib/xorg/modules"
[    12.549] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[    12.549] (II) Loader magic: 0x54cd8f20
[    12.549] (II) Module ABI versions:
[    12.549]    X.Org ANSI C Emulation: 0.4
[    12.549]    X.Org Video Driver: 20.0
[    12.549]    X.Org XInput driver : 22.1
[    12.549]    X.Org Server Extension : 9.0
[    12.553] (--) using VT number 2

[    12.553] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    12.553] (II) no primary bus or device found
[    12.558] (II) LoadModule: "glx"
[    12.598] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    12.878] (II) Module glx: vendor="X.Org Foundation"
[    12.878]    compiled for 1.18.4, module version = 1.0.0
[    12.878]    ABI class: X.Org Server Extension, version 9.0
[    12.878] (==) AIGLX enabled
[    12.878] (II) LoadModule: "fbdev"
[    12.879] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[    12.892] (II) Module fbdev: vendor="X.Org Foundation"
[    12.892]    compiled for 1.18.4, module version = 0.4.4
[    12.892]    Module class: X.Org Video Driver
[    12.892]    ABI class: X.Org Video Driver, version 20.0
[    12.892] (II) FBDEV: driver for framebuffer: fbdev
[    12.899] (WW) Falling back to old probe method for fbdev
[    12.899] (II) Loading sub module "fbdevhw"
[    12.899] (II) LoadModule: "fbdevhw"
[    12.900] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    12.913] (II) Module fbdevhw: vendor="X.Org Foundation"
[    12.913]    compiled for 1.18.4, module version = 0.0.2
[    12.914]    ABI class: X.Org Video Driver, version 20.0
[    12.914] (II) FBDEV(0): using /dev/fb1
[    12.914] (II) FBDEV(1): using /dev/fb1
[    12.914] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[    12.914] (EE) Screen 1 deleted because of no matching config section.
[    12.914] (II) UnloadModule: "fbdev"
[    12.914] (II) UnloadSubModule: "fbdevhw"
[    12.914] (II) FBDEV(0): Creating default Display subsection in Screen section
        "Default Screen Section" for depth/fbbpp 16/16
[    12.915] (==) FBDEV(0): Depth 16, (==) framebuffer bpp 16
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[    12.915] (==) FBDEV(0): RGB weight 565
[    12.915] (==) FBDEV(0): Default visual is TrueColor
[    12.915] (==) FBDEV(0): Using gamma correction (1.0, 1.0, 1.0)
[    12.915] (II) FBDEV(0): hardware: fb_ili9486 (video memory: 300kB)
[    12.915] (**) FBDEV(0): Option "fbdev" "/dev/fb1"
[    12.915] (II) FBDEV(0): checking modes against framebuffer device...
[    12.915] (II) FBDEV(0): checking modes against monitor...
[    12.915] (--) FBDEV(0): Virtual size is 480x320 (pitch 480)
[    12.915] (**) FBDEV(0):  Built-in mode "current"
[    12.915] (==) FBDEV(0): DPI set to (96, 96)
[    12.915] (II) Loading sub module "fb"
[    12.915] (II) LoadModule: "fb"
[    12.916] (II) Loading /usr/lib/xorg/modules/libfb.so
[    12.951] (II) Module fb: vendor="X.Org Foundation"
[    12.951]    compiled for 1.18.4, module version = 1.0.0
[    12.952]    ABI class: X.Org ANSI C Emulation, version 0.4
[    12.952] (**) FBDEV(0): using shadow framebuffer
[    12.952] (II) Loading sub module "shadow"
[    12.952] (II) LoadModule: "shadow"
[    12.952] (II) Loading /usr/lib/xorg/modules/libshadow.so
[    12.979] (II) Module shadow: vendor="X.Org Foundation"
[    12.979]    compiled for 1.18.4, module version = 1.1.0
[    12.980]    ABI class: X.Org ANSI C Emulation, version 0.4
[    12.980] (II) FBDEV(0): FBIOBLANK: Invalid argument (Screen blanking not supported by kernel - disabling)
[    13.043] (==) FBDEV(0): Backing store enabled
[    13.056] (==) FBDEV(0): DPMS enabled
[    13.064] (==) RandR enabled
[    13.121] (II) SELinux: Disabled on system
[    13.132] (II) AIGLX: Screen 0 is not DRI2 capable
[    13.132] (EE) AIGLX: reverting to software rendering
[    13.132] (EE) AIGLX error: dlopen of /usr/lib/arm-linux-gnueabihf/dri/swrast_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/swrast_dri.so: cannot open shared object file: $
[    13.132] (EE) GLX: could not load software renderer
[    13.132] (II) GLX: no usable GL providers found for screen 0
[    13.208] (EE) Error compiling keymap (server-0)
[    13.208] (EE) XKB: Couldn't compile keymap
[    13.208] (EE) XKB: Failed to load keymap. Loading default keymap instead.
[    13.236] (EE) Error compiling keymap (server-0)
[    13.237] (EE) XKB: Couldn't compile keymap
[    13.237] XKB: Failed to compile keymap
[    13.237] Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
[    13.237] (EE)
Fatal server error:
[    13.237] (EE) Failed to activate core devices.(EE)
[    13.237] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[    13.237] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[    13.237] (EE)
[    13.246] (EE) Server terminated with error (1). Closing log file.

**Comment by DBaker85** [comment]
I am about to give up on this.
Should I just install the desktop env and launch it from there?
I think the pi 3 should be able to handle it, being multi core and all...

**Comment by BillyBlaze** [comment]
Sorry, I have no idea whats going on, I can't reproduce your issue. Building a full jessie will make it easier to setup xserver. since that is pre-configured.

Just checking some stuff I found other websites with the same error:
```
[ 13.237] (EE) XKB: Couldn't compile keymap
[ 13.237] XKB: Failed to compile keymap
[ 13.237] Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
[ 13.237] (EE)
Fatal server error:
[ 13.237] (EE) Failed to activate core devices.(EE)
```

Do you have enough disk left? Did you install anything else except LCD-show driver?

**Comment by DBaker85** [comment]
I did not install anything else no. I have an 8gb card. 
Might be a little light, but should be enough right?

I will try with a full Jessie build then adding octoprint and touch ui on top.
Or I might just go for the desktop env and see how that goes. I will run some tests during the next couple of days and let you know

**Comment by BillyBlaze** [comment]
This is a bizar error I have never encountered before or have been reported before. 

Did you try to rebuild it from scratch? Perhaps something went wrong during setup with dependencies.

If your reluctant todo this, you could try to see what the outcome is of the follow steps:
1. Check your disk space with `df -h`
2. `ls ~/.Xauthority -al`
2. `ls /tmp/ -al`
2. `ls /var/tmp/ -al`

**Comment by DBaker85** [comment]
### 1.
 Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.3G  1.7G  5.3G  25% /
devtmpfs        458M     0  458M   0% /dev
tmpfs           462M     0  462M   0% /dev/shm
tmpfs           462M  6.3M  456M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           462M     0  462M   0% /sys/fs/cgroup
/dev/mmcblk0p1   41M   21M   21M  51% /boot

### 2
`ls: cannot access /home/pi/.Xauthority: No such file or directory`

### 3
total 32
drwxrwxrwt  8 root root 4096 Dec  8 21:10 .
drwxr-xr-x 22 root root 4096 Jun 21 09:49 ..
drwxrwxrwt  2 root root 4096 Dec  8 21:09 .font-unix
drwxrwxrwt  2 root root 4096 Dec  8 21:09 .ICE-unix
drwxr-xr-x  3 pi   pi   4096 Dec  8 21:10 pip-7C1bEn-build
drwxrwxrwt  2 root root 4096 Dec  8 21:09 .Test-unix
drwxrwxrwt  2 root root 4096 Dec  8 21:10 .X11-unix
drwxrwxrwt  2 root root 4096 Dec  8 21:09 .XIM-unix

### 4
total 8
drwxrwxrwt  2 root root 4096 Dec  8 21:10 .
drwxr-xr-x 11 root root 4096 Jun 21 09:49 ..

I am not against rebuilding it, i have in fact tried and lost many hours of my life.. I am not that good at linux so yeah... Also to mention I tried a waveshare hdmi screen also and could not get it to work...

I just found a 16gb card. Should I try that?

**Comment by DBaker85** [comment]
Well it seems your instinct was correct. 
I found a 16gb card (Lucky find!) and redid all the steps and it worked perfectly the first time. 
I have no idea if the space was the problem or if the card itself was faulty. 

Well I suppose now you can add a section to the wiki that says to try a different/bigger card if you have weird issues.

Thanks for your time and effort to help me out!

**Comment by BillyBlaze** [comment]
Phew! Glad that you where able to make it work.

Everything else looked okay, you had enough disk space, all rights look good, I just have no idea what caused this, and to be frankly I don't even wanna know at this stage because debugging apt-get would be hell.

Your welcome and enjoy 👍
