### ISSUE TITLE
Cannot clear Octoprint info pop ups

### ISSUE THREAD

**Issue by drewk2u** [BillyBlaze/OctoPrint-TouchUI#176]
When I get octoprint new release or info pop ups. Some go down below where I cannot click on my 7 inch pi screen. I can scroll, but the pop ups don't move. How can I clear them or should I just disable pop ups? I cannot cancel prints because the confirmation window doesn't come up, I have to cancel from my phone or conputer.

**Comment by BillyBlaze** [comment]
Thanks for reporting. I have reproduced the issue and will fix this in the upcoming release.

**Comment by drewk2u** [comment]
I was actually wondering if rotating the screen would at least make it
easier to read them.

Thank you.
Andrew
