### ISSUE TITLE
Cant initiate a print 

### ISSUE THREAD

**Issue by cwem3d** [BillyBlaze/OctoPrint-TouchUI#177]
With my RPI 3 w/ octoprint and touch ui I can not get it to print it works fine on my phone but not the PI.
https://youtu.be/cVToxRrn2Gw
OctoPrint 1.3.6 on OctoPrint 0.14.0

**Comment by BillyBlaze** [comment]
Hi, Thanks for reporting. It seems I cannot reproduce your issue at the moment.

Can you provide some more information with the Octoprint log and if there is any error thrown inside the browser console?

To get the browser console, you might be better off to navigate with Chrome to OctoPrint on a computer and extract it from there.

**Comment by cwem3d** [comment]
Where exactly can I find the logs in Windows?

**Comment by BillyBlaze** [comment]
should be under `%APPDATA%/OctoPrint`

**Comment by cwem3d** [comment]
There is no octoprint folder in apdata.

**Comment by BillyBlaze** [comment]
sorry, I misunderstood you, OctoPrint is installed on your RPI, so the log should be there under `~/.octoprint/log` on your Pi.

**Comment by BillyBlaze** [comment]
in addition you can also download the log from OctoPrint interface under `Settings > Logs`

**Comment by cwem3d** [comment]
https://drive.google.com/file/d/12YssES9e72BdiIBg6ARFMPA6AJZXB2Um/view?usp=sharing

**Comment by cwem3d** [comment]
Could it be do to me using m33 fio with a M3D

**Comment by BillyBlaze** [comment]
Yeah, M33 Fio is a very bad plugin that breaks OctoPrint when running it on a raspberry Pi.

Since the plugin is not using the standards of OctoPrint, I am unable to prevent it from loading on a Pi.

**Comment by cwem3d** [comment]
Will M33 FIO be supported by your plugin further down the road?

**Comment by BillyBlaze** [comment]
Not by me, it's unworkable and I would lose my sanity and jump out of the window.

On a serious note; I would be willing to accept pull-requests but I will not actively develop for that plugin. It just does to many things on multiple non-octoprint way. For example; it directly executes javascript and doesn't follow the 'octoprint way'. It's impossible to stop it from loading and cleaning up the mess would be alot of time I don't even have to start with.
