### ISSUE TITLE
Possible to change layout?

### ISSUE THREAD

**Issue by areonic** [BillyBlaze/OctoPrint-TouchUI#185]
Hello, I was wondering if it would be something hard to change how the touchui layout is. Like, would it be possible to just have it load into a screen with buttons to move the print head, and stuff. I know you have a tab for that, but the screens we are using it has became nuts trying to get it right without taking 10mins, to move the print head or shut down. I didnt want to go into full detail before seeing if it was something huge, so I didnt waste you time too much.

Thank you,
Shawn

**Comment by BillyBlaze** [comment]
Hi Shawn,

This is currently not possible. I will mark this as a feature request because I need to change code in order to allow this.

**Comment by StefanMeGit** [comment]
i also have a quiet big screen and would love it to change the layout!

**Comment by BillyBlaze** [comment]
Is this feature request still necesary since OctoPrint now supports deep-linking to tabs? e.g. http://octopi.local/#control

**Comment by vibestrakt** [comment]
too bad :(
I also have a wide screen and I could fit all the tab in my screen
Would it be possible to have a general tab with temperature , webcam, gcode and maybe control on the same page
