### ISSUE TITLE
Screen rotation

### ISSUE THREAD

**Issue by DirtyDerv** [BillyBlaze/OctoPrint-TouchUI#186]
I have followed al the guides but i cannot get the screen to rotate 180(or any) degrees

My cursor also moves up and down if i swipe left and right and left and right if i swipe up and down

Any ideas on what else i could try please

**Comment by BillyBlaze** [comment]
Hi @DirtyDerv,

I assume you've tried the [troubleshooting section](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#calibration-rotate-touchscreen).

If that didn't work, then depending on your driver, the configuration can differ and I cannot keep up-to-date with these developments. Please consult the manufacture documentation on how to change the rotation.
