### ISSUE TITLE
Separate option for defaulting on small screens from option for defaulting on touch devices.

### ISSUE THREAD

**Issue by andrewsil1** [BillyBlaze/OctoPrint-TouchUI#188]
The problem is that a PC with a large touch screen, like the Microsoft Surface devices, will default to touchUI when the regular web UI would be more appropriate.  However, it doesn’t appear that this can be turned off without also turning off the default to enable touch UI for screens of a low x/y dimension.  Separating these settings would allow this to work better in this scenario.

**Comment by BillyBlaze** [comment]
Thanks for the request. I'll implement it in the upcoming version!
