### ISSUE TITLE
[HELP!] TouchIU always "freezing" on local

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#191]
Please HELP!

I've been a huge fan and user of Octoprint/TouchUI since the very beginning and from the last few octoprint updates, I'm experiencing TouchUI crashes on LOCAL display touch (official Raspi 7") while the raspi operates fine on the LAN via computer web browsers and such...

I've done apt-get update/upgrades to no avail and reinstalled TouchUI from scratch just in case, but as soon as it reboots and I start clicking here and there (touching the screen, that is), the thing starts to LAAAAG heavily until collapsing with a chromium "kill this app or wait" screen :/

I dont know what else to try, can't understand whats the issue.

Running on Raspi3 1.2 with official power supply.

Thanks!

**Comment by bolsoncerrado** [comment]
OK I started by disabling ALL plugins except Gina's and TouchUI and it's stable now, will start investigate the plugin conflict.... I may suspect it has to do with the TAB ORDER plugin.

**Comment by BillyBlaze** [comment]
Sorry for the long delay and thanks for the feedback.

Please let me know if you have found the culprit!

**Comment by bolsoncerrado** [comment]
It's indeed a conflict of plugins. Not sure 109% which one but I still think it may be the Tabs one.

**Comment by TheNore** [comment]
This is also happening to me! and I have the Tabs order plugin, unfortunately I do need to have this plugin working. I am running version  0.3.12 of touch UI and 0.5.0 for TabsOrder. I am running octoprint 1.3.9 On a RasPi3+
i run my printer constantly and have ONLY noticed TouchUI freezing, resetting, and stopping my server after this plugin was installed :( After my print completes I have to unplug my RasPi to reset.
