### ISSUE TITLE
iPhone x room for one more tab on top of screen?

### ISSUE THREAD

**Issue by LazaroFilm** [BillyBlaze/OctoPrint-TouchUI#192]
Hi, 
On the iPhone X, it feels like there would be enough room to display one more tab instead of having it hidden in the drop down menu. Maybe shrinking the width of the tabs just a bit would allow for that? 
Also is there a way to organize which tab is showing on the top bar? 
See screenshot: https://i.imgur.com/zGgMFcf.png

**Comment by BillyBlaze** [comment]
Sorry for the long delay and thanks for the feedback.

I'll optimize the width on smaller resolutions in the upcoming release.

**Comment by LazaroFilm** [comment]
Thanks! iPhone X's definition is 2436-by-1125-pixel. but the web pages are dividing the pixel count by a factor 3 so the effective screen resolution is 812px x 375px. so we are just 17 pixels shorts of displaying 4 tabs (3 icons + menu) each tab would have to be a max of 93px to fit in the screen instead of 98px

**Comment by BillyBlaze** [comment]
Thanks, this has been released in 0.3.12
