### ISSUE TITLE
99-fbturbo.conf missing

### ISSUE THREAD

**Issue by syliak** [BillyBlaze/OctoPrint-TouchUI#193]
Hi everyone,
I got first an issue when I tried this cmd: 
sudo mv /usr/share/X11/xorg.conf.d/99-fbturbo.conf ~
After I found out that the the files were missing, so I downloaded the needed package:
sudo apt-get install xserver-xorg-video-fbdev (It creates the file: /usr/share/X11/xorg.conf.d/99-fbdev.conf)
but unfortunately the file 99-fbdev.conf has not been created.
Please if you can help

**Comment by BillyBlaze** [comment]
Hi @syliak,

Sorry for the delayed response.
Running `sudo nano /usr/share/X11/xorg.conf.d/99-fbdev.conf` will still create the file even if it doesn't exist.

If the setup still doesn't work then please share your log under `/var/log/xorg.0.log`
