### ISSUE TITLE
Make keyboard taller/customizable

### ISSUE THREAD

**Issue by kazolar** [BillyBlaze/OctoPrint-TouchUI#197]
With a 800x480 touch screen, the virtual keyboard is very hard to operate, especially buttons to switch letters to numbers, and accept dismiss are so close together that often times the click is registered on the wrong one. In horizontal mode, it is practically unusable. In vertical mode it's a bit better, but I would prefer to have the keyboard be 2 times taller to make the touch targets bigger. Is that changeable with style sheets/overrides?

**Comment by BillyBlaze** [comment]
Hi @kazolar,

You can definitely change it yourself. You can [include your own LESS file](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Customize:-Use-your-own-file) to override the styles. If you want to fix this on the short term then I would suggest this.

On the long term, I can definitely look if I can tweak the layout for lower resolutions.
