### ISSUE TITLE
Raspberry Pi connected to internet but not showing IP address after reinstallation. 

### ISSUE THREAD

**Issue by Braxstonwithans** [BillyBlaze/OctoPrint-TouchUI#198]
I cleared my SD card and reinstalled Rapberry Pi for Noobs on it and now I can't SSH into the device. I reinstalled raspberry pi because the device would randomly reboot. Please help!

**Comment by BillyBlaze** [comment]
Hi, for this kind of questions you're better off in the Raspberry Pi communities (e.g. forum) or the OctoPrint community. I have no experience solving your issue.

Good luck!
