### ISSUE TITLE
TouchUI not displaying on touch screen but displays on webui

### ISSUE THREAD

**Issue by ianjolin** [BillyBlaze/OctoPrint-TouchUI#199]
I had some issues early on and could not get my RPi touchscreen UI to display. I installed the TOuchUI prior to getting my touchscreen UI operational. I attempted an uninstall reinstall with the same results.
I assume this is a minor fix but I am unsure where to start, any help would be appreciated.

**Comment by BillyBlaze** [comment]
Duplicate of #200 ?
