### ISSUE TITLE
Webcam works, but "webcam stream not loaded" message shows up

### ISSUE THREAD

**Issue by salfter** [BillyBlaze/OctoPrint-TouchUI#207]
I was playing around with Touch UI on an old tablet that I might dedicate to printer control...looks like it's mostly working, but the webcam view looks like the attached screenshot:

![screenshot_20180415-194637](https://user-images.githubusercontent.com/1380958/38788341-02d62ea4-40e8-11e8-87e8-538b714c1e70.png)

(If it matters, the device is a Samsung Galaxy Tab 2 7.0 (did I mention it was old?), running Lineage OS 13.  I've rooted it and installed Chrome, and I launch OctoPrint from a homescreen shortcut.)

**Comment by salfter** [comment]
Another datapoint: the same thing happens with a Moto Z Play running the latest available Android release.

**Comment by salfter** [comment]
Another datapoint: I'm running the latest OctoPrint, installed onto Raspbian.

**Comment by BillyBlaze** [comment]
Sorry for the long delay, I am unable to look at this and will be looking into this as soon as I am able to.

**Comment by Cub3squar3d** [comment]
The issue might be related to the interaction with another plugin: WebcamTab.
Since TouchUi already moves che webcam to it's own tab.
Uninstalling the plugin resolves the issue.

**Comment by BillyBlaze** [comment]
Thanks for the feedback @Cub3squar3d, seems like both plugins try to do the same.

@salfter can you confirm this is the same issue for you?

If yes, then we can fix this by disabling WebcamTab if TouchUI is active

**Comment by salfter** [comment]
I just got my OctoPrint setup fully running again a couple of hours ago (replaced a failing motherboard on my A8 with a RAMPS and needed a longer cable for the camera).  My printer's  busy with a print job right now; I'll try disabling WebcamTab when it's done.

**Comment by salfter** [comment]
Looks like disabling WebcamTab did the trick.

**Comment by AfroPsycho** [comment]
Hi,
I have the same issue 
WebcamTab plugin is not installed  
And the webcam is working normally
But if I m not wrong Fullscreen Webcam plugin is working

**Comment by BillyBlaze** [comment]
Thanks for the confirmation, in the upcoming release the webcamTab plugin will be disabled when TouchUI is active.

@AfroPsycho, if you have a different issue then the original poster then please create a new issue, I cannot keep focus if multiple issues are reported in one issue.

**Comment by AfroPsycho** [comment]
If upcoming release won't solve my issue than I will be in touch

Best regards,
Bora Hoşadam

Paul de Vries <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (2 Eyl 2018 00:03):


Thanks for the confirmation, in the upcoming release the webcamTab plugin will be disabled when TouchUI is active.

@AfroPsycho<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAfroPsycho&data=02%7C01%7C%7C6ec72d58bd764db4a9f008d6104e6b7d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636714326324384452&sdata=O3FEbsfE9bZtj7AesgwuT5xlN2%2BIVhzVpfQrlL%2BvSCU%3D&reserved=0>, if you have a different issue then the original poster then please create a new issue, I cannot keep focus if multiple issues are reported in one issue.

**Comment by BillyBlaze** [comment]
This has been released in 0.3.12
