### ISSUE TITLE
touchscreen does not launch touchui

### ISSUE THREAD

**Issue by ianjolin** [BillyBlaze/OctoPrint-TouchUI#209]
I have a fresh install of v138. The first plugin I installed was touchui, then I installed the pi desktop environment via cmd line and it does not seem to launch either via web access or the desktop. 
When I access the UI via another machine the TouchUI gui is accessible and operable but its not present and does not automatically launch on the pi touchscreen.
Are there test that I can run or area I can check to determine why this may not be launching?

**Comment by BillyBlaze** [comment]
Sorry for the long delay, I am unable to look at this and will be looking into this as soon as I am able to.

**Comment by PlastiBots** [comment]
Edit:. Got mine working. Documented my experience here.  http://www.plastibots.com/index.php/2018/06/02/adding-tft-lcd-to-raspberry-pi-octopi-rig-touchui/


+1.  I have this same issue. Followed the instructions. Did a fresh install of OctoPi, then followed instructions in the wiki to install TouchUI. Also installed LCD-show.  The TFT shows all the boot cmd line stuff as the Pi starts up.  When done, it shows "octopi login:" and does not boot to TouchUI.    I am using the Banggood 3.5" TFT.

**Comment by BillyBlaze** [comment]
Hi @ianjolin,

Sorry for the delayed response. Could you perhaps share the contents of `/var/log/Xorg.0.log`?

@PlastiBots 
Thanks for sharing that!!

**Comment by ianjolin** [comment]
Here is my log file.

 

The autostart doesn’t launch on my touchscreen.

**Comment by BillyBlaze** [comment]
@ianjolin, I don't see anything.

**Comment by ianjolin** [comment]
You didn’t receive an attached file?

**Comment by BillyBlaze** [comment]
Nope, there are no files attached to your comment.

**Comment by ianjolin** [comment]
Here is the contents of the log

 

[     6.095] 

X.Org X Server 1.19.2

Release Date: 2017-03-02

[     6.095] X Protocol Version 11, Revision 0

[     6.095] Build Operating System: Linux 4.9.41-v7+ armv7l Raspbian

[     6.095] Current Operating System: Linux octopi 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l

[     6.095] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=266d4ded-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles

[     6.096] Build Date: 18 October 2017  04:55:30PM

[     6.096] xorg-server 2:1.19.2-1+rpt1+deb9u2 (https://www.debian.org/support) 

[     6.096] Current version of pixman: 0.34.0

[     6.096]            Before reporting problems, check http://wiki.x.org

                to make sure that you have the latest version.

[     6.096] Markers: (--) probed, (**) from config file, (==) default setting,

                (++) from command line, (!!) notice, (II) informational,

                (WW) warning, (EE) error, (NI) not implemented, (??) unknown.

[     6.096] (==) Log file: "/var/log/Xorg.0.log", Time: Tue Sep  4 12:45:27 2018

[     6.109] (==) Using system config directory "/usr/share/X11/xorg.conf.d"

[     6.124] (==) No Layout section.  Using the first Screen section.

[     6.125] (==) No screen section available. Using defaults.

[     6.125] (**) |-->Screen "Default Screen Section" (0)

[     6.125] (**) |   |-->Monitor "<default monitor>"

[     6.134] (==) No device specified for screen "Default Screen Section".

                Using the first device section listed.

[     6.134] (**) |   |-->Device "touchscreen"

[     6.134] (**) |   |-->GPUDevice "Allwinner A10/A13 FBDEV"

[     6.134] (==) No monitor specified for screen "Default Screen Section".

                Using a default monitor configuration.

[     6.134] (==) Automatically adding devices

[     6.135] (==) Automatically enabling devices

[     6.135] (==) Automatically adding GPU devices

[     6.146] (==) Max clients allowed: 256, resource mask: 0x1fffff

[     6.177] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.

[     6.177]            Entry deleted from font path.

[     6.177] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.

[     6.177]            Entry deleted from font path.

[     6.177] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.

[     6.177]            Entry deleted from font path.

[     6.177] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.

[     6.177]            Entry deleted from font path.

[     6.177] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.

[     6.177]            Entry deleted from font path.

[     6.177] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.

[     6.178]            Entry deleted from font path.

[     6.178] (==) FontPath set to:

                /usr/share/fonts/X11/misc,

                built-ins

[     6.178] (==) ModulePath set to "/usr/lib/xorg/modules"

[     6.178] (II) The server relies on udev to provide the list of input devices.

                If no devices become available, reconfigure udev or disable AutoAddDevices.

[     6.186] (II) Loader magic: 0x1fbf40

[     6.186] (II) Module ABI versions:

[     6.186]            X.Org ANSI C Emulation: 0.4

[     6.186]            X.Org Video Driver: 23.0

[     6.186]            X.Org XInput driver : 24.1

[     6.186]            X.Org Server Extension : 10.0

[     6.192] (--) using VT number 2

 

[     6.192] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration

[     6.193] (II) no primary bus or device found

[     6.199] (II) LoadModule: "glx"

[     6.239] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so

[     6.372] (II) Module glx: vendor="X.Org Foundation"

[     6.372]            compiled for 1.19.2, module version = 1.0.0

[     6.372]            ABI class: X.Org Server Extension, version 10.0

[     6.372] (II) LoadModule: "fbdev"

[     6.373] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so

[     6.384] (II) Module fbdev: vendor="X.Org Foundation"

[     6.384]            compiled for 1.19.0, module version = 0.4.4

[     6.384]            Module class: X.Org Video Driver

[     6.384]            ABI class: X.Org Video Driver, version 23.0

[     6.384] (II) LoadModule: "fbturbo"

[     6.385] (II) Loading /usr/lib/xorg/modules/drivers/fbturbo_drv.so

[     6.391] (II) Module fbturbo: vendor="X.Org Foundation"

[     6.391]            compiled for 1.19.2, module version = 0.5.1

[     6.391]            Module class: X.Org Video Driver

[     6.391]            ABI class: X.Org Video Driver, version 23.0

[     6.391] (II) FBDEV: driver for framebuffer: fbdev

[     6.391] (II) FBDEV: driver for framebuffer: fbdev

[     6.399] (WW) Falling back to old probe method for fbdev

[     6.399] (II) Loading sub module "fbdevhw"

[     6.399] (II) LoadModule: "fbdevhw"

[     6.400] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so

[     6.403] (II) Module fbdevhw: vendor="X.Org Foundation"

[     6.403]            compiled for 1.19.2, module version = 0.0.2

[     6.404]            ABI class: X.Org Video Driver, version 23.0

[     6.404] (II) FBDEV(0): using /dev/fb0

[     6.404] (WW) Falling back to old probe method for fbdev

[     6.404] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support

[     6.404] (II) FBDEV(0): Creating default Display subsection in Screen section

                "Default Screen Section" for depth/fbbpp 24/32

[     6.404] (==) FBDEV(0): Depth 24, (==) framebuffer bpp 32

[     6.404] (==) FBDEV(0): RGB weight 888

[     6.404] (==) FBDEV(0): Default visual is TrueColor

[     6.404] (==) FBDEV(0): Using gamma correction (1.0, 1.0, 1.0)

[     6.404] (II) FBDEV(0): hardware: BCM2708 FB (video memory: 1500kB)

[     6.405] (**) FBDEV(0): Option "fbdev" "/dev/fb0"

[     6.405] (II) FBDEV(0): checking modes against framebuffer device...

[     6.405] (II) FBDEV(0): checking modes against monitor...

[     6.405] (--) FBDEV(0): Virtual size is 800x480 (pitch 800)

[     6.405] (**) FBDEV(0):  Built-in mode "current"

[     6.405] (==) FBDEV(0): DPI set to (96, 96)

[     6.405] (II) Loading sub module "fb"

[     6.405] (II) LoadModule: "fb"

[     6.406] (II) Loading /usr/lib/xorg/modules/libfb.so

[     6.412] (II) Module fb: vendor="X.Org Foundation"

[     6.412]            compiled for 1.19.2, module version = 1.0.0

[     6.412]            ABI class: X.Org ANSI C Emulation, version 0.4

[     6.412] (**) FBDEV(0): using shadow framebuffer

[     6.412] (II) Loading sub module "shadow"

[     6.412] (II) LoadModule: "shadow"

[     6.413] (II) Loading /usr/lib/xorg/modules/libshadow.so

[     6.422] (II) Module shadow: vendor="X.Org Foundation"

[     6.422]            compiled for 1.19.2, module version = 1.1.0

[     6.422]            ABI class: X.Org ANSI C Emulation, version 0.4

[     6.422] (II) UnloadModule: "fbturbo"

[     6.422] (II) Unloading fbturbo

[     6.423] (==) Depth 24 pixmap format is 32 bpp

[     6.455] (==) FBDEV(0): Backing store enabled

[     6.464] (==) FBDEV(0): DPMS enabled

[     6.467] (==) RandR enabled

[     6.528] (II) SELinux: Disabled on system

[     6.541] (II) AIGLX: Screen 0 is not DRI2 capable

[     6.541] (EE) AIGLX: reverting to software rendering

[     8.147] (II) IGLX: enabled GLX_MESA_copy_sub_buffer

[     8.152] (II) IGLX: Loaded and initialized swrast

[     8.152] (II) GLX: Initialized DRISWRAST GL provider for screen 0

[     8.522] (II) config/udev: Adding input device Telink Wireless Receiver (/dev/input/event0)

[     8.522] (**) Telink Wireless Receiver: Applying InputClass "libinput pointer catchall"

[     8.522] (**) Telink Wireless Receiver: Applying InputClass "libinput keyboard catchall"

[     8.522] (II) LoadModule: "libinput"

[     8.523] (II) Loading /usr/lib/xorg/modules/input/libinput_drv.so

[     8.554] (II) Module libinput: vendor="X.Org Foundation"

[     8.554]            compiled for 1.19.0, module version = 0.23.0

[     8.554]            Module class: X.Org XInput Driver

[     8.554]            ABI class: X.Org XInput driver, version 24.1

[     8.554] (II) Using input driver 'libinput' for 'Telink Wireless Receiver'

[     8.554] (**) Telink Wireless Receiver: always reports core events

[     8.555] (**) Option "Device" "/dev/input/event0"

[     8.555] (**) Option "_source" "server/udev"

[     8.559] (II) input device 'Telink Wireless Receiver', /dev/input/event0 is tagged by udev as: Keyboard Mouse

[     8.559] (II) input device 'Telink Wireless Receiver', /dev/input/event0 is a pointer caps

[     8.560] (II) input device 'Telink Wireless Receiver', /dev/input/event0 is a keyboard

[     8.601] (II) libinput: Telink Wireless Receiver: needs a virtual subdevice

[     8.601] (**) Option "config_info" "udev:/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:248A:FF0F.0001/input/input0/event0"

[     8.601] (II) XINPUT: Adding extended input device "Telink Wireless Receiver" (type: MOUSE, id 6)

[     8.602] (**) Option "AccelerationScheme" "none"

[     8.602] (**) Telink Wireless Receiver: (accel) selected scheme none/0

[     8.603] (**) Telink Wireless Receiver: (accel) acceleration factor: 2.000

[     8.603] (**) Telink Wireless Receiver: (accel) acceleration threshold: 4

[     8.606] (II) input device 'Telink Wireless Receiver', /dev/input/event0 is tagged by udev as: Keyboard Mouse

[     8.607] (II) input device 'Telink Wireless Receiver', /dev/input/event0 is a pointer caps

[     8.607] (II) input device 'Telink Wireless Receiver', /dev/input/event0 is a keyboard

[     8.611] (II) config/udev: Adding input device Telink Wireless Receiver (/dev/input/mouse0)

[     8.612] (II) No input driver specified, ignoring this device.

[     8.612] (II) This device may have been added with another device file.

[     8.616] (II) config/udev: Adding input device Telink Wireless Receiver (/dev/input/event1)

[     8.617] (**) Telink Wireless Receiver: Applying InputClass "libinput keyboard catchall"

[     8.617] (II) Using input driver 'libinput' for 'Telink Wireless Receiver'

[     8.617] (**) Telink Wireless Receiver: always reports core events

[     8.617] (**) Option "Device" "/dev/input/event1"

[     8.617] (**) Option "_source" "server/udev"

[     8.621] (II) input device 'Telink Wireless Receiver', /dev/input/event1 is tagged by udev as: Keyboard

[     8.621] (II) input device 'Telink Wireless Receiver', /dev/input/event1 is a keyboard

[     8.660] (**) Option "config_info" "udev:/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:248A:FF0F.0002/input/input1/event1"

[     8.660] (II) XINPUT: Adding extended input device "Telink Wireless Receiver" (type: KEYBOARD, id 7)

[     8.660] (**) Option "xkb_model" "pc105"

[     8.660] (**) Option "xkb_layout" "gb"

[     8.815] (II) input device 'Telink Wireless Receiver', /dev/input/event1 is tagged by udev as: Keyboard

[     8.815] (II) input device 'Telink Wireless Receiver', /dev/input/event1 is a keyboard

[     8.818] (II) config/udev: Adding input device FT5406 memory based driver (/dev/input/event2)

[     8.818] (**) FT5406 memory based driver: Applying InputClass "libinput touchscreen catchall"

[     8.818] (II) Using input driver 'libinput' for 'FT5406 memory based driver'

[     8.819] (**) FT5406 memory based driver: always reports core events

[     8.819] (**) Option "Device" "/dev/input/event2"

[     8.819] (**) Option "_source" "server/udev"

[     8.821] (II) input device 'FT5406 memory based driver', /dev/input/event2 is tagged by udev as: Touchscreen

[     8.822] (II) input device 'FT5406 memory based driver', /dev/input/event2 is a touch device

[     8.870] (**) Option "config_info" "udev:/sys/devices/virtual/input/input2/event2"

[     8.870] (II) XINPUT: Adding extended input device "FT5406 memory based driver" (type: TOUCHSCREEN, id 8)

[     8.871] (**) Option "AccelerationScheme" "none"

[     8.871] (**) FT5406 memory based driver: (accel) selected scheme none/0

[     8.871] (**) FT5406 memory based driver: (accel) acceleration factor: 2.000

[     8.871] (**) FT5406 memory based driver: (accel) acceleration threshold: 4

[     8.874] (II) input device 'FT5406 memory based driver', /dev/input/event2 is tagged by udev as: Touchscreen

[     8.874] (II) input device 'FT5406 memory based driver', /dev/input/event2 is a touch device

[     8.876] (II) config/udev: Adding input device FT5406 memory based driver (/dev/input/mouse1)

[     8.876] (II) No input driver specified, ignoring this device.

[     8.877] (II) This device may have been added with another device file.

[     8.906] (**) Telink Wireless Receiver: Applying InputClass "libinput pointer catchall"

[     8.906] (**) Telink Wireless Receiver: Applying InputClass "libinput keyboard catchall"

[     8.906] (II) Using input driver 'libinput' for 'Telink Wireless Receiver'

[     8.906] (**) Telink Wireless Receiver: always reports core events

[     8.906] (**) Option "Device" "/dev/input/event0"

[     8.906] (**) Option "_source" "_driver/libinput"

[     8.907] (II) libinput: Telink Wireless Receiver: is a virtual subdevice

[     8.907] (**) Option "config_info" "udev:/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:248A:FF0F.0001/input/input0/event0"

[     8.907] (II) XINPUT: Adding extended input device "Telink Wireless Receiver" (type: KEYBOARD, id 9)

[     8.907] (**) Option "xkb_model" "pc105"

[     8.907] (**) Option "xkb_layout" "gb"

**Comment by BillyBlaze** [comment]
That looks okay,

What if you try this?
1. stop touchui `sudo service touchui stop`
1. run `sudo xinit ~/TouchUI-autostart/chromium.xinit`
1. post output here

**Comment by Drakogol** [comment]
Im trying to restart this, as im having the same problem and can´t find a solution.
I tried as you suggested and this was the outcome:


pi@octopi:~ $ sudo xinit ~/TouchUI-autostart/chromium.xinit
[sudo] password for pi:


X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.41-v7+ armv7l Raspbian
Current Operating System: Linux octopi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20                   GMT 2018 armv7l
Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1024 bcm2708_fb.fbheight                  =600 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000                    dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=e100d113-02                   rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
Build Date: 18 October 2017  04:55:30PM
xorg-server 2:1.19.2-1+rpt1+deb9u2 (https://www.debian.org/support)
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sun Feb 10 10:00:17 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional info                  rmation.
(EE)
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error

any ideas?

**Comment by Drakogol** [comment]
In another thread i saw some solution and tried this:

pi@octopi:~ $ wget -qO - http://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
OK
pi@octopi:~ $ echo "deb http://dl.bintray.com/kusti8/chromium-rpi jessie main " | sudo tee -a /etc/apt/sources.list
deb http://dl.bintray.com/kusti8/chromium-rpi jessie main
pi@octopi:~ $ sudo apt-get update
E: Malformed entry 4 in list file /etc/apt/sources.list (Component)
E: The list of sources could not be read.
