### ISSUE TITLE
[BUG?] Screen resolution detection makes no effect??

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#211]
So I'm used to monitor all my Octoprint instances from a single (Mac) computer running Chrome.

Thing is, out of EIGHT instances, only ONE is correctly showing either Octoprint standard GUI or TouchUI depending on if I load the IP of that particular instance directly on my browser or on a 8 frameset divided HTML, where that instance is correctly showing TOUCHUI instead.

The rest of instances are always in TouchUI mode, no matter if I call the Ip directly, on big screen.

All of the Pis run the same Octoprint and Octopi version, same OS, same settings, same plugins, all plugins and apt-get updates done. :????

Any clues what could be wrong here?

Thanks!

PS. Yes I have the START TOUCHUI BASED ON SCREEN RESOLUTION setting ticked :?

**Comment by bolsoncerrado** [comment]
I guess Im alone with this too...

**Comment by BillyBlaze** [comment]
Ditto to #210: I have no time on my hands to look into this due to real life situation. I have added a pending label so that the bot will ignore this.

**Comment by BillyBlaze** [comment]
Sorry for the delayed response, TouchUI does a resolution detection but also a touch detection. If the browser has the Touch API enabled it will also activate TouchUI regardless of the resolution. However if TouchUI does get activated you can disable it and TouchUI shouldn't be activated anymore (unless you clear all the browser data)

**Comment by BillyBlaze** [comment]
In addition to above comment, in context of issue #188 (which will be released in the upcoming version) you can disable TouchUI detection of resolution or touch individually.
