### ISSUE TITLE
Webcam stops functioning after LCD and/or Touch UI installation

### ISSUE THREAD

**Issue by moveslikeyoda** [BillyBlaze/OctoPrint-TouchUI#213]
Having issue on RPi3b.  I installed in this order Octopi (from Octopi provided image), then webcam, which functioned fine, then Waveshare 3.5 LCD, then Touch UI.  After installing Touch UI, I not get the webcam stream.  I have tried the troubleshooting section addresses and neither work for me.  Performed sudo apt-get update as some digging suggested to no avail
![image](https://user-images.githubusercontent.com/37554412/39553678-6e634b94-4e34-11e8-817f-74e0b08ee61d.png)

**Comment by BillyBlaze** [comment]
Sorry for the long delay, I am unable to look at this and will be looking into this as soon as I am able to.

**Comment by moveslikeyoda** [comment]
Any luck?  I will add that after further testing and toying around, the webcam stream is now only failing on the local (server) device.  The stream is good on remote Octopi Web interface logins (e.g. PC browser). Just for some additional information, I am now running Octoprint 1.3.8 Octopi 0.15 on a RPi3b+ using the Raspi Cam.

**Comment by BillyBlaze** [comment]
Thanks for reporting, I have fixed this issue in the bootloader and if you update to the latest version that this will be fixed and you can use relative paths again.

To update your bootloader follow these steps:
1. Goto your TouchUI startup folder:

   ````
   cd ~/TouchUI-autostart/
   ````

1. Update the files with git*
   ````
   git pull
   ````

1. Restart TouchUI

   ````
   sudo service touchui restart
   ````
