### ISSUE TITLE
2 Pi on 1 screen with touchui

### ISSUE THREAD

**Issue by blazze11** [BillyBlaze/OctoPrint-TouchUI#219]
Hi I would like to use one screen for two pis. Both are running octoprint and are connected to seperate printers. Pi 1 has the screen attached, Pi 2 has no screen.
Is it possible to add a button or something to switch between them?

**Comment by BillyBlaze** [comment]
Hi @blazze11,

Sorry for the delayed response, I am currently working on a new release and I am going over all the issues.

Technically this is possible, changing the bootloader with multiple iframes that load each printer can be done, However it would require alot of work to get this done; especially to make this configurable without breaking the update mechanism. I also don't have the time for this feature, but I am open for accepting pull-requests or when there is more interest in this feature from the community.

**Comment by spronkets** [comment]
Related: https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/322

Similar issue, I'd like to be able to navigate to different ports on the same pi within the booted Touch UI.

**Comment by rogodra** [comment]
Hello, I would also be interested in this option.

**Comment by manuman94** [comment]
Me too!

**Comment by Prizmagnetic** [comment]
Wouldn't this be better if it were implemented inside of octoprint so it would work for both normal web and TouchUI?

**Comment by willsam2k12** [comment]
Has there been any progress with regards to this request. is there a way to add an additional tab to the touch ui chromium so that it opens 2 tabs within the service for 2 different ports?
