### ISSUE TITLE
show another plugin inside side bar

### ISSUE THREAD

**Issue by devildant** [BillyBlaze/OctoPrint-TouchUI#220]
Hello,

i dev a plugin and a would like to add this plugin inside touch ui web view.
this plugin add an acordion inside the side bar, it's work perfactly with basic view but it does not appear with touch ui.
how fix that ?

best regards

**Comment by BillyBlaze** [comment]
Hi @devildant,

This is not possible (yet), there is already another issue that addresses this issue: #196 

I will close this and you could follow the other PBI for updates, as I will address this in the upcoming release.

**Comment by devildant** [comment]
hello,

 thx for your reply, finally i found a temporary solution with js code inside my plugin (with css)
:)
i will change my code when this feature will be implement.
ps : good plugin, good jobs :)
