### ISSUE TITLE
OctoPi 1.3.9rc1 Release Candidate

### ISSUE THREAD

**Issue by tibmeister** [BillyBlaze/OctoPrint-TouchUI#221]
So I went ahead and upgraded my OctoPrint to this version, which has a new Tornado version, and now TouchUI is "broke".  Here's what I've been able to glean from the developer console of Chrome when starting TouchUI not in kiosk mode.  Maybe it's helpful???
I'm running on a rPI Model 3 b+ with Raspian Stretch.

![screen shot 2018-06-23 at 12 18 59 am](https://user-images.githubusercontent.com/8305833/41815238-74d45e18-772a-11e8-8654-96eace8e2d13.png)
![screen shot 2018-06-23 at 12 19 28 am](https://user-images.githubusercontent.com/8305833/41815239-7565038c-772a-11e8-8613-330045f129a8.png)

**Comment by tibmeister** [comment]
So the workaround I am using is changing the chrome args from

`CHROME_ARGS="   --no-first-run --kiosk $TOUCHUI_ARGS $TOUCHUI_DEBUG
                --dns-prefetch-disable --disable-sync-preferences --disk-cache-size=1048576
                --disable-java --disable-plugins --disable-extensions --disable-infobars
                --user-agent='TouchUI (X11, Chrome $CHROME_VERSION) (P:$PORT)'
                --start-maximized --window-position=0,0
                $(dirname "$0")/load-screen/startup.html"`

to

`CHROME_ARGS="   --no-first-run --kiosk #$TOUCHUI_ARGS $TOUCHUI_DEBUG
                --dns-prefetch-disable --disable-sync-preferences --disk-cache-size=1048576
                --disable-java --disable-plugins --disable-extensions --disable-infobars
                --user-agent='TouchUI (X11, Chrome $CHROME_VERSION) (P:$PORT)'
                --start-maximized --window-position=0,0
                $(dirname "$0")/load-screen/startup.html"`

Seems to work for now.

**Comment by acrespog** [comment]
@tibmeister what have you changed in CHROME_ARGS? 
I didn't see any diference.

Thanks.

**Comment by tibmeister** [comment]
#$TOUCHUI_ARGS $TOUCHUI_DEBUG

Commented these two items out after —kiosk

**Comment by acrespog** [comment]
Thanks! I have checked ten times without success.

**Comment by macv36** [comment]
Hi,
After updating OctoPrint to Version 1.3.9, got RSOD (Red Screen of Dead)
I tried:
#$TOUCHUI_ARGS $TOUCHUI_DEBUG
but this stops TouchUI from loading on the Pi. I can manage Octoprint from PC, but I like to also have the advantage of not having to go back to the PC if I can change something directly on the Pi.
I hope a solution is on the works soon.

**Comment by dwcrall** [comment]
I loaded TouchUI this morning, and it was working fine.  I tried to take the update and I it hangs at "Loading TouchUI".  It appears to be the same problem discussed in this thread.  Is there a way to roll back the rev?  Is there a special place to get the fixed version?

**Comment by BillyBlaze** [comment]
You can uninstall TouchUI and install it again with the following URL: https://github.com/BillyBlaze/OctoPrint-TouchUI/archive/maintenance.zip

That should fix it.

**Comment by macv36** [comment]
I can confirm the update fixed my issue. Thanks!

**Comment by rhys100** [comment]
fixed for me! cheers. Might be good to push this out now, as i did a brand new setup today and wasted 45 mins trying to work out why it wouldnt load :D

**Comment by jraydoran** [comment]
Working for me too. Thank you for your effort. Appreciated.

**Comment by otherguy** [comment]
Fixed it for me too! Thank you for the effort, @BillyBlaze!

**Comment by jamskate** [comment]
Yep, Fixed it for me too..  Thank you!!!!

**Comment by maganzi** [comment]
Hey, can someone explain to me how to download and install the maintenance zip archive to my raspberry?

**Comment by tigrrr** [comment]
Just download the file and install it with Octoprint Plugin manager.

@BillyBlaze, I've installed the TouchUI maintenance version, but I still get the RSOD.

**Comment by maganzi** [comment]
Thank you Tigrrr!
My HDMI Display runs perfectly but TouchUI doesn´t start automatically... i tried so much =/ i think the new build is the problem

**Comment by jraydoran** [comment]
Although it initially worked for me. It stopped working after I updated to the latest bootloader.

**Comment by maganzi** [comment]
Which is the way to autostart this build of TouchUI?

**Comment by BillyBlaze** [comment]
@tigrrr, @jraydoran
Thanks for reporting, could you provide me a list of plugins installed?

@maganzi 
It sounds like you have other issues then what is reporting in this issue, please create a new issue for help.

**Comment by tigrrr** [comment]
hi, here's my plugin list: 
Action Command Prompt Support  
Action Commands (0.1)
Announcement Plugin  
Bed Leveling Wizard (0.1.6)
Core Wizard  
CuraEngine (<= 15.04)  
Discovery  
Emergency Stop Button (0.1.2)
Fullscreen Plugin (0.0.4)
Logging  
Octolapse (0.3.1)
OctoPi Support Plugin  
Plugin Manager  
Printer Safety Check  
Slicer (1.4.0)
Software Update  
Touchtest Plugin (0.1.1)
TouchUI (0.3.12)
Virtual Printer  

I'm gonna retry a fresh install next week with TouchUI only and report.

**Comment by eboston** [comment]
Instead of doing a fresh install, try disabling all the other plug-ins 
first.  See if that has any effect.

**Comment by BillyBlaze** [comment]
@tigrrr,
Thanks for the list, I was able to reproduce your issue with "Bed Leveling Wizard (0.1.6)" enabled.

@jraydoran,
Do you have this plugin installed too?

**Comment by jraydoran** [comment]
Hi,

Here is my list of plugins. I do not have this plugin installed.

Action Command Prompt Support
Announcement Plugin
AstroPrint (1.1.0)
Core Wizard
CuraEngine (<= 15.04)
Discovery
Emergency Stop Button (0.1.2)
Logging
MQTT (0.7.1)
MQTT Publish (0.5.0)
Octolapse (0.3.1)
OctoPi Support Plugin
Plugin Manager
PolarCloud (1.6)
Printer Safety Check
Pushover (0.2.1)
Software Update
Tasmota-MQTT (0.3.1)
TouchUI (0.3.12)
Virtual Printer

Thanks for the effort!

Kind Regards

**Comment by BillyBlaze** [comment]
@jraydoran 

Thanks for reporting, I cannot reproduce your issue at the moment, could you install the latest maintenance branch, update the bootloader and create a new issue with the error that is being shown in the bootloader?

**Comment by jraydoran** [comment]
Will do, Thank you!

**Comment by BillyBlaze** [comment]
@jraydoran any updates? I want to release but I like to resolve your issue too before releasing.

**Comment by jraydoran** [comment]
Updated bootloader and installed latest maintenance release.
Disabled all plugins and still getting “Connecting to TouchUI” with a counter to the left that counts to 30 and then fails.

**Comment by maganzi** [comment]
> Updated bootloader and installed latest maintenance release.
> Disabled all plugins and still getting “Connecting to TouchUI” with a counter to the left that counts to 30 and then fails.

me2

**Comment by BillyBlaze** [comment]
Thanks for the info, can you provide me your octoprint.log?

**Comment by jraydoran** [comment]
Thanks for your effort.

See attached

[octoprint.log](https://github.com/BillyBlaze/OctoPrint-TouchUI/files/2375186/octoprint.log)

**Comment by BillyBlaze** [comment]
Thanks, can you [update the bootloader](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Update-your-bootloader) to the latest version? I have added an extra check that should detect if port 80 is open.

**Comment by jraydoran** [comment]
@BillyBlaze, I did update with the same results.

**Comment by BillyBlaze** [comment]
@jraydoran Thanks for the feedback, can we continue this in #239 ?

**Comment by BillyBlaze** [comment]
Thanks all, this has been fixed in the released 0.3.12 version

Please remove any workarounds from your bootloader to prevent issues in the future.
