### ISSUE TITLE
UI Page for Enclosure plugin?

### ISSUE THREAD

**Issue by Ch3fk0ch88** [BillyBlaze/OctoPrint-TouchUI#224]
Hello,
is it possible to add a Page for the enclosure plugin?
To control the Fans and the temperature .

Greetings

**Comment by dikodahan** [comment]
+1 for that!

**Comment by BillyBlaze** [comment]
Thanks for your feature request. I am unfamiliar with that plugin, anyhow, why doesn't the plugin itself have these control functions? and why would we add that only to TouchUI and not to the plugin itself?
