### ISSUE TITLE
OctoPi only boots into console

### ISSUE THREAD

**Issue by ngoldack** [BillyBlaze/OctoPrint-TouchUI#227]
Hello,

OctoPi just boots into console. I'm using the original 7" touch screen of the raspberry.

Greetings,
Raiv3n

**Comment by qpens** [comment]
Hi,

Same thing. I'm using stable 1.3.9  Octoprint

**Comment by BillyBlaze** [comment]
Hi @Raiv3n ,

Sorry for the delayed response. Could you perhaps share the contents of `/var/log/Xorg.0.log`?
