### ISSUE TITLE
TouchUI not loading on smaller devices when webcamera is connected

### ISSUE THREAD

**Issue by ghost** [BillyBlaze/OctoPrint-TouchUI#229]
The touchui won't load on smaller devices when a webcam is connected, the logs indicated that my webcam is detected as a keyboard, is this the reason? Also, how can I fix it?

**Comment by BillyBlaze** [comment]
Hi @MachineNOR,

If you're using an unmodified version of the TouchUI bootloader, then it should always activate TouchUI on that device regardless of the attached devices. TouchUI will set the UI-agent string to "TouchUI" which will then always enable it.

However, perhaps Chromium is no longer setting this through the command line, could you perhaps share some more information about your Chrome version, TouchUI version and OctoPrint version so I can try to reproduce your issue.
