### ISSUE TITLE
Can't login with TouchUI

### ISSUE THREAD

**Issue by dikodahan** [BillyBlaze/OctoPrint-TouchUI#230]
running the latest OctoPi with OctoPrint and the latest TouchUI, however, I am not able to login. From the menu icon other components respond, it is just the login the accept the "click" just not doing anything.

**Comment by amoose136** [comment]
I noticed the same thing. Toggling “touchscreen mode” seems to sometimes make it work as a temporary work around.

**Comment by thethinkingman** [comment]
I have the same issue after installing 1.3.9 and 0.15 from scratch and doing an install of the plugins.
I deactivate TouchUI and then can login using the desktop interface. Then I switch back.
I am using an iPhone 6s.
I have tried it on my girlfriends iPhone 8 and it doesn't work on that either.

**Comment by frioSC** [comment]
Same thing here.  Clicking login in TouchUI simply does nothing.  The work around @amoose136 mentions worked for me.

**Comment by dikodahan** [comment]
Seems like this is not a one off and obviously not a minor issue. Can we please share an update on status to getting this fixed?

**Comment by BillyBlaze** [comment]
Thanks all for the feedback. Could anybody perhaps install the maintenance branch to see if this issue still persists with the latest fixes?

You can uninstall TouchUI and install it with the following URL: https://github.com/BillyBlaze/OctoPrint-TouchUI/archive/maintenance.zip

**Comment by dikodahan** [comment]
I can confirm that with the new maintenance release login worked with no issues.
Thank you!

**Comment by BillyBlaze** [comment]
Awesome, thanks for the confirmation!

**Comment by mcecchi** [comment]
Manteinance release worked ok for me too. When do you plan merging in master or backporting?

**Comment by BillyBlaze** [comment]
Thank you! Very soon. I am waiting for feedback on the last open issue.

**Comment by BillyBlaze** [comment]
I am assuming this has been resolved, please create a new issue when the issue is coming back.
