### ISSUE TITLE
Temperature-Graph too small on 7" Touchdisplay on 90° Rotated

### ISSUE THREAD

**Issue by ghost** [BillyBlaze/OctoPrint-TouchUI#231]
Hello,

can I made the Temp-Graph bigger? The Problem is that it is very small on a Display what is Horizontal, when the Display rotate to vertical it is good. So what can I do that the Temp-Graph would be bigger. Sry for the bad english ^^

Greetings Dominik

**Comment by CTcartesian3D** [comment]
Does it look like this...

![picture 009](https://user-images.githubusercontent.com/42018748/43962031-18d64580-9ca6-11e8-9448-81aa12c26a97.JPG)

**Comment by ghost** [comment]
Yes ist looks like your Screenshot, Wehen you turn the screen 90 degrees to right of left it is also smaler like your picture, i can make a foto when i am at home

**Comment by ghost** [comment]
Here you see how it looks on my Settings https://www.dropbox.com/s/4lm6mln4k7c7vou/IMG_1456.JPG?dl=0

**Comment by CTcartesian3D** [comment]
Yep, same issue I've been having...

Take a look at this thread on octoprint.org

[TouchUI Temperature-graph Squished ~ Modify size](https://discourse.octoprint.org/t/touchui-temperature-graph-squished-modify-size/3014/49)

And this #226

**Comment by BillyBlaze** [comment]
Thanks for the request. I will address this issue in the upcoming release!

**Comment by BillyBlaze** [comment]
This has been released in 0.3.12
