### ISSUE TITLE
Control interface not showing

### ISSUE THREAD

**Issue by MisterFoxi** [BillyBlaze/OctoPrint-TouchUI#232]
Hi,
I just installed Touchui using a 3.5 adafruit display on a Pi 3. All works except the control tab (3rd from left) display nothing at all. 

Is there some kind of config to add ?

Thanks

Laurent

**Comment by BillyBlaze** [comment]
Hi @MisterFoxi 

Are you logged in as an user? If you're not logged in it will not display anything.

**Comment by MisterFoxi** [comment]
That's the issue. The login area shows partially on the 3.5 screen and there is no way to scroll that part. If you try to scroll, it closes the login UI automatically.

**Comment by BillyBlaze** [comment]
It should not close while scrolling.

You can uninstall TouchUI and install it again with the following URL: https://github.com/BillyBlaze/OctoPrint-TouchUI/archive/maintenance.zip

I think that should fix it, if not, please provide me a list of installed plugins so I can try to reproduce your issue.
