### ISSUE TITLE
Touch UI will not start

### ISSUE THREAD

**Issue by cobra281** [BillyBlaze/OctoPrint-TouchUI#233]
I followed the directions to the letter at https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(Jessie-Full)

The Pi will boot to a CLI

When entering sudo xinit ~/TouchUI-autostart/chromium.xinit to try to manually start TouchUI I get the follwing error:

xterm: No absolute path found for shell: ~/TouchUI-autostart/chromium.xinit
xinit: connection to X server lost

Ideas

**Comment by BillyBlaze** [comment]
Hi @cobra281,

What happens if you try `sudo xinit /home/pi/TouchUI-autostart/chromium.xinit` ?

**Comment by ricardohalfeld** [comment]
I had the same issue just now. 

> Hi @cobra281,
> 
> What happens if you try `sudo xinit /home/pi/TouchUI-autostart/chromium.xinit` ?

Does the trick, although my different hostname likely caused it to not find the page.

**Comment by ricardohalfeld** [comment]
I noticed some of the scripts assume pi as the user, and I created another before trying the whole TouchUI thing. Maybe the key is introducing the variable $USER in the scripts.
