### ISSUE TITLE
Remove external links from UI

### ISSUE THREAD

**Issue by ncot-tech** [BillyBlaze/OctoPrint-TouchUI#236]
Is it possible to remove all links that point to external sites from the Touch UI?

While trying to log into my printer I just accidentally tapped on "Forgot password?" and it took me to the Octoprint FAQ, but now I have no way to get back to the Touch UI because there's no "back" button visible in the browser.

**Comment by BillyBlaze** [comment]
Hi @pikuorguk 

Thanks for your request, I'm reluctant to remove links, but I will add a confirmation popup when navigating away from TouchUI when touchscreen mode is enabled. This way you can cancel it from happening again.
