### ISSUE TITLE
Calibration Error

### ISSUE THREAD

**Issue by eboston** [BillyBlaze/OctoPrint-TouchUI#237]
Following the directions for calibration here...
https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#calibration

Step 2 is to run _curl -sLS https://apt.adafruit.com/add | sudo bash_ but it seems the web site is no longer available.

**Comment by BillyBlaze** [comment]
Just skip that step, seems like xinput-calibration is listed on the default repository of Stretch.

**Comment by eboston** [comment]
Okay.  Skipped the step and was able to run the calibration. However, it 
seems things have changed since the directions were created.  The file 
listed to edit in step 8 does not exist, nor does the directory.  Should 
the directory be created?

And just a minor thing, but step 6 says after completing step 6. I think 
that was suppose to be completing step 5.

**Comment by BillyBlaze** [comment]
1. Use `/etc/X11/xorg.conf.d/` instead of `/etc/X11/xorg.conf.d/`
    (/etc/X11/xorg.conf.d/ isn't generated anymore by default)

2. Yeah your right, feel free to edit the public wiki!

**Comment by eboston** [comment]
Use the directory that isn't generated anymore by default?  :) You have 
the same directory in all 3 references.

**Comment by BillyBlaze** [comment]
Ouchy, copy-paste mistake. LOL!

I meant use `/usr/share/X11/xorg.conf.d/` instead of `/etc/X11/xorg.conf.d/`

**Comment by eboston** [comment]
Thanks for the help.  Got through the process.  I also updated the wiki 
with this new information.  Thanks again for all the work with this.

**Comment by BillyBlaze** [comment]
Your welcome and thank you for the wiki edits!
