### ISSUE TITLE
Doesn´t autostart on LCD 7Inch HDMI Display

### ISSUE THREAD

**Issue by maganzi** [BillyBlaze/OctoPrint-TouchUI#238]
Hello,
thanks for your support!

Raspberry Pi 3 Model B
7 Inch 800x480 LCD Display HDMI (B)

i tried everything to autostart TouchUI on this Display but... every time after booting i´am logged in as pi@octopi in CLI. 

1) Clean installation octoprint (2018-06-27-raspbian-stretch) on SD
2) install the 7 Inch Display (https://github.com/goodtft/LCD-show)
3) install TouchUI with Plugin Manager (i also tried OctoPrint-TouchUI-maintenance.zip)
4) install Boot-to-browser OctoPi-Mehtode (https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup)

what i am doing wrong? Can you help me please?

Greetings

**Comment by BillyBlaze** [comment]
Hi @maganzi,

Your welcome, can you share your log found in "/var/log/xorg.0.log"

**Comment by maganzi** [comment]
Hi @BillyBlaze 
thank you, i don´t know but this file is empty
![bildschirmfoto 2018-09-12 um 14 02 46](https://user-images.githubusercontent.com/10503526/45423765-8e15ab80-b694-11e8-8f31-cde8f64c97b8.png)

**Comment by BillyBlaze** [comment]
Hmm, yeah, it's empty or the file didn't exist.

What happens if you try this?
1. stop touchui `sudo service touchui stop`
1. run `sudo xinit ~/TouchUI-autostart/chromium.xinit`
1. post output here

**Comment by maganzi** [comment]
X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.26-v7+ armv7l Raspbian
Current Operating System: Linux octopi 4.9.70-v7+ #1068 SMP Mon Dec 18 22:12:55 GMT 2017 armv7l
Kernel command line: 8250.nr_uarts=1 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
Build Date: 11 November 2016  11:59:59AM
xorg-server 2:1.18.4-2+rpi1 (https://www.debian.org/support) 
Current version of pixman: 0.33.3
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Wed Sep 12 12:20:35 2018
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error

**Comment by BillyBlaze** [comment]
1. Are you sure your SD card is expanded?
1. What is your current config? `sudo cat /usr/share/X11/xorg.conf.d/99-fbdev.conf`

**Comment by maganzi** [comment]
1. i expand the filesystem with sudo raspi-config
2.
Section "Device"
  Identifier "touchscreen"
  Driver "fbdev"
  Option "fbdev" "/dev/fb1"
EndSection
<img width="553" alt="bildschirmfoto 2018-09-12 um 14 31 49" src="https://user-images.githubusercontent.com/10503526/45425082-a4256b00-b698-11e8-9af3-5094188fedba.png">

2. it doesn´t match with my settings

**Comment by maganzi** [comment]
<img width="952" alt="bildschirmfoto 2018-09-12 um 14 29 54" src="https://user-images.githubusercontent.com/10503526/45425173-e77fd980-b698-11e8-93ac-901fe68b48c6.png">

"/var/log/Xorg.0.log"

**Comment by BillyBlaze** [comment]
Ok, you're using the wrong config.

Change
`Option "fbdev" "/dev/fb1"`
into
`Option "fbdev" "/dev/fb0"`

**Comment by maganzi** [comment]
It work!! THANK YOU so much!

**Comment by BillyBlaze** [comment]
Your welcome! Enjoy!
