### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mcmurray** [BillyBlaze/OctoPrint-TouchUI#24]
---

```
IndexSizeError: DOM Exception 1: Index or size was negative, or greater than the allowed value.
http://octopi.local/static/webassets/packed_app.js?06f93b82 @ 11178
```

**Comment by BillyBlaze** [comment]
Thanks for reporting! Sadly this isn't a bug I can fix, as it is not TouchUI related. Sorry for inconvenience I will remove these notifications in the next release.
