### ISSUE TITLE
Printer Head Movement Issues after upgrading to Maintenance release referenced in Issue #223

### ISSUE THREAD

**Issue by leitenky** [BillyBlaze/OctoPrint-TouchUI#241]
After installing the Maintenance release zip file in issue #223 the printer head moves extremely slow. If i Disable the TouchUI plugin, in the plugin manager the issue goes away. Please note I am also using the GPX plugin (not sure if there is a conflict between the two plugins)

**Comment by leitenky** [comment]
Just figured I would provide an update that i tired turning touchui back on and experienced the same issue again. Turning the touchui plugin off fixed the issue. Is anyone else experiencing this issue?

**Comment by BillyBlaze** [comment]
Hi @leitenky,

I suspect that your CPU is too high for your RaspberryPi which results into your problem, the GPX plugin as described "replacing g-code to talk to s3g/x3g machines" would require the CPU to translate every g-code instruction. Could you also tell what type of Pi you're using?

**Comment by leitenky** [comment]
Hi sorry for the late response I was away for a bit. I have a Pi3. I never had any issues previously. Ever since the last octopi build update ive had nothing but issues. First I could not get the touch UI to boot and now with your fix I can get it to boot but movement of the head is extremely slow. If there is any other information I can provide please let me know.

**Comment by leitenky** [comment]
Ok one last update.  Somehow debug logging was enabled, once I disabled this all my issues went away!  Thanks for the support but looks like we can close this issue.

Thanks again
