### ISSUE TITLE
Something in 99-calibration.conf stop starting TouchUI

### ISSUE THREAD

**Issue by maganzi** [BillyBlaze/OctoPrint-TouchUI#244]
Hello,
i have found an issue.
My 3.5 LCD Display is inverted at one axis.
I tired the troubleshooting (https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#inverted-touch-yx-axis)
and insert this 
```
Section "InputClass"
	Identifier	"calibration"
	MatchProduct	"ADS7846 Touchscreen"
	Option	"MinX"	"3595"
	Option	"MaxX"	"61667"
	Option	"MinY"	"63675"
	Option	"MaxY"	"4011"
	Option	"SwapXY"	"1" # unless it was already set to 1
	Option	"InvertX"	"0"  # unless it was already set
	Option	"InvertY"	"0"  # unless it was already set
EndSection
```

into (sudo nano /usr/share/X11/xorg.conf.d/99-calibration.conf)
After a reboot. I´am on this screen. TouchUI won´t start anymore. If i remove all of this code out of the 99-calibration.conf TouchUI will start again.

Thank you for your help!
Greetings

**Comment by BillyBlaze** [comment]
HI @maganzi,

Could you perhaps share your log found under `/var/log/Xorg.0.log`
