### ISSUE TITLE
Possible to have the boot into chromium browser without the touchui interface?

### ISSUE THREAD

**Issue by bluemeane** [BillyBlaze/OctoPrint-TouchUI#247]
I have set this up and it is amazing!!! However I am running a 7: screen, and would prefer a way to switch back and forth from the touchui to the normal octoprint web interface. However when I toggle that setting in the settings, it reboots the Pi. 

Is this not possible?

**Comment by BillyBlaze** [comment]
Hi @bluemeane,

Sadly this is not possible with the fancy bootloader, The bootloader needs to be 'told' that the interface is loaded.

However you could edit `~/TouchUI-autostart/chromium.xinit` and change on line 83 `http://localhost:$TOUCHUI_PORT/startup.html` into `http://localhost:$PORT`

This will directly load OctoPrint, and then you're able to switch back and forwards!
