### ISSUE TITLE
TouchUI not booting

### ISSUE THREAD

**Issue by Nickk888SAMP** [BillyBlaze/OctoPrint-TouchUI#251]
Hello! 

I've bought a 3.5" TFT display and is working fine after i installed the drivers. The screen shows the command prompt, after installing TouchUI and installing it with the official install guide from BillyBlaze, it's showing `octopi login: _ `( "_" is blinking), it's blinking for about 5-10 seconds, after that, it's going to a kinda new line as it would try to boot into something, but it's not booting, i've tried to use the 
`xinit /home/pi/OctoPrint-TouchUI-autostart/start_chromium.xinit` command, and i've got this result:

[Pastebin Code](https://pastebin.com/88BXXXxU)

[Image](https://i.imgur.com/4n8804w.jpg)

I should metion that i've tried to switch `/dev/fb0` to `/dev/fb1` and back, both are not "working", command `ls /dev | grep fb` shows that there is fb0 and fb1 present.

I've updated and upgraded my Pi to the latest versions, but TouchUI's not booting.

What could be the issue?

I'm using Raspberry Pi 3 B+

Regards.

**Comment by BillyBlaze** [comment]
Hi @Nickk888SAMP,

I noticed this error
````
Parse error on line 10 of section InputClass in file /etc/X11/xorg.conf.d/99-calibration.conf
The Section keyword requires a quoted string to follow it.
````

it seems like something went wrong with copy pasting, did you perhaps missed EndSection?

**Comment by Nickk888SAMP** [comment]
Well i don't know, what should the command look like?

**Comment by Nickk888SAMP** [comment]
It looks like this: [https://i.imgur.com/lPK9zLH.png](https://i.imgur.com/lPK9zLH.png)
But it looks like he's trying to use this config file: [https://i.imgur.com/xE4qolN.png](https://i.imgur.com/xE4qolN.png)

Update: I deleted everything from the config file and placed only this:
```
Section "Device"
  Identifier "touchscreen"
  Driver "fbdev"
  Option "fbdev" "/dev/fb1"
EndSection
```

It doesn't show a code error, instead it's showing a permission error. How do i fix it?
[https://i.imgur.com/E8s2Q5Y.png](https://i.imgur.com/E8s2Q5Y.png)

**Comment by Nickk888SAMP** [comment]
Update 2: So, i've got the server running somehow using this step [https://gist.github.com/alepez/6273dc5220c1c5ec5f3f126e739d58bf](https://gist.github.com/alepez/6273dc5220c1c5ec5f3f126e739d58bf)

There are no errors and it's booting, but not into OctoPrint TouchUI.
I've tried step 6 to 10, all went well, but it's not booting into TouchUI. Instead it's asking me to log-in.

[Picture](https://i.imgur.com/Amc93XT.jpg)

**Comment by BillyBlaze** [comment]
run `sudo raspi-config` and change under `Boot Options` to `boot to command line `

**Comment by Nickk888SAMP** [comment]
I've changed under "Boot Option" > "Desktop / CLI" to "Console Autologin" and it works! It's booting into TouchUI ^_^ Thank you! Now i need to calibrate the touchscreen because it's inverted strangely.

So, if it will help someone, if your input screen is inverted and you use a 3.5" screen, use this option

`xinput --set-prop 'ADS7846 Touchscreen' 'Coordinate Transformation Matrix' 0 -1 1 1 0 0 0 0 1`

inside your `calibration.sh` script.
[https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#calibration](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#calibration)

Location calibration doesn't work, it will bug the whole input, well, it doesn't work for me though. But that's fine, the input is actually pretty good even if not calibrated.

**Comment by danconsole** [comment]
Hi!

I was having this exact same issue and followed the method suggested. However, instead of logging in to TouchUI as it was supposed to, now I have [this](https://imgur.com/WZSaa22). Does anyone have any idea why?

Here's also a [pastebin](https://pastebin.com/Aj3cPSL7) after running `xinit /home/pi/OctoPrint-TouchUI-autostart/start_chromium.xinit ` as suggested by Nickk888SAMP.

**Comment by BillyBlaze** [comment]
Wait, you guys are using `start_chromium.xinit`? that one is really old. How did you get that?

I would remove `/home/pi/OctoPrint-TouchUI-autostart/` folder and [install the latest](
https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(OctoPi-or-Jessie-Light)) one by redo-ing step 7 and 8

**Comment by danconsole** [comment]
I did that, but without any apparent effect. I'm gonna try formatting the sd card and starting from scratch later. Maybe that helps?

Thanks for the help anyways!

**Comment by BillyBlaze** [comment]
if you have updated it, then stop touchui `sudo service touchui stop` and run `sudo xinit ~/TouchUI-autostart/chromium.xinit` and post the output here.

**Comment by danconsole** [comment]
[Here](https://pastebin.com/S3vee0yw) it is. Honestly I have no clue what's going on

**Comment by BillyBlaze** [comment]
thanks, whats the contents of `/etc/X11/xorg.conf.d/99-calibration.conf`

**Comment by danconsole** [comment]
Not much stuff: `-bash: /etc/X11/xorg.conf.d/99-calibration.conf: Permission denied`

**Comment by BillyBlaze** [comment]
use `sudo`

**Comment by danconsole** [comment]
tried it previously, here you go: `pi@octopi:~ $ sudo /etc/X11/xorg.conf.d/99-calibration.conf
[sudo] password for pi:
sudo: /etc/X11/xorg.conf.d/99-calibration.conf: command not found
`

**Comment by BillyBlaze** [comment]
try `sudo cat /etc/X11/xorg.conf.d/99-calibration.conf`

**Comment by danconsole** [comment]
[Here](https://pastebin.com/98MvfvcG) you go.

**Comment by BillyBlaze** [comment]
It looks like the wrong double-quotation character is used in the bottom of the config:

```
Section “Device”
  Identifier “touchscreen”
  Driver “fbdev”
  Option “fbdev” “/dev/fb1”
EndSection
```

replace `“` with `"`

Also since my guide don't have this character, it might be good to inform the guide you where following to adjust this error in their guide.

**Comment by danconsole** [comment]
Good eye. Thank you so much! That solved it.
