### ISSUE TITLE
Long navigation tooltip breaks navigation menu

### ISSUE THREAD

**Issue by blazze11** [BillyBlaze/OctoPrint-TouchUI#253]
If the text of a menu is to long it will make other entries unreadable.

![screenshot_chrome_dev_20181103-114434](https://user-images.githubusercontent.com/8845639/47951265-9c7a9800-df5e-11e8-96ca-726c4ee8e365.png)

**Comment by BillyBlaze** [comment]
Thanks for reporting!

**Comment by BillyBlaze** [comment]
Hi @blazze11,

Sorry for the long delay, Al-through the author of DiscordRemote already fixed this issue, I am unable to reproduce the issue again. I have confirmed that the dropdown can normally not grow bigger then the viewport.

Therefor I am closing this issue, if you however still see this issue then please let me know!
