### ISSUE TITLE
No Touch and screen timeout

### ISSUE THREAD

**Issue by matty0511** [BillyBlaze/OctoPrint-TouchUI#255]
I purchased a 7 inch touch screen (http://a.co/d/0EkDweD) my Raspberry PI.  I got the PI to auto boot into a browser but the touch screen is not working. Also, It seems like after a short period of time it goes into a black screen saver mode and being i cant touch the screen, i cant wake it up.

**Comment by BillyBlaze** [comment]
1. It sounds like a hardware or driver issue.
   - Check if USB Touch device is recognized (`lsusb`)
   - Check if touch is received (`sudo lsinput | grep -i touch -A4 -B5`)
2. You can disable the screensaver in `/etc/default/touchui` by chaning DISABLE_SCREENSAVER to true

**Comment by matty0511** [comment]
okay i found the disable screen saver part but this is waht i get when i run the touch command:
pi@octoprint:~ $ sudo lsinput | grep -i touch -A4 -B5
sudo: lsinput: command not found

**Comment by BillyBlaze** [comment]
I forgot you need evtest for this and not lsinput.

- Install it with `sudo apt-get install evtest`
- Run `evtest` and interact with your touchscreen to see if it receives the touch events
