### ISSUE TITLE
[feature request] Reboot in parameters dialog

### ISSUE THREAD

**Issue by yet-another-average-joe** [BillyBlaze/OctoPrint-TouchUI#258]
Hello,

I think that the parameters dialog (Parameters/Settings/TouchUI) should suggest a reboot for changes to be applied. Or even a "save and reboot" button.

**Comment by BillyBlaze** [comment]
Hello,

Why would it need to reboot?

**Comment by yet-another-average-joe** [comment]
Hello BillyBlaze.

Do this :

- OctoPi fresh install
- TouchUI plugin fresh install
- toggle TouchUI = ON
- enable customization
- change color

-> no change

restart OctoPrint

-> no change

restart system

-> you're done

(tested 2 installations)

Under other circumstances, colors are applied immediately.

I found some other *MINOR* glitches, still invistigating...

**Comment by BillyBlaze** [comment]
Hmm that sounds like a bug. maybe a timing issue, please let me know if you have some more information!
