### ISSUE TITLE
Error while rotating phone

### ISSUE THREAD

**Issue by mcmurray** [BillyBlaze/OctoPrint-TouchUI#26]
## On an iPhone 6s+ using safari browser.

```
IndexSizeError: DOM Exception 1: Index or size was negative, or greater than the allowed value.
http://octopi.local/static/webassets/packed_app.js?583a1d9a @ 11815
```

**Comment by BillyBlaze** [comment]
Thanks for reporting! Sadly this isn't a bug I can fix, as it is not TouchUI related. Sorry for inconvenience I will remove these notifications in the next release.
