### ISSUE TITLE
Temperature tab buttons reorganization

### ISSUE THREAD

**Issue by yet-another-average-joe** [BillyBlaze/OctoPrint-TouchUI#261]
Hello,

there is a problem with the buttons positionning in the temperature tab. It can be seen easily on a PC by resizing the browser. On my phone, the buttons '+' and "validation" are not usable in landscape as they are drawn one over the other, and the temperature offset fields are not displayed (720x1280)

[EDIT] also true in portrait mode

(I did'nt notice this bug with the previous version, but maybe I did'nt pay attention...)

There are no problems in other tabs, even with custom buttons (Action Command Prompt and Custom Control Editor, for Control and Terminal tabs respectively)

![touchui](https://user-images.githubusercontent.com/43514870/48962119-fe398b00-ef7b-11e8-894b-524f1616022e.PNG)

**Comment by BillyBlaze** [comment]
Hi @yet-another-average-joe,

Thanks for reporting 👍 I have reproduced the issue and fixed it, it will be released in the upcoming release.
