### ISSUE TITLE
Connecting to TouchUI failed

### ISSUE THREAD

**Issue by mhargonaut** [BillyBlaze/OctoPrint-TouchUI#262]
After the initial installation TouchUI loads into the GUI.  After a reboot the pi loads the red TouchUI logo with "Connecting to TouchUI failed"  It is attempting to access Octoprint via http://::1 before timing out.

**Comment by mhargonaut** [comment]
Should I abandon this issue and let it go stale?  Issue still remains.

**Comment by BillyBlaze** [comment]
Hi @mhargonaut 

sorry I overlooked your issue, it seems like you have the same issue as #266, which is that you cannot autoLoginAs with an IPv6 connection. Please subscribe to issue 266 so once we have the solution you can also apply that 👍
