### ISSUE TITLE
Blank Dialogie wont close

### ISSUE THREAD

**Issue by bloodygoodbloke** [BillyBlaze/OctoPrint-TouchUI#263]
I am using a Gen 2 Kindle Fire with SILK browser and although its not supported it works fine with normal Octotiprint UI however when Touch UI is enabled i get a Dialogue box up that is blank with the exception of a close button.  
The close button does not work so it wont close the dialogue.  
The Dialogue box is full width and blocks access to the Menu button so i cant even disable Touch UIO for this device. 
I have to fully disable Touch UI on octoprint to use the Kindle Fire but this disables Touch UI for all devices. 

https://www.facebook.com/photo.php?fbid=10161056093890065&set=gm.578766025895458&type=3&eid=ARBD0vbpcmDM-3iPc4qvdjlkD_wIAUAHsCFD35qRBoNnOVuq_57d0w7u9kGNqU3Rc_FOxwx_UmMFE7eZ&ifg=1

**Comment by BillyBlaze** [comment]
Hi @bloodygoodbloke 

First; I cannot see the facebook photo, you can copy-paste the image onto github (paste it while writing a comment)
Secondly; You can disable the auto-detection of TouchUI and manually activate it on the device you want to:
  - Disabling auto-detect is under 'Settings > TouchUI' and uncheck the two options
  - Enabling TouchUI can be done by clicking the mobile icon in the navigation bar and by clicking the button activate touchui

**Comment by bloodygoodbloke** [comment]
![47436238_10161056093895065_8874986065287446528_o](https://user-images.githubusercontent.com/38584064/50094696-ad7c2180-020b-11e9-9e23-677539775561.jpg)

Hi 
here is the attached photo.  

i have disabled the Autodetect and the screen is still the same as above.   
onthe tablet i cant get access to enable and disable touch UI per device as the dialogue blocks the menu

**Comment by AJ240-Aus** [comment]
I am having this same issue. I cannot close the White Window which is overlaid on the menu bar. The window has a close button that does nothing. I cannot access any functions because I cannot get to the menu bar underneath.

**Comment by AJ240-Aus** [comment]
> I am having this same issue. I cannot close the White Window which is overlaid on the menu bar. The window has a close button that does nothing. I cannot access any functions because I cannot get to the menu bar underneath.

I found the issue : ABL plugin is the cause of the White Box that will not close. I just started turning off plugins until it disappeared. Once I discovered it, I investigated further and found that there is White Text in the box but is invisible on the white background.
So the issue is not with TouchUi.

**Comment by bloodygoodbloke** [comment]
i have remobed ABL and reset Cache on the tablet for it finally to work.

Thanks everyone for your help.  You can close this issue. and not it in your readme that the ABL plugin isnt compatible if you use certain tablets.

**Comment by BillyBlaze** [comment]
Thanks for the responses, I will have a look in the next if I can disable this plugin when TouchUI is active.

**Comment by chuxxsss01** [comment]
Having the same problem on the banggood 3.5 TFT display. Could someone point me to the ABL plugin please. Not sure if I have it running. Plus auto login does not work even after ticking the auto login?

**Comment by SBachman** [comment]
I've been having the same issue, disabling the ABL plug-in worked and also gave me a work around for another more recent issue with TouchUI in desktop Chrome

**Comment by chuxxsss01** [comment]
Under setting, but open in chrome brower on laptop instead of Andriod mate.

Watch this will help you.

https://youtu.be/MEjdQw5hqOo

⁣Get BlueMail for Android ​

**Comment by chuxxsss01** [comment]
Hey,

I just signed the petition "Free Julian Assange, before it's too late. STOP
USA EXTRADITION" and wanted to see if you could help by adding your name.

Our goal is to reach 75,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/wTzzdRRbGp

Thanks!
Chris

**Comment by BillyBlaze** [comment]
Hi @chuxxsss01,

Thanks for your first comment, however please refrain from posting politics or any other off topic comments regarding this open-source project.

I however highly encourage you to have this dialog on the appropriate social platforms.

**Comment by chuxxsss01** [comment]
It was an accident sorry. Sign something, but to get to it, it asked for my gplus throught it was close now day. Didn't think of gmail sorry again.

⁣Get BlueMail for Android ​
