### ISSUE TITLE
Failed message on sudo ~/TouchUI-autostart/helpers/install command.

### ISSUE THREAD

**Issue by onur-elbirlik** [BillyBlaze/OctoPrint-TouchUI#267]
I did all instructions from other sources as well,
changed
Option "fbdev" "/dev/fb1" to fb0 etc.
nothing works. my touch ui doesnt work on my touchscreen. i only see octopi login: terminal on touchscreen. problem is same both on 1.3.8 and 1.3.10.

I also try to install touch-ui on touchscreen with instructions below with clean octopi image;

sudo apt-get install --no-install-recommends xinit xinput xserver-xorg xserver-xorg-video-fbdev x11-xserver-utils matchbox unclutter chromium-browser
 
sudo nano /usr/share/X11/xorg.conf.d/99-fbdev.conf
 
Copy & paste the following:
 
Section "Device"
  Identifier "touchscreen"
  Driver "fbdev"
  Option "fbdev" "/dev/fb1"
EndSection
 
Press CTRL+O > Enter > CTRL+X
 
Type the following into the console:
 
sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
 
If it fails, simply ignore it. It will still work.
 
git clone https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart.git ~/TouchUI-autostart/
sudo cp ~/TouchUI-autostart/touchui.init /etc/init.d/touchui
sudo chmod +x /etc/init.d/touchui
sudo cp ~/TouchUI-autostart/touchui.default /etc/default/touchui
sudo update-rc.d touchui defaults
sudo reboot

it didn't work also

**Comment by BillyBlaze** [comment]
Can you share the contents of the log file of `/var/log/xorg.0.log` (run `sudo cat /var/log/xorg.0.log` and copy paste it)
