### ISSUE TITLE
TouchUI does not show on Adafruit 3.5" PiTFT

### ISSUE THREAD

**Issue by devsfan1830** [BillyBlaze/OctoPrint-TouchUI#271]
Clean OctoPrint image. Updated to 1.3.10. Touch UI plugin installed. Ran the driver scripts from adafruit and am able to calibrate the touch screen. I get full console output on the screen. Then ran the Touch UI installer scripts. Everyting runs and report: success. The screen flickers when it finishes but its just the console text. No interface. Tried updating the bootloader but it says  its already up to date. Totally stumped. For the record this is a Pi 3B+.

**Comment by SBachman** [comment]
I'm experiencing the same issue

**Comment by Warsenius** [comment]
i hae this issue aswell. the touchscreen shows the console login prompt.

**Comment by BillyBlaze** [comment]
Hi,

Can you share the contents of the file /var/log/xorg.0.log, that should tell us a bit more.

**Comment by SBachman** [comment]
[Xorg.0.log](https://github.com/BillyBlaze/OctoPrint-TouchUI/files/2770062/Xorg.0.log)
