### ISSUE TITLE
Unable to Login at all using touchUI on 3.5" screen PI B

### ISSUE THREAD

**Issue by SandwichRising** [BillyBlaze/OctoPrint-TouchUI#272]
OctoPrint 1.3.10
TouchUI 0.3.12
octopi 0.15.1

I have competed setup of touchui on my pi, and am able to login using my credentials using a PC over the network. I have also setup the touchui to auto-load on my pi on startup. When it finishes loading it prompts me to "Please log in" even though I set it to autologin my user. My octoprint login doesn't work, it gives me an "Incorrect name or password" error, and does the same thing with my pi su login as well. However I am using the same credentials I use to login with a pc over the network and it appears to be logging in passively just fine. 

I have attempted editing my ~/.octoprint/config.yaml to the following:

`AccessControl:`
`  autologinAs: myoctopilogin`
`  autologinLocal: true`
`  localNetworks:`
`  - 127.0.0.0/8`
`  - ::1/128`
`  salt: 4zwrHYQ3BoWqDbSWYIyHIGhM29sn7jRW`
`api:`
`  key: `

But when I try to login a couple times and check the file again is has been updated to:

`AccessControl:`
`  autologinAs: myoctopilogin`
`  autologinLocal: true`
`  localNetworks:`
`  - 127.0.0.0/8`
`  - ::1/128`
`  salt: 4zwrHYQ3BoWqDbSWYIyHIGhM29sn7jRW`
`accessControl:`
`  salt: EuN40TnP6BbPn1hF2mwTtH5coHxDOdMP`
`api:`
`  key: 75D081F106BA4B2AA400140CB5D2DBEA`

So it adds the extra accessControl: line but only after I try to login, and I'm not sure why. Also, that's not my actual user api key from inside octoprint, and adding it from the used settings to that file doesn't seem to help. I am restarting both octoprint and touchui after any changes are made.

In the log it looks like I'm getting some sort of 401 POST error. My octoprint.log is [here](https://pastebin.com/GQmnUnd3) and also attached.

[octoprint.log](https://github.com/BillyBlaze/OctoPrint-TouchUI/files/2716762/octoprint.log)

**Comment by BillyBlaze** [comment]
Make sure you have the right whitespaces (2 before autoLoginAs etc, and 4 underneath `localnetworks:`). Also it's `accessControl` and not `AccessControl`

it should look something like this:

```
accessControl:
  autologinAs: myoctopilogin
  autologinLocal: true
  salt: somelonghash
  localnetworks:
    - "127.0.0.1/8"
    - "::1/128"
```

**Comment by SandwichRising** [comment]
Yeah, githubs autoformat was getting rid of my spaces. And I think because mine has "Access" instead of "access" that's probably the root of all my problems, and I'm not sure how it happened. And that's why it keeps remaking it when I try to log in. I will make the changes and try again, thanks! Ill keep you updated.

**Comment by SandwichRising** [comment]
Okay, that was the root of the problem. Now I've got it auto logging in. My touchscreen stopped working at that point, so now I have to figure out if that's hardware or software. Thank you for the help though, my original issue is resolved.

**Comment by SandwichRising** [comment]
I damaged my touchscreen hardware, but have it replaced now. All my issues are solved. Thank you for the help, BillyBlaze!

**Comment by jeor112** [comment]
Hi BillyBlaze
I have the same issue. I have tried to reinstalling a few times with the same results.
I have tried to do follow this steps and inserted this:
  localnetworks:
    - "127.0.0.1/8"
    - "::1/128"
in the config.yaml file, but there is still no autologin.

Now, the config file looks like this:

accessControl:
  autologinLocal: true
  autologinAs: " myusername "
  salt: " somelonghash "
  localnetworks:
    - "127.0.0.1/8"
    - "::1/128"
api:
  key: " It is the correct API key "
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1545132000
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1527588900

To be able to login, I will have to connect USB keyboard :-(

I hope you can help!
Thx in advance

Edit: I forgot to tell, that the virtual keyboard works when I´m in the touch GUI. And it´s only when I reboot the RPI.

Update:
I have disablet the Themeify plugin and after reboot it sems to work now.

**Comment by docb7** [comment]
Hi, I have the same issue. I did not have Themeify installed but I took the chance and deactivated all Plugins I had, but nothing helps.  My config.yaml looks good and the autologin works from a normal browser. But not via Touch UI on the octopi. Also there is no virtual keyboard and when I attach a real keyboard I always get username/password wrong. Anyone got an idea what went wrong?
Ocotpi is 1.3.10, TouchUI 0.3.12

**Comment by SandwichRising** [comment]
One of the problems I had with the pi was passwords. My pi defaults to a UK layout typically, and I have to tell it to use a US layout instead. The symbols are at different locations for both layouts which was the root of my password problems. Also, did you set the api key to match your octopi api in the config.yaml? I think it needs to be set.

**Comment by docb7** [comment]
Ha, I tried that and it might help for finding the problem. I changed my password to 123 (just for testing of course ;-) and when I use that via a real keyboard (virtual keyboard does not pop up unfortunately) the site just seems to reload. There is no "incorrect user/password" message like when I punch in a wrong password but the same login page again without any change.

**Comment by SandwichRising** [comment]
Did you add the api key from octoprint?

**Comment by docb7** [comment]
Nope, where can I do that? I have installed touch ui on the same raspi as Octopi runs on, is there still a need for putting the api key somewhere? If yes - where?

**Comment by docb7** [comment]
Nope, where can I do that? I have installed touch ui on the same raspi as Octopi runs on, is there still a need for putting the api key somewhere? If yes - where?

**Comment by docb7** [comment]
Do I need to put the Octoprint Api Key into the  config.yaml?

**Comment by SandwichRising** [comment]
I put the OctoPrint api from inside the OctoPrint interface into the config.yaml on mine before it would autologin.

**Comment by docb7** [comment]
Ah, that was done automatically somehow. The api key is in config.yaml so that is not the error.

**Comment by sbias** [comment]
try to set AUTODETECT_PORT=false in /etc/default/touchui . Don't know why (yet) ... but this solved the problem for me.

**Comment by docb7** [comment]
Real crazy, after about 10 restarts (cause I shutdown the system when not printing) the login works. I have changed nothing ;-) Really funny. Thanks for all your support!

**Comment by jglazer63** [comment]
Nothing I can do will automatically log into TouchUI.  It constantly stops for username/password.  I checked the config and the spaces are correct.  There is an API value (hopefully the correct one).  I cannot edit touchui to set AUTODETECT_PORT to false.  It's "not allowed".  Any more ideas?
