### ISSUE TITLE
Octoprint Themeify Breaks TouchUI

### ISSUE THREAD

**Issue by BennyBoyW** [BillyBlaze/OctoPrint-TouchUI#273]
I was using TouchUI very nicely but then added the Octoprint Themeify plugin. This has broken the TouchUI interface. Is there a way of having both plugins operational at the same time as each other ?

**Comment by BennyBoyW** [comment]
Is there any way of getting a response to this issue ?

**Comment by BillyBlaze** [comment]
Hi @BennyBoyW,

I'll will have a look in the next release if I can disable Themeify when TouchUI is active.

**Comment by BennyBoyW** [comment]
Hi @BillyBlaze
Thank you so much for that. 
Is it worth me changing the LESS file to try to cater for this in the meantime ?
Thanks,
Ben

**Comment by BillyBlaze** [comment]
I haven't tested this, but this should work in base.less:
```
.themeify:not(#touch) {
    ...
}
```

**Comment by BennyBoyW** [comment]
Brilliant - thank you for the assist
