### ISSUE TITLE
TouchUI Failed To Connect After Restart 

### ISSUE THREAD

**Issue by thomasdlap** [BillyBlaze/OctoPrint-TouchUI#284]
Hey Guys, 

Firstly thank you for the awesome work.

The problem i'm experiencing looks like it been reported before but it didn't manifest itself in the same way so wanted to report.

 Currently every time I boot up my raspberry pi, it'll eventually fail to connect to touch ui and service the following error

"Connectin to TouchUI Failed"

![51145003_316361032556068_7577518965342076928_n](https://user-images.githubusercontent.com/47286231/52171303-74423700-270f-11e9-8ed9-69abc761b37f.jpg)

Initially I was able to get TouchUI to auto boot on the raspberry pi without issue and all was working well. The only thing that is worth mentioning Is I had performed an update to latest OctoPi/OctoPrint, then after reboot started experiencing the above error

I went through and made sure to update the bootloader as been mentioned in https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Update-your-bootloader

Any suggestions of things to try?

Thanks In advance

Current Setup:

Raspberry Pi 3 B+
  - OctoPi: 0.15.1
  - OctoPrint: 1.3.10
  - Raspberry PI 7" Touch Screen
  - Wireless 5.0 network

Printer:
  - Prusa i3 MK3 firmware 3.5.1

**Comment by BillyBlaze** [comment]
Hi @thomasdlap 

What happens if you try this;
1. run `sudo nano /etc/default/touchui`
2. change on the bottom of the file `AUTODETECT_PORT=true` to `AUTODETECT_PORT=false`
3. save (CTR-O, enter, CTR-X)
4. run `sudo service touchui restart`

**Comment by indianmcycle** [comment]
I tried that and still failed.

**Comment by gasrovescio** [comment]
I tried everything to do the update and change to "false" but the touchui does not connect !!!!
