### ISSUE TITLE
OctoPrint-TouchUI-autostart scripts seem to miss install of libgl1-mesa-dri

### ISSUE THREAD

**Issue by derjacks** [BillyBlaze/OctoPrint-TouchUI#287]
:white_check_mark: OctoPrint-TouchUI-autostart scripts seem to miss install of libgl1-mesa-dri

**Reproduction Steps:**
1. Fresh install of 2019-01-30_2018-11-13-octopi-streatch-lite-0.16.0 on PI3
2. Run initial setup on browser interface for octoprint and install touchui plugin
3. git  https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart.git and run install

**Expected behavior:**
Installs ok and finishes

**Observed behavior:**
Doesn't get past trying to enable GL driver.  Don't think the script checks for dependency.
Workaround: Maually install libgl1-mesa-dri before running install script.  Install script finishes.

**octopi version:**0.16.0
**OctoPrint version:**1.3.10
**TouchUI version:** 0.3.12

**Installed plugins:**
1. TouchUI

**Comment by BillyBlaze** [comment]
Hi @derjacks 

Thanks for your detailed ticket! I had added the step to enable GL driver for a bugfix on WaveShare devices, but in hindsight this fix only created more problems. Therefor I will remove this step entirely and   add a section under troubleshooting for those affected by the bug how the can manually try it.

Thanks again!
