### ISSUE TITLE
Touch UI shows properly flipped but touch is not

### ISSUE THREAD

**Issue by jglazer63** [BillyBlaze/OctoPrint-TouchUI#288]
I rotated my pi screen 180 by editing /boot/config.txt and putting "display_rotate=2" in the file.  This worked great but the digitizer is still flipped so actually using it is impossible.  How do I flip the digitizer too?

**Comment by jglazer63** [comment]
Ok, issue solved (sorry) but for posterity, you should put "lcd_rotate=2" in the config.txt file.  Not "display_rotate=2".

**Comment by BillyBlaze** [comment]
Glad you were able to solve this issue on your own and that you shared the solution 👍👍👍
