### ISSUE TITLE
TouchUI progress just "freezes" sometimes...

### ISSUE THREAD

**Issue by Jaxel** [BillyBlaze/OctoPrint-TouchUI#290]
I'm using TouchUI on the official Pi 7" Touchscreen.

Sometimes the progress area of my current print just "freezes" on TouchUI. The print continues; but the progress information never updates. Because of this, I can't pause/cancel or start new prints. Octoprint still works, in that I can still control if from my phone or from my computer. I can even click on the Touchscreen and navigate all the other tabs; I just can't do anything with it, because it always thinks it's in the middle of a print.

This forces me to restart my Pi to fix this. Is there a way to fix this without restarting my Pi or interrupting a current print?

**Comment by BillyBlaze** [comment]
Sorry for the long delay and thanks for reporting the issue!

Since we have two open issues about the same issue, I propose to continue this in #281, also could you please share your `octoprint.log` in that ticket too?

(if the issue is different please feel free to continue here)
