### ISSUE TITLE
[WARNING] TouchUI and Auto Bed Leveling Expert = no more system menu

### ISSUE THREAD

**Issue by yet-another-average-joe** [BillyBlaze/OctoPrint-TouchUI#295]
Sorry, but for some reason I'm unable to subscribe to Framagit... This not a TouchUI bug, but there's some incompatibility (not found here with the search functionnality)

I attempted, 2 times, to install Auto Bed Leveling Expert plugin, on 2 different systems with TouchUI installed. The result was 2 times the same. This plugin breaks TouchUI, and only the menu bar can be accessed.

In a browser, this plugin makes TouchUI unusable. Clicking the system menu has no effect. Switching back from TouchUI to classic UI is therefore impossible.

On the touchscreen, there's an empty  dialog box. On one system the hamburger menu is still accessible, on the other it isn't, and it has to be powered off by sxitching OFF the mains. 

![Capture](https://user-images.githubusercontent.com/43514870/55743582-f5c98480-5a32-11e9-85c1-9a29fb08cbb9.PNG)

So, if you are a TouchUI user (you're most likely one if you read this... ;) ), do NOT install this plugin.

If you have an account on Framagit, please advise the author. On my side, for some reason (?????????)  I can't...

(hopefully, everytime I test a plugin, I image the system)

[EDIT] I finaly could log in Framagit...

**Comment by BillyBlaze** [comment]
Hi @yet-another-average-joe,

Thanks for reporting this issue. In the upcoming release we will disable ABL expert while TouchUI is active.
