### ISSUE TITLE
X11 doesn't seem to read the 99-calibration.conf file

### ISSUE THREAD

**Issue by SteveDallas** [BillyBlaze/OctoPrint-TouchUI#298]
I have installed TouchUI on the latest OctoPi (stretch-lite-0.16) and installed the 3.5" display drivers.  TouchUI launches correctly, and I have been able to run the calibration tool following the instructions from the troubleshooting page.  However, the X and Y axes are swapped, and if I change the state of Option "SwapXY" and reboot, horizontal stylus movement still moves the cursor vertically and vice versa.

Contents of my /usr/share/X11/xorg.conf.d/99-calibration.conf:
Section "InputClass"
        Identifier      "calibration"
        MatchProduct    "ADS7846 Touchscreen"
        Option  "MinX"  "22425"
        Option  "MaxX"  "22152"
        Option  "MinY"  "49237"
        Option  "MaxY"  "50192"
        Option  "SwapXY"        "1" # unless it was already set to 1
        Option  "InvertX"       "0"  # unless it was already set
        Option  "InvertY"       "0"  # unless it was already set
EndSection

**Comment by BillyBlaze** [comment]
Try moving the file to this directory instead: `/etc/X11/xorg.conf.d/`

**Comment by SteveDallas** [comment]
I tried that, too.  It didn't seem to work there, either.

**Comment by BillyBlaze** [comment]
Have you tried setting `Option "InvertY" "true"` too?

**Comment by BillyBlaze** [comment]
see https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/54

**Comment by SteveDallas** [comment]
I got things working by doing a complete reinstall and using Waveshare's LCD-show repository (https://github.com/waveshare/LCD-show) to install the driver, rather than https://github.com/goodtft/LCD-show

When reinstalling TouchUI on the stretch lite based Octopi 0.16.0, I found that the configuration files for X11 were in /usr/share/X11/xorg.conf.d/ rather than /etc/X11/xorg.conf.d/, so when I got the "boot to black screen" issue, I had to adjust my procedure from your troubleshooting instructions to set the fbdev to fb0.

Everything is working now and I can install the rest of my plugins.
