### ISSUE TITLE
Run TouchUI on a second Pi that isn't running OctoPrint itself

### ISSUE THREAD

**Issue by MikeThomas123456** [BillyBlaze/OctoPrint-TouchUI#301]
I'm looking for instructions to setup TouchUI on a second Pi with a TFT. I have one Pi running OctoPrint and connected to the printer. It has the TouchUI plugin installed and it works well when accessign from smart phone. I have a second Pi with a 3.5" TFT and a full Raspbian install that I want to use for running the Touch UI console.

Hoping someone has a guide on how to configure the TouchUI install on the second Pi to look at the first Pi instead of itself.

**Comment by BillyBlaze** [comment]
Hi, 

From the top of my mind, the following should work:

1. Clone touchui autostart on your 2nd PI:
   ```git clone https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart.git ~/TouchUI-autostart/```

2. Run install helper with force mode on the 2nd PI:
    ```sudo ~/TouchUI-autostart/helpers/install --force```

3. Edit TouchUI-autostart/bootloader/script.js:
   ```nano ~/TouchUI-autostart/bootloader/script.js```

4. Change `var prefix = (port == "80") ? url + "/" : url + ":"+port+"/";` into `var prefix = "http://my-1st-pi-ip-address";`

5. Change `http://my-1st-pi-ip-address` above to the IP of your 1st Pi that runs OctoPrint.

6. Save and Exit (ctr-o, enter, ctr-x)

6. Add the ip of your 2nd PI to your 1st PI octoprint.config under the localNetworks ([read more](https://docs.octoprint.org/en/master/configuration/config_yaml.html#access-control))

7. Restart both devices
