### ISSUE TITLE
Font set to incorrect value, screen seems blank

### ISSUE THREAD

**Issue by Jeff-Haas** [BillyBlaze/OctoPrint-TouchUI#311]
Please see the screenshot - the yellow star is from the Print Time Genius plugin.  Otherwise the info seems to be blank.

![TouchUI bug](https://user-images.githubusercontent.com/27331078/61016652-3ba12c00-a345-11e9-8fdf-6347d61ca303.png)

However if I highlight the text you can see it's there:

![TouchUI bug highlight](https://user-images.githubusercontent.com/27331078/61016708-773bf600-a345-11e9-8c88-9115b6b812ec.png)

**Comment by Jeff-Haas** [comment]
This is running on a Google Pixel 2, with the current version of Android Chrome.  Disabling Print Time Genius makes no difference - you just don't see the little yellow star!

**Comment by Jeff-Haas** [comment]
I was able to figure out how to change the font color so that it shows up for me, but it seems that the default is incorrect for the current Android Chrome browser.

**Comment by celogeek** [comment]
To fix this I create a small less file:

```less
#printer {
    .accordion {
        &-inner {
            color: @main-background;
        }
    }
}
```

So I can add it to customization, use local file (copy it to your raspberry).

Now I got this:

<img width="380" alt="Capture d’écran 2020-01-05 à 00 31 13" src="https://user-images.githubusercontent.com/65178/71772837-c0ff4500-2f52-11ea-9f50-356f9d58206c.png">
