### ISSUE TITLE
Toggled to Touch UI - can't toggle back

### ISSUE THREAD

**Issue by Jan07576** [BillyBlaze/OctoPrint-TouchUI#312]
After switching view to Touch UI once it seems impossible to toggle back to regular. Also some buttons seem incomplete; I can not access the settings anymore.
![Stupid_TouchUI_Bug](https://user-images.githubusercontent.com/52888739/61185832-e4a99880-a65d-11e9-8cfe-699f11467530.JPG)

**Comment by freddotu** [comment]
As a newbie to TouchUI, I was not aware there was a feature to permit toggling. Is this a screen touch location or otherwise?

**Comment by Jan07576** [comment]
After installing I noticed that it won´t go to Touch UI mode on my mobile phone - so I activated "Toggle Touch UI" in the user settings. Still no effect. When I noticed a smartphone - icon in my regular web-surfece i was able to activate Touch UI manually. Now there does not seen to be a way back.

**Comment by Jan07576** [comment]
Does anyone know how to access the settings by adress-line (soemthing like http://192.168.178.63/**#control**)  there has to be a way to remove this messy plugin even with the button missing.

**Comment by BillyBlaze** [comment]
Hi @Jan07576,

Thanks for reporting. There seems to be a javascript error. Is there a way you can share your browser log?

**Comment by BillyBlaze** [comment]
Hi @freddotu,

You can toggle TouchUI in the [TouchUI user-settings](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Configuration#user-settings) modal and should open if you click the 'mobile' icon,

**Comment by freddotu** [comment]
My ignorance may be getting in the way. I installed from an image downloaded from the Octoprint web site. During the configuration, I selected to automatically start Octoprint and TouchUI plug in was added shortly after that.

I have version 1.3.11, although the github page shows 0.3.11 as the current version.

The Pi is connected to the printer and the Pi also has the touchscreen interface. It's a healthy 7" screen. I've been wanting on occasion to exit the interface, to exit Octoprint to get to a linux terminal screen at the very least but not sure how to accomplish that and then how to return to Octoprint/TouchUI.

![touchUIsettings](https://user-images.githubusercontent.com/29874039/61187780-ccc51b00-a643-11e9-971f-339bb4a7798c.JPG)

I don't have the toggle suggested in the link provided, nor some of the other references in that link.

Am I heading in the wrong direction?

**Comment by BillyBlaze** [comment]
No, your not heading in the wrong direction. This option is disabled on touchscreen devices that use the bootloader.

**Comment by freddotu** [comment]
Is there a method to exit to a terminal (linux) and restart later, using the touchscreen?

**Comment by JSViterise** [comment]
hey @BillyBlaze I am having these same difficulties. touch UI interface on all my devices, touch screen, web browser and mobile phone with no printer detection, or option to toggle back to regular octoprint. octoprint is completely unresponsive. I have no idea what to do from here?

**Comment by Jan07576** [comment]
Sorry, I was not able to retrieve a log from my browser, also I gave up and installed Octoprint from scratch, this time without TouchUI.

**Comment by klinkenberg** [comment]
Hallo,
I have the same problem, how to reach X or a terminal temporarly from touchUI (fullscreen boot) ?

**Comment by daniel11krupa** [comment]
erase cookies from to your browser

**Comment by klinkenberg** [comment]
How to erase cookies if I can not get a teminal? (and no keyboard at hand ....)

**Comment by galosre** [comment]
Sorry to reopen this,but when I toggle Touch UI no way I can go back to normal view,  my  only option is to delete octoprint cookies
So where you are in touch UI where is the icon to toggle?
