### ISSUE TITLE
Inverted x/y touch screen issues

### ISSUE THREAD

**Issue by Yacobeeb** [BillyBlaze/OctoPrint-TouchUI#315]
Any help would be most appreciated! could not find any other info on this.

I am trying to get my touch screen to work (Adafruit PiTFT - 2.8" Touchscreen Display for Raspberry Pi) with TouchUI but the x and y-axis are inverted. I have followed through the calibration steps [here](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#calibration-touch-location) and I tried to follow these steps [here](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#inverted-touch-yx-axis) but I do have the file listed in this step in my directory. I have tried to change the text in the file from the calibration steps but that does not change anything. 
thanks in advance.
best, Jacob

**Comment by juacuell** [comment]
I am having same issue
