### ISSUE TITLE
TouchUI Broken

### ISSUE THREAD

**Issue by juacuell** [BillyBlaze/OctoPrint-TouchUI#318]
TouchUI on Pi 3b broken after updating to latest octoprint. When I disabled that plugin the Pi will show desktop version fine. Have tried reinstalling desktop environment and still no luck

**Comment by Kuenstler79** [comment]
I have the same problem.

**Comment by chrschn** [comment]
Same here, TouchUI on OctoPrint v1.3.11 loads on my phone but no controls are available after login. The connections dialog is empty. File list, temperature, and control windows are mostly empty.
![connections](https://user-images.githubusercontent.com/2598629/63209931-a03f6b80-c0e7-11e9-95e4-6b759e25ede7.png)
![controls](https://user-images.githubusercontent.com/2598629/63209932-a3d2f280-c0e7-11e9-9cef-0c3a7412255a.png)
![file_list](https://user-images.githubusercontent.com/2598629/63209933-a6cde300-c0e7-11e9-83e1-712b02b2d003.png)

**Comment by BillyBlaze** [comment]
Thanks for reporting, can you provide me a list of plugins? If you're running Shutdown Printer Plugin, then there is already fix (see #302) on the maintenance branch.

**Comment by chrschn** [comment]
Thanks for the fast response. I can confirm that I have the Shutdown Printer plugin installed. I disabled it and upon restart of OctoPrint, the TouchUI works again. Thanks for the pointer, I'm looking forward for the fix in the next release.

Also, thanks for creating TouchUI! It works really well and makes it so easy to navigate OctoPrint on my phone. I love it!

**Comment by Kuenstler79** [comment]
Thank You for the hint! That worked for me too.
