### ISSUE TITLE
Disable virtual keyboard in Touch UI

### ISSUE THREAD

**Issue by ghost** [BillyBlaze/OctoPrint-TouchUI#323]
Hello everyone, 

I wanted to ask if it is possible to disable virtual keyboard in Touch UI like disabling some features in octopi in config.yaml?

Thanks for answer in advance!

**Comment by BillyBlaze** [comment]
Hi @malinka91,

You can disable the virtual keyboard in the TouchUI [user settings](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Configuration#user-settings)

**Comment by ghost** [comment]
@BillyBlaze thank you very much!
