### ISSUE TITLE
First input when screen blanking is active is not ignored

### ISSUE THREAD

**Issue by smiler** [BillyBlaze/OctoPrint-TouchUI#330]
When screen blanking is active (screen is blank) and you touch somewhere on the display to disable it that input is not ignored and can hence cause all kind of annoyances depending on which screen that is currently active.

I do realize this is standard Xorg blanking behavior but I don't know of any good workaround other than disable blanking completely which I don't want.

**Comment by BillyBlaze** [comment]
Thanks for reporting, I have no solution to be honest, if there is any I would love to hear it too.
