### ISSUE TITLE
Glitch with a new option in OctoPrint 1.3.12

### ISSUE THREAD

**Issue by yet-another-average-joe** [BillyBlaze/OctoPrint-TouchUI#338]
Hi,

I just installed OctoPrint 1.3.12. It came with a great option I asked for a while ago on OctoPrint Git : "Close dialogs by clicking outside" can be deactivated. Deactivating this feature makes use of TouchUI on inaccurate touchsreens much easier.

see here : https://github.com/foosel/OctoPrint/issues/3162

But in some circumstances, TouchUI does not like it.

Steps to reproduce :

- update OctoPrint to 1.3.12
- in Settings/Appearence, uncheck "Close dialogs by clicking outside"
- open "Settings" in the main menu, the dialog box opens quite slowly... Click anywhere while it is not 100% displayed, and before clicking the menu: the edit field "Additional serial ports" will be over the menu, and can't be used.
- workaround : be carefull not to click anywhere until the Settings dialog is displayed !

The UI updates slowly (RaspBerry pi 3B+ is not an Intel I9 with the last high end GPU !). The user could think the touch event was not received, and click a second time -> glitch !

I don't know if it's a TouchUI issue, or an OctoPrint one. When "Close dialogs by clicking outside" is deactivated, and the screen is touched/clicked outside, there's a visual effect that could explain the problem (OctoPrint shakes the dialog horizontally).

In VNC :

![Capture2](https://user-images.githubusercontent.com/43514870/67762838-9f5f7a00-fa46-11e9-9ac7-0441244fcd43.PNG)

In a browser :

![Capture3](https://user-images.githubusercontent.com/43514870/67763145-4c39f700-fa47-11e9-8e32-e6f4af6efc36.PNG)

If you'd prefer, I could open an issue on OctoPrint Git...

**Comment by BillyBlaze** [comment]
Sorry for the long delay and thanks for reporting! I'll have a look at this in the next release.

**Comment by BillyBlaze** [comment]
Thanks for the detailed report. I was easily able to identify the issue! This will be fixed in the upcoming release.
