### ISSUE TITLE
Move distance increments missing when disabling extruder

### ISSUE THREAD

**Issue by jhenley01** [BillyBlaze/OctoPrint-TouchUI#341]
Hello. I'm using OctoPrint for my CNC router therefore no extruder or heated bed is used. When I disable the extruder and heated bed the temperature tab and extruder options are no longer visible under control as expected but the move distance increments (0.1/1/10/100) also disappear in TouchUI. I verified that they do show in the normal UI so and also did a clean install to rule out an issue with my installation. This was tested on Chrome and Safari mobile and Chrome desktop.

I've attached some screenshots, hopefully someone can help with this issue. 

![Screenshot_20191118-224334_Chrome](https://user-images.githubusercontent.com/56179818/69123385-dbdf2e00-0a66-11ea-8f98-716be888c03e.jpg)
![Screenshot_20191119-002705_Chrome](https://user-images.githubusercontent.com/56179818/69123394-e3063c00-0a66-11ea-96fe-3c30d0c9e63a.jpg)
![Screen Shot 2019-11-19 at 12 28 55 AM](https://user-images.githubusercontent.com/56179818/69123414-eb5e7700-0a66-11ea-90c9-87706f58320d.png)

**Comment by BillyBlaze** [comment]
Sorry for the long delay, I'll have a look at this in the next release.
