### ISSUE TITLE
TouchUI Fails install

### ISSUE THREAD

**Issue by sthgardner** [BillyBlaze/OctoPrint-TouchUI#342]
get this during install.

Running apt-get update (this will take a while)
Do NOT switch off the Pi or close this console until done!
 - success

Installing dependencies (xinit xinput xserver-xorg xserver-xorg-video-fbdev x11-xserver-utils matchbox unclutter chromium-browser):
 - failed
pi@octopi:~ $

**Comment by macaba** [comment]
I just had this issue myself.

After you've attempted the install, and it has failed, then run:
` sudo apt --fix-broken install`
then run the install again.

**Comment by sthgardner** [comment]
Thank you. I will try this after work.
