### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by Doncuppjr** [BillyBlaze/OctoPrint-TouchUI#347]
Would be cool, this is my last problem child before dropping python2 support from my project.

**Comment by BillyBlaze** [comment]
Sorry for the long delay, I'll have a look at this in the upcoming release!

**Comment by TheMrCaveman** [comment]
This seems to be needed to get the screen working on 1.4.0

**Comment by BillyBlaze** [comment]
Since python support was dropped, this needs to be fixed a.s.a.p. 

Please follow #368 for updates

**Comment by BillyBlaze** [comment]
Re-opened since #368 is a different issue

**Comment by BillyBlaze** [comment]
Support for python3 has landed; it's now available on the maintenance branch.

Could you check it out?
