### ISSUE TITLE
Layers not reporting in TouchUI to screen

### ISSUE THREAD

**Issue by samd12** [BillyBlaze/OctoPrint-TouchUI#348]
When using a plugin that reports back layer percentage in the dashboard it is not reporting the correct data to the touch interface.  What you are seeing in the browser is correct but not the same as on the touch screen.  Only the layer percent data.  Every thing else works perfectly.  See attached photo.  Yellow is computer and info is correct, red in the touch screen which does not move.  These photos were seconds apart
![touchui01](https://user-images.githubusercontent.com/4117470/71648402-cef26300-2cd1-11ea-9a04-502b8a0e83d8.jpg)
![touchui02](https://user-images.githubusercontent.com/4117470/71648404-d31e8080-2cd1-11ea-8fda-127856331d88.jpg)

**Comment by samd12** [comment]
Guessing the project is on hold for a while?

**Comment by BillyBlaze** [comment]
Sorry for the long delay, what plugin are you using?

**Comment by BillyBlaze** [comment]
After investigating this issue; I found out that the 'Dashboard' plugins requires the GCodeViewer to be active to get the data. However for performance issues the GCodeViewer is disabled in 'touchscreen mode'. If you really want to see this data, then go to your TouchUI settings and disable Touchscreen mode.
