### ISSUE TITLE
OctoPrint 1.3.12 and TouchUI

### ISSUE THREAD

**Issue by Frank-Ov** [BillyBlaze/OctoPrint-TouchUI#349]
Hallo

i have a little problem with installing the touchUI installer helper:
I get the error msg "expand your file system before running this helper"

i use a usb-stick instead of a sd-card ....

is there a workaround ?

Thanks :-)

**Comment by BillyBlaze** [comment]
Edit `~/TouchUI-autostart/helpers/install-steps/1-check-mounted-sd` and remove the contents of the file. That way it should not exit the helper
