### ISSUE TITLE
No data updating on touch screen, Displaylayer error, fresh install

### ISSUE THREAD

**Issue by samd12** [BillyBlaze/OctoPrint-TouchUI#350]
I am completely updated on the Pi and in octopi.   Fresh install done today of everything.  I see my gauges and fields but there is no data.  I am also getting a message that "Cant get stats from DisplayLayerProgress"  Is it installed.  The plugin is installed.  I have even tried uninstalling/reinstalling with now luck.  I could not find a debug mode in the plugin please let me know what info you need
![up1](https://user-images.githubusercontent.com/4117470/71775343-41bb4280-2f4d-11ea-81a3-bd3be657c71c.jpg)
![up2](https://user-images.githubusercontent.com/4117470/71775344-41bb4280-2f4d-11ea-9f49-88e6d46c2b98.jpg)

**Comment by samd12** [comment]
Guessing this project is dead??

**Comment by BillyBlaze** [comment]
Sorry for the long delay and thanks for reporting, Whats the name of the plugin?

**Comment by samd12** [comment]
I have resolved everything except the layer does not update on the pi.  It just stays pinned at 0% even though on the computer it updates properly.  Dashboard and DisplayZ are the the plugins
![IMG_0818](https://user-images.githubusercontent.com/4117470/73602761-b54d7100-4546-11ea-9d54-b3289f5461ed.jpg)

**Comment by BillyBlaze** [comment]
Great you fixed the data issue. Therefor I am closing this in favor of the other issue #348
