### ISSUE TITLE
Webcam icon not showing up in portrait mode

### ISSUE THREAD

**Issue by Mesmer88** [BillyBlaze/OctoPrint-TouchUI#353]
Webcam quick access button is not showing up in portrait mode. It appears in landscape.
I'm using a Samsung Galaxy Note 10 Plus phone to check Octoprint.

I see other users are having the same issue (not sure what they use to browse)

https://www.reddit.com/r/octoprint/comments/eha86s/how_to_get_webcam_quick_select_on_touch_ui_plugin/

https://imgur.com/a/EB2tMH7

![XVwYAw8](https://user-images.githubusercontent.com/39758319/72225941-fa0f6900-3593-11ea-90c2-4dc20cb0eea5.jpg)

**Comment by Mesmer88** [comment]
UP for the bot.

**Comment by BillyBlaze** [comment]
I think the icon with the padding just barely - doesn't - fit. The missing icon should be visible in the menu, or isn't this the case?

**Comment by pebsi** [comment]
I get something similar. I have a different layout so for me it is the gcode viwer, consol and stop objects, which don't actually appear in the list or at the top of the screen in portrait mode and just controls don't appear in either.
I am using the addin themify, does this interfere with touch UI maybe? the themify snippet is below as well.
layout in website.
website view:
![image](https://user-images.githubusercontent.com/58213697/75194576-ad08e000-5758-11ea-89af-6bd0eec35786.png)

landscape mode
![image](https://user-images.githubusercontent.com/58213697/75194549-a2e6e180-5758-11ea-9d3a-9d75ade20495.png)
portrait mode
![image](https://user-images.githubusercontent.com/58213697/75194618-c1e57380-5758-11ea-9595-78a45a190681.png)

themify
![image](https://user-images.githubusercontent.com/58213697/75194705-f0fbe500-5758-11ea-98ee-dd5be17a104a.png)
