### ISSUE TITLE
change Autologin Username for TouchUi

### ISSUE THREAD

**Issue by Hostile17** [BillyBlaze/OctoPrint-TouchUI#354]
hello.

i had to re install TouchUI today as i had a corrupted SC card.
i accidentally used the wrong user name for the auto login for the touchUI and now cant find a way to change it. i have tried deleting the install of touhui and that didnt work, as the re install said "skipping setup" login as pi already setup.

can someone please tell me i dont have to format the SD card and start again ?

PS, im relatively new to Raspberry PI.

thanks.

**Comment by BillyBlaze** [comment]
The autoLogin username is located in the octoprint config. Read more about that here: https://docs.octoprint.org/en/master/configuration/config_yaml.html
