### ISSUE TITLE
TouchUI stops working when Shutdown Printer Plugin is active

### ISSUE THREAD

**Issue by Varming73** [BillyBlaze/OctoPrint-TouchUI#356]
I can see that issue #302 is closed but being on TouchUI: 0.3.13, OctoPrint: 1.3.12 and Shutdown Printer (1.0.8) and the problem is still there.

**Comment by BillyBlaze** [comment]
This bugfix has not been released in the official channels, but you can install the dev version that includes this bugfix. See #302 for how.

**Comment by Varming73** [comment]
I can confirm installation with https://github.com/BillyBlaze/OctoPrint-TouchUI/archive/maintenance.zip fixed the problem here too.
