### ISSUE TITLE
"[::1] Refused to connect" screen after upgrade to  OctoPrint 1.4.0rc4 

### ISSUE THREAD

**Issue by NightSkySK** [BillyBlaze/OctoPrint-TouchUI#362]
![IMG_20200204_074118](https://user-images.githubusercontent.com/52137446/73720490-57758080-4722-11ea-9383-7a98cc28d0db.jpg)
After upgrade to OctoPrint 1.4.0rc4 TouchUI no longer boot up correctly. At previouse version of Octoprint everything was working correctly including autologin

~/.octoprint/config.yaml
`
accessControl:
    autologinAs: szymon
    autologinLocal: true
    localNetworks:
    - 127.0.0.1/8
    - ::1/128
`

**Comment by jajo42** [comment]
I had the same problem with RC3 and could not fix it. I rolled back to stable version and all is working fine again. Would like to test and use RC4 but i also need a working display. Looking forward to a fix.
