### ISSUE TITLE
touchui and octoprint 1.4 not working

### ISSUE THREAD

**Issue by TheMrCaveman** [BillyBlaze/OctoPrint-TouchUI#365]
I am currently testing octoprint in our farm and would like to use 1.4 betas on some devices but ran into the problem that touchui is not working anymore on 1.4 only works on 1.3 versions.

**Comment by Cadair** [comment]
👍

**Comment by jansenchua** [comment]
I just upgraded to 1.4 and it's not working too... Just a white screen with error "refused to connect"

**Comment by smokerjoe** [comment]
Same here. upgraded to 1.4 and it's not working too... Just a white screen with error "refused to connect"
Fortunately, I had a backup :-)

**Comment by revjkramer** [comment]
Same here just updated to 1.4 final today.

**Comment by okdesuka63** [comment]
Same here and no backup :-(
Just revert to an older version, e.g. 1.3.12

`~/oprint/bin/pip install https://github.com/foosel/OctoPrint/archive/1.3.12.zip`
`sudo service octoprint restart`

[https://community.octoprint.org/t/how-can-i-revert-to-an-older-version-of-the-octoprint-installation-on-my-octopi-image/205](url)

**Comment by TheNore** [comment]
here is the screen everyone is receiving (me included) on final 1.40 octoprint
![IMG_20200304_112201](https://user-images.githubusercontent.com/16988567/75914765-54ee6f80-5e23-11ea-8e68-1e5dbce483a8.jpg)

**Comment by roelleke** [comment]
After today upgrade to 1.4 I have the same problem.

**Comment by floridaservices** [comment]
I'm not sure I would have ever seen this issue beforehand as it's only touchui that's affected, but I had to do the version reversion trick detailed by okdesuka63 (thanks!) to get my touchscreen back as well.  Easiest way is to SSH in, can't do it from the GUI and it's a pain to do it from the touch screen terminal.

**Comment by diablex2** [comment]
Same problem here, 
After upgraded to 1.4.0 Touch UI is not loading.
Any solutions?

**Comment by rogodra** [comment]
Same problem after upgrading to 1.4.0.
![IMG_20200305_124809_](https://user-images.githubusercontent.com/26087556/75979308-7e210580-5ee0-11ea-9547-263a8a3ad8dc.jpg)

Edit temporal solution: https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/368#issuecomment-595036339

nano TouchUI-autostart/chromium.xinit

change and comment:

http://localhost:80/"
#http://localhost:$TOUCHUI_PORT/"

sudo service touchui restart

**Comment by BillyBlaze** [comment]
Thanks for reporting. I'll have a look at this as soon as possible. Closing this duplicated issue, please follow #368

**Comment by cappy0815** [comment]
Hi,

got the same problem since upgrading to 1.4

> nano TouchUI-autostart/chromium.xinit
> 
> change and comment:
> 
> http://localhost:80/"
> #http://localhost:$TOUCHUI_PORT/"
> 
> sudo service touchui restart

I have no lines like this or any symilar entries ...
Wondering why!?

Cappy

**Comment by BillyBlaze** [comment]
Don't do this. To fix your issue follow this step instead: https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/368#issuecomment-595679383

**Comment by cappy0815** [comment]
Hi,
I checked your recommended feed.
First steps did not work ...

Finally I was working on the same lines as here in this thread.
I changed values to ...:80 and it is working.

Cappy
