### ISSUE TITLE
Navigation Bar Scaling 

### ISSUE THREAD

**Issue by buzkill420** [BillyBlaze/OctoPrint-TouchUI#367]
Dear Billy! I am having the issue where anytime i restart TouchUI or OctoPrint, the Tab Navigation Bar resizes much longer then the screen and i am unable to select the Settings tab, as its defaulted to the far right.
It is fine on a fresh boot of the RasPi and makes extra addons shrink away into the settings tab but heaven forbid i install a plug in and i have to reboot Octoprint, I'm currently forced to reboot the whole Pi.....
 Anything we can do to force scaling or to reduce the size of the Navigation bar icons?

**Comment by BillyBlaze** [comment]
Thanks for reporting. I have identified the issue and this will be fixed in the upcoming release.
