### ISSUE TITLE
OctoPrint 1.4.0 Touch UI refused to connect.

### ISSUE THREAD

**Issue by Testmangh** [BillyBlaze/OctoPrint-TouchUI#369]
After updating to OctoPrint 1.4.0 the touch UI TFT display boots to a white screen with the error message: "[::1] refused to connect". Is there something that I can do to fix it or should I go back to the older version of octoprint?

Thanks.

**Comment by Testmangh** [comment]
I reverted back to "1.3.12 (stable)" now it works again =(

**Comment by TheNore** [comment]
i used this workaround and it was temporarily fixed

https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/368#issuecomment-595036339

**Comment by BillyBlaze** [comment]
Thanks for reporting. I'll have a look at this as soon as possible. Closing this duplicated issue, please follow #368
