### ISSUE TITLE
Please add support for multiple webcams

### ISSUE THREAD

**Issue by timur-tabi** [BillyBlaze/OctoPrint-TouchUI#371]
The MultiCam plugin provides support for multiple cameras on the Control page.
![Screen Shot 2020-03-08 at 1 50 41 PM](https://user-images.githubusercontent.com/1065860/76169206-e4f22900-6143-11ea-8f1a-d1604e004e9d.png)
However, TouchUI only lets me see the primary webcam.

**Comment by BillyBlaze** [comment]
Thanks for reporting. I'll have a look into it! Sadly it wont be in the upcoming release since I am wrapping that one up.

**Comment by buzkill420** [comment]
can confirm this is happening to more then 1 person. thanks for looking into it Billy!
