### ISSUE TITLE
Newest update to Octoprint, terminal missing on mobile

### ISSUE THREAD

**Issue by 3DEnthusiast** [BillyBlaze/OctoPrint-TouchUI#373]
As the title says, after the recent Octoprint update, the terminal option on my phone has disappeared. It's there on desktop but not under touchui.

**Comment by BillyBlaze** [comment]
Thanks for reporting.

**Comment by 3DEnthusiast** [comment]
What's the fix for this? I see a lot of code in the linked "fix" but no instructions.

**Comment by BillyBlaze** [comment]
You can update to the latest version 0.3.14 to get this fix

**Comment by 3DEnthusiast** [comment]
Thanks! It wasn't showing up at the time but now it has.
