### ISSUE TITLE
Newest update on OctoPrint - Progress bar is gone?

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#374]
Ditto, progress bar while printing seems gone!?

**Comment by TheNore** [comment]
I have noticed this as well on both of my octopi installs

**Comment by BillyBlaze** [comment]
Thanks for reporting, it's already fixed and will be released soon.

**Comment by bolsoncerrado** [comment]
I updated...

Is it me or it still does NOT show up?

Also, the REFRESH TOUCHUI button is gone too?

**Comment by TheNore** [comment]
I had to fully uninstall and reinstall the plugin in the repository

**Comment by alive-corpse** [comment]
I have this issue too on both of my octiprint hosts.

**Comment by TheNore** [comment]
did you fully update the bootloader and the 1.40 of the plugin and backend from a git pull?
