### ISSUE TITLE
Disable link preview when hover over a icon

### ISSUE THREAD

**Issue by maganzi** [BillyBlaze/OctoPrint-TouchUI#378]
I have installed a completely new Raspberry for my second 3D printer and this one always shows the link when clicking / hovering over an icon / link and you have to click more often to change the tab.

How can I deactivate this?

![IMG_8299](https://user-images.githubusercontent.com/10503526/76660871-381c0f80-657a-11ea-8b3a-b22ad8e9d765.JPG)

**Comment by maganzi** [comment]
problem still exists

**Comment by maganzi** [comment]
problem still exists

**Comment by BillyBlaze** [comment]
Thanks for reporting. TouchUI already strips this information. Maybe there is a third party plugin that puts it back. Do you have a list of plugins for me so I can reproduce the issue?
