### ISSUE TITLE
Raspberry Pi Touch Display 7 Inch Issue

### ISSUE THREAD

**Issue by dcavallero** [BillyBlaze/OctoPrint-TouchUI#382]
Hi, in the last TouchUI (0.3.14) I cannot change the feed rate speed because the interface cannot show the textbox to change the value.
Other issue is that when I stop the job or shutdown the service, the warning message window is bery large and I cannot press the OK button, because this is not appear in the screen. 

Regards.
Daniel.
![image](https://user-images.githubusercontent.com/6058726/77176712-3f27ae00-6aa3-11ea-9d82-7c0d63db5a0d.png)

![image](https://user-images.githubusercontent.com/6058726/77176723-43ec6200-6aa3-11ea-8073-07522c53dbf7.png)

![image](https://user-images.githubusercontent.com/6058726/77176744-48b11600-6aa3-11ea-905e-514e53fc2e35.png)

**Comment by yet-another-average-joe** [comment]
52 pi display ?

Is your display a capacitive multitouch one ?
If yes, pinch to reduce.
Better disable this feature with TouchUI :

sudo nano /etc/default/touchui

then add :

TOUCHUI_ARGS="--disable-pinch"

But it could be something else...

[EDIT]

I was currently reinstalling OctoPi + TouchUI, and had a look to GitHub...

TOUCHUI_ARGS="--disable-pinch"

does not work anymore...
I open a bug report : #385
