### ISSUE TITLE
New version of numberkeyboard is broken

### ISSUE THREAD

**Issue by kazolar** [BillyBlaze/OctoPrint-TouchUI#386]
Has a weird -> next to backspace, makes it very difficult to press backspace
![Arrows](https://user-images.githubusercontent.com/37454332/77803252-0f544980-7053-11ea-81bd-d302a08f3ee2.PNG)

**Comment by klsc18** [comment]
same here. I can not delete anything with the x-button, only changing temperature with up and down in textfield works. this issue is only after update to the new version.

**Comment by kazolar** [comment]
I found the code and deleted the arrow keys in the JavaScript library, and that worked. I don't know how to fix it so I can reinstall the plug-in

**Comment by PietsHost** [comment]
> 
> 
> I found the code and deleted the arrow keys in the JavaScript library, and that worked. I don't know how to fix it so I can reinstall the plug-in

Could you specify where to find the code and what piece of code did you delete?

**Comment by CCSnell** [comment]
Would definitely like to know also, having the same issue. I'm running in portrait mode, not sure if it makes a difference, just thought I'd mention.

**Comment by lciscon** [comment]
I have encountered the same issue.

**Comment by lciscon** [comment]
I believe it is an issue with the definition of the number keyboard in keyboard.js.  I *think* it should not have the {left}  and {right} keys in the second row.  I'm trying to figure out how to remove those from an active install and try it:

```
		number: {
			display: {
				'bksp'   :  ' ',
				'a'      :  'Save',
				'c'      :  'Cancel'
			},

			layout: 'custom',
			customLayout: {
				'default' : [
					'{bksp} 1 2 3 4 5 6 7 ',
					'{accept} {c} {left} {right} 8 9 0 - , . '
				]
			},
		}
```

**Comment by lciscon** [comment]
I've confirmed that by changing this row:

```
'{accept} {c} {left} {right} 8 9 0 - , . '
```

to this:

```
'{accept} {c} 8 9 0 - , . '
```

it fixes the issue.

**Comment by BillyBlaze** [comment]
Thanks all for reporting. This issue has been fixed on the maintenance branch and will be released soon.
