### ISSUE TITLE
Any option to add custom css?

### ISSUE THREAD

**Issue by CodeBrauer** [BillyBlaze/OctoPrint-TouchUI#393]
I optimized the view to my 3.5 inch screen, so all necessary information is visible without scrolling.

How can I add the style sheet, without losing it on upgrading the plugin?

Before | After
--- | ---
![Bildschirmfoto 2020-04-06 um 16 23 36](https://user-images.githubusercontent.com/2059754/78568871-09185700-7823-11ea-9f2e-efcea54e413b.png) | ![Bildschirmfoto 2020-04-06 um 16 23 29](https://user-images.githubusercontent.com/2059754/78568889-0ddd0b00-7823-11ea-885a-262e2cef37f2.png)

Additional CSS: https://gist.github.com/CodeBrauer/b95da1bb5e527e306523534a981b2f65

**Edit**

Just found: https://github.com/cryptk/OctoPrint_CustomCSS
It works when I use `!important` on any property. Just looked through the code and looks ok, but I'm not the python expert.

**Comment by BillyBlaze** [comment]
Hi @CodeBrauer,

You can import your own LESS file instead of CSS. Documentation (sort of) is [here](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Customize:-Use-your-own-file) and in the TouchUI settings you can link it to the file on your local system
