### ISSUE TITLE
strange screen after boot up like permision denied

### ISSUE THREAD

**Issue by freezeghost** [BillyBlaze/OctoPrint-TouchUI#396]
Hello I just have strange screen like permision denied solved in #368 
This screen is showed after aprox 1 min after start up. If I restart service it will show again :-(
![IMG_20200323_094533](https://user-images.githubusercontent.com/61758699/79264874-8aac5c80-7e95-11ea-8dcf-a63e657eeeda.jpg)

**Comment by freezeghost** [comment]
I try to solve this issue. And it is not related with TouchUI but with chromium browser. I try install latest version of chromium on other rpi and after same time (always 57 sec, strange :-) ) is same issue.
Has some one same issue?

**Comment by freezeghost** [comment]
trouble disappear when cleared chromium`s cache with "rm -rf ~/.cache/chromium"

**Comment by TheNore** [comment]
thanks for this, happened to me too - would a simple update help as well?
