### ISSUE TITLE
- failed

### ISSUE THREAD

**Issue by kknopp01** [BillyBlaze/OctoPrint-TouchUI#398]
Followed directions, got to the part where you install the helpers:

"sudo ~/TouchUI-autostart/helpers/install"

and the TOUCHUI install helper runs.  It starts to install dependencies and then this happens:

"Installing dependencies (xinit xinput xserver-xorg xserver-xorg-video-fbdev x11-xserver-utils matchbox unclutter chromium-browser):
 - failed"

**Comment by Charlemagne65** [comment]
I have the exact same issue. please help

**Comment by kknopp01** [comment]
So this issue will not be addressed and no fix implemented?  Is this software no longer being supported?

**Comment by BillyBlaze** [comment]
Try #316 #333 for the solution.
