### ISSUE TITLE
Bed Temp can't be set & Pre-Heat Plugin doesn't work

### ISSUE THREAD

**Issue by PietsHost** [BillyBlaze/OctoPrint-TouchUI#400]
Hi there!

At first I want to mention, that the Bed Temperature cannot be set.. The Keyboard shows up, marks all digits within the Temp field and doesn't allow to delete them (backspace Icon).. if you enter a new value, it's just being added to the actual temperature, so if you want to go from 90 to 85 degrees, and type in "85" it's actually "8590" degrees..

Screenshot attached. 
![Screenshot_6](https://user-images.githubusercontent.com/3725416/80287917-979e3b00-8734-11ea-848d-644bf56f68e8.png)

![Screenshot_7](https://user-images.githubusercontent.com/3725416/80287970-eb108900-8734-11ea-893e-d9173d756f95.png)

Second, I'm using the "Preheat Button"-Plugin to preheat the heatbed/hotend to the first-layer temperature.. unfortunately that "preheat button" doesn't show up with TouchUI.

best regards,

Patrick

**Comment by BillyBlaze** [comment]
Thanks all for reporting. 

First:
This issue has been fixed on the maintenance branch and will be released soon.

Second:
Sadly this is something I cannot fix. The Preheat button plugin is trying to access an element that has been moved by TouchUI. The only way this could be fixed is in the Preheat button's codebase.
