### ISSUE TITLE
[feature request] Add scaling buttons

### ISSUE THREAD

**Issue by SimonTil** [BillyBlaze/OctoPrint-TouchUI#415]
Currently, I'm running a 3.5" display with a 800x480 resolution.
Because this is a high resolution for this display size, and TouchUI detects the resolution instead of the size, the buttons are very small.
I am also not able to calibrate the touch input, so, clicking the small buttons is very hard.
An option to set a different UI scaling would be helpful.
This could be realized by for example a button with scalings (125%, 100%, 75%, etc.) in the TouchUI option menu.
Note that I'm still very happy with your awesome work!

I'm using a custom build RaspiOS with touchscreen configured (I'm not experienced with that stuff) and the latest version of OctoPrint.

**Comment by BillyBlaze** [comment]
You can do that already by changing the 'font-size' in the OctoPrint Settings > Plugins > TouchUI. This also acts like scaling.

If the Extra-Large option is still to small then you can add your [custom styling](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Customize:-Use-your-own-file) and set the `@main-font-size` variable to even a larger value.
