### ISSUE TITLE
How do uninstall boot to browser?

### ISSUE THREAD

**Issue by mattbarb** [BillyBlaze/OctoPrint-TouchUI#416]
I've managed to install TouchUI on boot with use of a touch screen which is great, but how do I remove it as wanted to test out Octodash too? I've looked everywhere but cant locate any instructions Many thanks Matt

**Comment by BillyBlaze** [comment]
run `sudo ~/TouchUI-autostart/uninstall`

**Comment by mattbarb** [comment]
Thanks!
