### ISSUE TITLE
800*480 LCD touch Display "Are you sure?" I don't see the button.

### ISSUE THREAD

**Issue by bougs93** [BillyBlaze/OctoPrint-TouchUI#429]
5 Inch 800*480 LCD touch display is used.

in touchUI
"Are you sure?" I don't see the Cancel and OK buttons everywhere.

It is below the display screen and cannot be touched.

I don't see the button.
All "Are you sure?" You cannot touch the screen.

  Are you sure?
[Cancel] [Proceed]

Are you sure?
[No, continune the print] [Yes, cancel the print]

![5inch 800x480 error](https://user-images.githubusercontent.com/45992773/92542092-d0255800-f282-11ea-83f5-d90ca64378ee.png)

**Comment by BillyBlaze** [comment]
Thanks for reporting; closing this issue because there is already an open issue @ #418
