### ISSUE TITLE
error with touchUI helpers install for booting to browser

### ISSUE THREAD

**Issue by armon4** [BillyBlaze/OctoPrint-TouchUI#435]
when I try to do the final step for booting to browser I keep getting this error.

![Desktop Screenshot 2020 09 20 - 20 51 11 78](https://user-images.githubusercontent.com/71623037/93733615-ed173080-fb8a-11ea-8f15-33982a6e710a.png)

**Comment by Will-wastelander** [comment]
> when I try to do the final step for booting to browser I keep getting this error.
> 
> ![Desktop Screenshot 2020 09 20 - 20 51 11 78](https://user-images.githubusercontent.com/71623037/93733615-ed173080-fb8a-11ea-8f15-33982a6e710a.png)

What happens if you run apt upgrade manually ?

**Comment by AP4130** [comment]
What version of Octopi are you running? I got the same error with 0.18.0rc1; got a little further by installing the Desktop environment, but still failed in the end.  I fixed the problem by reverting back to Octopi 0.17.0.
