### ISSUE TITLE
Browser error

### ISSUE THREAD

**Issue by JeedHome44** [BillyBlaze/OctoPrint-TouchUI#443]
Hello,

Sorry, I'm french. So I translated with Google translate:

I just installed a 7 inch screen on my Raspberry Pi 3B.
I followed this tutorial to install TouchUI normally:

http://egamaker.be/octoprint-5-plugin-touchui/

I have the TouchUI loading screen which is displayed on the 7 inch screen with "Connecting to TouchUI" but it makes an "browsers's error console" then, then the red TouchUI screen "Startup failed...".

I see at the bottom of the blue loading page the following link: "Connecting to http://[::1]/
I think the problem is there but I don't know how to solve it.

I specify that TouchUI works correctly on Chrome on my desktop computer. The problem is therefore with the autostart configuration I think.

**Comment by bougs93** [comment]
https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/242

In case you want to disable it, then add AUTODETECT_PORT=false to your settings under '/etc/default/touchui'


sudo nano /etc/default/touchui
AUTODETECT_PORT=false

**Comment by AP4130** [comment]
Please take a look at issue #445; @Craigeous posted a temp fix to the chromium.xinit file that solved this for me.
