### ISSUE TITLE
USB Camera Not Working

### ISSUE THREAD

**Issue by Kev7274** [BillyBlaze/OctoPrint-TouchUI#45]
I have a Logitech C170  usb cam that WORKS when viewing the web URL,but not on the Pi 7" touchscreen. I also have a Pi Cam,but I haven't tried to hook it up yet.

Sorry for creating another issues so quick. Thanks

**Comment by BillyBlaze** [comment]
Please see: https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#webcam-image-not-working
