### ISSUE TITLE
Control tab Broken in OctoPrint 1.5.0

### ISSUE THREAD

**Issue by BillyBlaze** [BillyBlaze/OctoPrint-TouchUI#450]

**Comment by cp2004** [comment]
Off the top of my head I can't remember what else changed in the tab other than https://github.com/OctoPrint/OctoPrint/issues/3686, if that helps.

**Comment by BillyBlaze** [comment]
Thanks for the pointer, I decided to refactor the code a bit and drop support for OctoPrint 1.30<

This should now be fixed on the maintenance branch

**Comment by pebsi** [comment]
thanks, when will this be pushed to the main branch? I just installed the octoprint release candidate 3 and all icons have gone.

**Comment by BillyBlaze** [comment]
0.3.17 was just released.
