### ISSUE TITLE
Install on non-raspbian os not work

### ISSUE THREAD

**Issue by upx1211** [BillyBlaze/OctoPrint-TouchUI#452]
Hello.
I have octoprint installed on armbian (Orange PI PC2).
I got this error while trying to install TouchUI: "Expand your file system before running this helper. Run `sudo raspi-config` and select `Expand filesystem`"
I have enough free space.

/dev/mmcblk0p1   15G  3.4G   11G  25% /

**Comment by BillyBlaze** [comment]
That is annoying.

If you want to fix this for other users, then you could create a PR for this [file](https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart/blob/master/helpers/functions/get_can_expand)

If you just want to install it now then you can add `--force` behind the install command.
