### ISSUE TITLE
Not compatible with UI Customizer 

### ISSUE THREAD

**Issue by markeby** [BillyBlaze/OctoPrint-TouchUI#458]
TouchUI display does not display properly with UI Customizer active.
Options that cause issues:

- Center topbar icons
- Fluid/full width layout
- If macro is selected for sidebar it will not disply in TouchUI

**Comment by KarnofWar** [comment]
With UI Customizer enabled, on my TFT the first menu on the left doesn't' display anything, just blackness. Temp, control, other menus work fine.

**Comment by kimpixel** [comment]
i would love a fix!!

**Comment by crstrand** [comment]
Just installed UI customizer and now my Touch UI is broken
