### ISSUE TITLE
OctoPrint auto login?

### ISSUE THREAD

**Issue by m-marcjanik** [BillyBlaze/OctoPrint-TouchUI#464]
Hi!
I've just read, that starting with 1.5.0, OctoPrint will enforce access control to be enabled, meaning that each time TouchUI restarts, logging in is required, which requires plugging in keyboard to put in credentials. Is there any way to work with that because to be honest it is quite problematic. I've tried hitting "remember me" on login page but unfortunately it doesn't work. Any idea on solutions to this issue? I would really appreciate it.

**Comment by cp2004** [comment]
@marcjanik if you haven't already, I suggest checking out the [guide to configuring 'Auto Login Local'](https://community.octoprint.org/t/how-to-set-up-octoprint-to-autologin-a-single-user-when-connecting-from-the-internal-network/26235?u=charlie_powell) linked from the [1.5.0 release notes](https://octoprint.org/blog/2020/11/30/new-release-1.5.0/).
