### ISSUE TITLE
how I can uninstall?

### ISSUE THREAD

**Issue by rteixeira-chairmain** [BillyBlaze/OctoPrint-TouchUI#468]
Hi,

My screen have 5'' and don't work , how i can unistall?

thank you in advance

**Comment by gschmitt946** [comment]
I need to know aswell

**Comment by Yokosa** [comment]
sudo ~/TouchUI-autostart/helpers/uninstall

**Comment by Yokosa** [comment]
@rteixeira-chairmain @gschmitt946 
sudo ~/TouchUI-autostart/helpers/uninstall
