### ISSUE TITLE
UI does not render correctly on low resolution. 

### ISSUE THREAD

**Issue by t-keith** [BillyBlaze/OctoPrint-TouchUI#469]
![Screenshot_20201227-144115](https://user-images.githubusercontent.com/76664881/103179463-039bea80-4852-11eb-94f8-3d18118569c6.png)

Tried in chrome and Firefox. Version 0.3.17 480x854 screen resolution.

**Comment by DanielYWoo** [comment]
The icons are not loaded, looks like network loading issue. Did you ever clean cache and restart the browser?

**Comment by t-keith** [comment]
> The icons are not loaded, looks like network loading issue. Did you ever clean cache and restart the browser?

I tried with multiple browsers, including ones that have never loaded it.

**Comment by DanielYWoo** [comment]
I experienced the same thing, but eventually the icons are loaded and it works again. To load the page, it takes 13MB to load, sometimes very slow on a Pi1 or Pi2B.

**Comment by t-keith** [comment]
> I experienced the same thing, but eventually the icons are loaded and it works again. To load the page, it takes 13MB to load, sometimes very slow on a Pi1 or Pi2B.

I don't think that's what's going here. I did clear the cache, and icons are loaded, they just don't have enough room to display, or are too large to fit. If you look at the layout in the controls tab it is all messed up,nothing to do with icons.

**Comment by DanielYWoo** [comment]
maybe you can open the developer tools in chrome to see which request are always pending or failed?
