### ISSUE TITLE
TouchUI isn't auto booting

### ISSUE THREAD

**Issue by jdenec123** [BillyBlaze/OctoPrint-TouchUI#47]
HellO!

I'm going to preface this by saying I am very new to this.

I followed your guide to install TouchUI and get it to autoboot on a Raspberry pi 7" touchscreen. However, it doesn't auto boot. I went through previous issues opened with other users and nothing helped. Whenever I reboot the Pi, it goes straight to the command line. I tried to manually boot with:

xinit /home/pi/OctoPrint-TouchUI-autostart/start_chromium.xinit

as you suggested to another user. No luck. I tried to use that command through SSH and directly into the Pi. It came up with this:

X.Org X Server 1.17.2
Release Date: 2015-06-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.8.11-2-ARCH armv7l Raspbian
Current Operating System: Linux octopi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l
Kernel command line: 8250.nr_uarts=1 dma.dmachans=0x7f35 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2709.boardrev=0xa22082 bcm2709.serial=0xe7f5ea94 smsc95xx.macaddr=B8:27:EB:F5:EA:94 bcm2708_fb.fbswap=1 bcm2709.uart_clock=48000000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait fbcon=map:10 fbcon=font:ProFont6x11
Build Date: 11 January 2016  01:32:44PM
xorg-server 2:1.17.2-1+rpi1 (http://www.debian.org/support)
Current version of pixman: 0.33.3
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat May 28 16:44:48 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/home/pi/OctoPrint-TouchUI-autostart/start_chromium.xinit: 4: /home/pi/OctoPrint-TouchUI-autostart/start_chromium.xinit: chromium-browser: not found
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.

I have tried everything in this thread: https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/44 nothing worked.

Thanks! Very excited to get this working!

**Comment by BillyBlaze** [comment]
Hello jdenec123,

The log say the following error `chromium-browser: not found` which indicates Chrome is not installed, did you perhaps missed following [these instructions](https://www.raspberrypi.org/forums/viewtopic.php?t=121195)?

~Paul

**Comment by jdenec123** [comment]
I thought I did. I will go through the steps again though. Will I have to go through all the steps again, or will it work once I install Chromium?

**Comment by jdenec123** [comment]
Okay, its installed and mostly working. On fist time startup, it worked perfectly. The Pi itself went strait into TouchUI. However, it wouldn't connect to my printer. This was probably because I turned the printer on after the Pi. I restarted it, but it wont boot strait into TouchUI anymore. Would you happen to know why that is?

**Comment by BillyBlaze** [comment]
No, I have no idea, so if TouchUI doesn't boot, do you see the normal interface of OctoPrint? or nothing at all? And if yes, if you do `sudo service touchui restart` will that solve it?

**Comment by jdenec123** [comment]
Normal OctoPrint shows up, but I can't do anything on it. When I try to click on anything in OctoPrint, nothing happens. I will try that when I get home in a couple hours and get back to you.

**Comment by jdenec123** [comment]
Yes, that did solve it. Will I have to do it every time the server boots up? Or will that fix it permanently?

**Comment by jdenec123** [comment]
Just answered that for myself. No, it doesn't. But, I have a new problem, and I'm not actually sure if this is the fault of TouchUI. When I type in my Octoprint username and password and press login, the login button blinks but does nothing. Can't log into octoprint. I have tried restarting the server, changing the password, making absolute sure that I was typing in the correct password. Can you think of anything that I could do to fix it?

**Comment by BillyBlaze** [comment]
I have an idea, but we need to dig a bit deeper, could you provide me your octoprint log (located under .octoprint/log/)

**Comment by BillyBlaze** [comment]
I am going to close this issue, please check for updates on the login issue in ticket #42 

Me and foosel are trying to figure out a solution for the problem.
