### ISSUE TITLE
OctoPrint Will Not Launch on Pi Display

### ISSUE THREAD

**Issue by AngeloAna** [BillyBlaze/OctoPrint-TouchUI#470]
I installed Touch UI according to the directions on a Pi 4 b with a MageDok 7 inch touchscreen. It gets to the Touch UI Loading OctoPrint page. At the bottom it is loading 127.0.0.1. It times out and says it can't load the page. Below is most of the SSH session showing pertinent information. I can launch it from the Pi desktop chromium browser with no problems.

pi@octopi:~ $ git clone https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart.git ~/TouchUI-autostart/
Cloning into '/home/pi/TouchUI-autostart'...
remote: Enumerating objects: 330, done.
remote: Total 330 (delta 0), reused 0 (delta 0), pack-reused 330
Receiving objects: 100% (330/330), 58.94 KiB | 370.00 KiB/s, done.
Resolving deltas: 100% (193/193), done.
pi@octopi:~ $ sudo ~/TouchUI-autostart/helpers/install
[sudo] password for pi:
 ╔╦╗╔═╗╦ ╦╔═╗╦ ╦╦ ╦╦
  ║ ║ ║║ ║║  ╠═╣║ ║║
  ╩ ╚═╝╚═╝╚═╝╩ ╩╚═╝╩
Install helper v0.0.3

Boot to command line:
 - success

Running apt-get update (this will take a while)
Do NOT switch off the Pi or close this console until done!
 - success

Installing dependencies (xinit xinput xserver-xorg xserver-xorg-video-fbdev x11-xserver-utils matchbox unclutter chromium-browser):
 - success

Creating xserver config file:
 - success

Move touchui.init to '/etc/init.d/touchui':
 - success

Move touchui.default to '/etc/default/touchui':
 - success

Register touchui:
 - success

/home/pi/TouchUI-autostart/helpers/install-steps/6-setup-autologin-as: line 8: [: too many arguments
Skipping setup autoLogin for localhost:
 - Cancelled by user

TouchUI is successfully installed, Do not remove the directory
~/TouchUI-autostart/ and if you change the path of this directory
then edit the file /etc/default/touchui with the new path.

Launching TouchUI:
 - success
pi@octopi:~ $ sudo reboot

pi@octopi:~ $ sudo ~/TouchUI-autostart/helpers/install
[sudo] password for pi:
 ╔╦╗╔═╗╦ ╦╔═╗╦ ╦╦ ╦╦
  ║ ║ ║║ ║║  ╠═╣║ ║║
  ╩ ╚═╝╚═╝╚═╝╩ ╩╚═╝╩
Install helper v0.0.3

Skipping installation of dependencies:
 - All dependencies are already installed

Skipping creation of xserver config file:
 - /dev/fb0 already configured

Move touchui.init to '/etc/init.d/touchui':
 - success

Move touchui.default to '/etc/default/touchui':
 - success

Register touchui:
 - success

/home/pi/TouchUI-autostart/helpers/install-steps/6-setup-autologin-as: line 8: [: too many arguments
Saving autoLogin to config (/home/pi/.octoprint/config.yaml)

TouchUI is successfully installed, Do not remove the directory
~/TouchUI-autostart/ and if you change the path of this directory
then edit the file /etc/default/touchui with the new path.

Launching TouchUI:
 - success
pi@octopi:~ $ cd ~
pi@octopi:~ $ cd .octoprint/
pi@octopi:~/.octoprint $ cat config.yaml
accessControl:
    salt: rzCeaK1sVuCjvtuM2juOKb8dUsCaQYsG
api:
    key: DAE7736D651046EDA94709B7742E5807
appearance:
    components:
        order:
            tab:
            - temperature
            - plugin_cancelobject
            - control
            - plugin_webcamtab
            - terminal
            - plugin_gcodeviewer
            - plugin_octolapse
            - timelapse
            - plugin_resource_monitor
plugins:
    BetterHeaterTimeout:
        _config_version: 2
    PrintJobHistory:
        pluginCheckActivated: false
        preferedImageSource: camera
        showPrintJobDialogAfterPrint: false
    announcements:
        _config_version: 1
        channels:
            _blog:
                read_until: 1608041700
            _important:
                read_until: 1521111600
            _octopi:
                read_until: 1604571600
            _plugins:
                read_until: 1608876000
            _releases:
                read_until: 1607604000
    cura:
        cura_engine: /usr/local/bin/cura_engine
    discovery:
        publicPort: 80
        upnpUuid: 0f5c600c-93aa-4635-97f0-2dd06f9cf507
    errortracking:
        unique_id: c11f4770-e30b-4c0f-9b24-e67fd0d13a42
    excluderegion:
        _config_version: 1
    gcodeviewer:
        _config_version: 1
    octolapse:
        _config_version: 3
    resource_monitor:
        _config_version: 1
    softwareupdate:
        _config_version: 9
    taborder:
        _config_version: 5
        tabs:
        -   icon: ''
            icon_color: ''
            icon_tooltip: Temperature
            name: temperature
            showtext: true
            usetitle: true
        -   icon: fas fa-stop-circle
            icon_color: ''
            icon_tooltip: Cancel
            name: plugin_cancelobject
            showtext: true
            usetitle: true
        -   icon: ''
            icon_color: ''
            icon_tooltip: Control
            name: control
            showtext: true
            usetitle: true
        -   icon: ''
            icon_color: ''
            icon_tooltip: Webcam
            name: plugin_webcamtab
            showtext: true
            usetitle: true
        -   icon: ''
            icon_color: ''
            icon_tooltip: Terminal
            name: terminal
            showtext: true
            usetitle: true
        -   icon: ''
            icon_color: ''
            icon_tooltip: GCode
            name: gcodeviewer
            showtext: true
            usetitle: true
        -   icon: ''
            icon_color: ''
            icon_tooltip: Octolapse
            name: plugin_octolapse
            showtext: true
            usetitle: true
        -   icon: ''
            icon_color: ''
            icon_tooltip: Timelapse
            name: timelapse
            showtext: true
            usetitle: true
        -   icon: ''
            icon_color: ''
            icon_tooltip: Resource Monitor
            name: plugin_resource_monitor
            showtext: true
            usetitle: true
    themeify:
        customRules:
        -   enabled: false
            rule: background-color
            selector: .navbar-inner
            value: '#2f3136'
        -   enabled: false
            rule: background-color
            selector: .accordion
            value: '#2f3136'
        -   enabled: true
            rule: width
            selector: .span8
            value: 70%
        -   enabled: true
            rule: width
            selector: .container
            value: 100%
        -   enabled: true
            rule: width
            selector: .span4
            value: 25%
        -   enabled: true
            rule: margin-left
            selector: .row
            value: '0'
        enableCustomization: true
        theme: material_ui_light
    thespaghettidetective:
        auth_token: c06af51ba4a12ae6b519
        sentry_opt: asked
    tracking:
        enabled: false
        unique_id: 4441d89e-1007-46bf-8d6a-f4a487c66528
    virtual_printer:
        _config_version: 1
printerProfiles:
    default: _default
server:
    commands:
        serverRestartCommand: sudo service octoprint restart
        systemRestartCommand: sudo shutdown -r now
        systemShutdownCommand: sudo shutdown -h now
    firstRun: false
    incompleteStartup: true
    onlineCheck:
        enabled: true
    pluginBlacklist:
        enabled: true
    secretKey: h3Pt2sM2jIIEb47MELvEwTEGaUCLz2lD
    seenWizards:
        corewizard: 3
        thespaghettidetective: 2
        tracking: null
temperature:
    profiles:
    -   bed: 100
        chamber: null
        extruder: 210
        name: ABS
    -   bed: 60
        chamber: null
        extruder: 180
        name: PLA
webcam:
    ffmpeg: /usr/bin/ffmpeg
    flipH: true
    flipV: true
    snapshot: http://127.0.0.1:8080/?action=snapshot
    stream: /webcam/?action=stream
    timelapse:
        fps: 25
        options:
            minDelay: 5.0
            retractionZHop: 0.0
        postRoll: 0
        type: zchange
    watermark: false

pi@octopi:~ $ xinit /home/pi/OctoPrint-TouchUI-autostart/start_chromium.xinit

(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE)
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 7 requests (7 known processed) with 0 events remaining.
pi@octopi:~ $ cat /var/log/Xorg.0.log
[    19.965]
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
[    19.965] Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
[    19.965] Current Operating System: Linux octopi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l
[    19.965] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:800x600M@60 smsc95xx.macaddr=DC:A6:32:79:82:23 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=6c586e13-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    19.966] Build Date: 01 December 2020  05:59:57PM
[    19.966] xorg-server 2:1.20.4-1+rpt2+deb10u2 (https://www.debian.org/support)
[    19.966] Current version of pixman: 0.36.0
[    19.966]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[    19.966] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    19.966] (==) Log file: "/var/log/Xorg.0.log", Time: Wed Dec 30 03:33:51 2020
[    19.977] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    19.982] (==) No Layout section.  Using the first Screen section.
[    19.982] (==) No screen section available. Using defaults.
[    19.982] (**) |-->Screen "Default Screen Section" (0)
[    19.982] (**) |   |-->Monitor "<default monitor>"
[    19.989] (==) No device specified for screen "Default Screen Section".
        Using the first device section listed.
[    19.989] (**) |   |-->Device "touchscreen"
[    19.989] (**) |   |-->GPUDevice "Allwinner A10/A13 FBDEV"
[    19.989] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[    19.989] (==) Automatically adding devices
[    19.989] (==) Automatically enabling devices
[    19.989] (==) Automatically adding GPU devices
[    19.996] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    20.000] (WW) The directory "/usr/share/fonts/X11/misc" does not exist.
[    20.000]    Entry deleted from font path.
[    20.000] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    20.000]    Entry deleted from font path.
[    20.000] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    20.000]    Entry deleted from font path.
[    20.000] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    20.000]    Entry deleted from font path.
[    20.000] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    20.000]    Entry deleted from font path.
[    20.000] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    20.000]    Entry deleted from font path.
[    20.000] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    20.000]    Entry deleted from font path.
[    20.000] (==) FontPath set to:
        built-ins
[    20.001] (==) ModulePath set to "/usr/lib/xorg/modules"
[    20.001] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[    20.001] (II) Loader magic: 0x1fdf80
[    20.001] (II) Module ABI versions:
[    20.001]    X.Org ANSI C Emulation: 0.4
[    20.001]    X.Org Video Driver: 24.0
[    20.001]    X.Org XInput driver : 24.1
[    20.001]    X.Org Server Extension : 10.0
[    20.002] (--) using VT number 2

[    20.002] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    20.004] (II) xfree86: Adding drm device (/dev/dri/card1)
[    20.017] (II) xfree86: Adding drm device (/dev/dri/card0)
[    20.018] (II) no primary bus or device found
[    20.018]    falling back to /sys/devices/platform/gpu/drm/card1
[    20.018] (II) LoadModule: "glx"
[    20.022] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    20.061] (II) Module glx: vendor="X.Org Foundation"
[    20.061]    compiled for 1.20.4, module version = 1.0.0
[    20.061]    ABI class: X.Org Server Extension, version 10.0
[    20.061] (II) LoadModule: "fbdev"
[    20.061] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[    20.063] (II) Module fbdev: vendor="X.Org Foundation"
[    20.063]    compiled for 1.20.3, module version = 0.5.0
[    20.063]    Module class: X.Org Video Driver
[    20.063]    ABI class: X.Org Video Driver, version 24.0
[    20.063] (II) LoadModule: "fbturbo"
[    20.064] (II) Loading /usr/lib/xorg/modules/drivers/fbturbo_drv.so
[    20.067] (II) Module fbturbo: vendor="X.Org Foundation"
[    20.067]    compiled for 1.20.3, module version = 0.5.1
[    20.067]    Module class: X.Org Video Driver
[    20.067]    ABI class: X.Org Video Driver, version 24.0
[    20.067] (II) FBDEV: driver for framebuffer: fbdev
[    20.067] (II) FBDEV: driver for framebuffer: fbdev
[    20.084] (WW) Falling back to old probe method for fbdev
[    20.084] (II) Loading sub module "fbdevhw"
[    20.084] (II) LoadModule: "fbdevhw"
[    20.084] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    20.089] (II) Module fbdevhw: vendor="X.Org Foundation"
[    20.089]    compiled for 1.20.4, module version = 0.0.2
[    20.090]    ABI class: X.Org Video Driver, version 24.0
[    20.090] (II) FBDEV(0): using /dev/fb0
[    20.090] (WW) Falling back to old probe method for fbdev
[    20.090] (II) FBDEV(0): Creating default Display subsection in Screen section
        "Default Screen Section" for depth/fbbpp 16/16
[    20.090] (==) FBDEV(0): Depth 16, (==) framebuffer bpp 16
[    20.090] (==) FBDEV(0): RGB weight 565
[    20.090] (==) FBDEV(0): Default visual is TrueColor
[    20.090] (==) FBDEV(0): Using gamma correction (1.0, 1.0, 1.0)
[    20.090] (II) FBDEV(0): hardware: vc4drmfb (video memory: 937kB)
[    20.090] (DB) xf86MergeOutputClassOptions unsupported bus type 0
[    20.090] (**) FBDEV(0): Option "fbdev" "/dev/fb0"
[    20.090] (II) FBDEV(0): checking modes against framebuffer device...
[    20.090] (II) FBDEV(0): checking modes against monitor...
[    20.090] (II) FBDEV(0): Virtual size is 800x600 (pitch 800)
[    20.090] (**) FBDEV(0):  Built-in mode "current"
[    20.090] (==) FBDEV(0): DPI set to (96, 96)
[    20.090] (II) Loading sub module "fb"
[    20.090] (II) LoadModule: "fb"
[    20.091] (II) Loading /usr/lib/xorg/modules/libfb.so
[    20.096] (II) Module fb: vendor="X.Org Foundation"
[    20.096]    compiled for 1.20.4, module version = 1.0.0
[    20.096]    ABI class: X.Org ANSI C Emulation, version 0.4
[    20.096] (**) FBDEV(0): using shadow framebuffer
[    20.096] (II) Loading sub module "shadow"
[    20.096] (II) LoadModule: "shadow"
[    20.097] (II) Loading /usr/lib/xorg/modules/libshadow.so
[    20.099] (II) Module shadow: vendor="X.Org Foundation"
[    20.099]    compiled for 1.20.4, module version = 1.1.0
[    20.099]    ABI class: X.Org ANSI C Emulation, version 0.4
[    20.099] (II) UnloadModule: "fbturbo"
[    20.099] (II) Unloading fbturbo
[    20.134] (==) FBDEV(0): Backing store enabled
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.137] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (EE) FBDEV(0): FBIOPUTCMAP: Invalid argument
[    20.138] (==) FBDEV(0): DPMS enabled
[    20.139] (II) Initializing extension Generic Event Extension
[    20.140] (II) Initializing extension SHAPE
[    20.141] (II) Initializing extension MIT-SHM
[    20.142] (II) Initializing extension XInputExtension
[    20.144] (II) Initializing extension XTEST
[    20.145] (II) Initializing extension BIG-REQUESTS
[    20.145] (II) Initializing extension SYNC
[    20.146] (II) Initializing extension XKEYBOARD
[    20.146] (II) Initializing extension XC-MISC
[    20.147] (II) Initializing extension SECURITY
[    20.147] (II) Initializing extension XFIXES
[    20.148] (II) Initializing extension RENDER
[    20.148] (II) Initializing extension RANDR
[    20.149] (II) Initializing extension COMPOSITE
[    20.151] (II) Initializing extension DAMAGE
[    20.152] (II) Initializing extension MIT-SCREEN-SAVER
[    20.152] (II) Initializing extension DOUBLE-BUFFER
[    20.153] (II) Initializing extension RECORD
[    20.153] (II) Initializing extension DPMS
[    20.154] (II) Initializing extension Present
[    20.154] (II) Initializing extension DRI3
[    20.154] (II) Initializing extension X-Resource
[    20.155] (II) Initializing extension XVideo
[    20.155] (II) Initializing extension XVideo-MotionCompensation
[    20.155] (II) Initializing extension SELinux
[    20.155] (II) SELinux: Disabled on system
[    20.155] (II) Initializing extension GLX
[    20.156] (II) AIGLX: Screen 0 is not DRI2 capable
[    20.956] (II) IGLX: Loaded and initialized swrast
[    20.956] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[    20.956] (II) Initializing extension XFree86-VidModeExtension
[    20.956] (II) Initializing extension XFree86-DGA
[    20.957] (II) Initializing extension XFree86-DRI
[    20.959] (II) Initializing extension DRI2
[    21.106] (II) config/udev: Adding input device SIGMACHIP USB Keyboard (/dev/input/event0)
[    21.106] (**) SIGMACHIP USB Keyboard: Applying InputClass "libinput keyboard catchall"
[    21.106] (II) LoadModule: "libinput"
[    21.109] (II) Loading /usr/lib/xorg/modules/input/libinput_drv.so
[    21.135] (II) Module libinput: vendor="X.Org Foundation"
[    21.135]    compiled for 1.20.3, module version = 0.28.2
[    21.135]    Module class: X.Org XInput Driver
[    21.136]    ABI class: X.Org XInput driver, version 24.1
[    21.136] (II) Using input driver 'libinput' for 'SIGMACHIP USB Keyboard'
[    21.136] (**) SIGMACHIP USB Keyboard: always reports core events
[    21.136] (**) Option "Device" "/dev/input/event0"
[    21.136] (**) Option "_source" "server/udev"
[    21.167] (II) event0  - SIGMACHIP USB Keyboard: is tagged by udev as: Keyboard
[    21.167] (II) event0  - SIGMACHIP USB Keyboard: device is a keyboard
[    21.169] (II) event0  - SIGMACHIP USB Keyboard: device removed
[    21.220] (**) Option "config_info" "udev:/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:1C4F:0002.0001/input/input0/event0"
[    21.220] (II) XINPUT: Adding extended input device "SIGMACHIP USB Keyboard" (type: KEYBOARD, id 6)
[    21.220] (**) Option "xkb_model" "pc105"
[    21.220] (**) Option "xkb_layout" "gb"
[    21.278] (II) event0  - SIGMACHIP USB Keyboard: is tagged by udev as: Keyboard
[    21.278] (II) event0  - SIGMACHIP USB Keyboard: device is a keyboard
[    21.283] (II) config/udev: Adding input device SIGMACHIP USB Keyboard Consumer Control (/dev/input/event1)
[    21.283] (**) SIGMACHIP USB Keyboard Consumer Control: Applying InputClass "libinput keyboard catchall"
[    21.283] (II) Using input driver 'libinput' for 'SIGMACHIP USB Keyboard Consumer Control'
[    21.284] (**) SIGMACHIP USB Keyboard Consumer Control: always reports core events
[    21.284] (**) Option "Device" "/dev/input/event1"
[    21.284] (**) Option "_source" "server/udev"
[    21.292] (II) event1  - SIGMACHIP USB Keyboard Consumer Control: is tagged by udev as: Keyboard
[    21.293] (II) event1  - SIGMACHIP USB Keyboard Consumer Control: device is a keyboard
[    21.294] (II) event1  - SIGMACHIP USB Keyboard Consumer Control: device removed
[    21.350] (II) libinput: SIGMACHIP USB Keyboard Consumer Control: needs a virtual subdevice
[    21.350] (**) Option "config_info" "udev:/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:1C4F:0002.0002/input/input1/event1"
[    21.350] (II) XINPUT: Adding extended input device "SIGMACHIP USB Keyboard Consumer Control" (type: MOUSE, id 7)
[    21.350] (**) Option "AccelerationScheme" "none"
[    21.350] (**) SIGMACHIP USB Keyboard Consumer Control: (accel) selected scheme none/0
[    21.350] (**) SIGMACHIP USB Keyboard Consumer Control: (accel) acceleration factor: 2.000
[    21.350] (**) SIGMACHIP USB Keyboard Consumer Control: (accel) acceleration threshold: 4
[    21.358] (II) event1  - SIGMACHIP USB Keyboard Consumer Control: is tagged by udev as: Keyboard
[    21.358] (II) event1  - SIGMACHIP USB Keyboard Consumer Control: device is a keyboard
[    21.362] (II) config/udev: Adding input device SIGMACHIP USB Keyboard System Control (/dev/input/event2)
[    21.362] (**) SIGMACHIP USB Keyboard System Control: Applying InputClass "libinput keyboard catchall"
[    21.362] (II) Using input driver 'libinput' for 'SIGMACHIP USB Keyboard System Control'
[    21.362] (**) SIGMACHIP USB Keyboard System Control: always reports core events
[    21.362] (**) Option "Device" "/dev/input/event2"
[    21.362] (**) Option "_source" "server/udev"
[    21.369] (II) event2  - SIGMACHIP USB Keyboard System Control: is tagged by udev as: Keyboard
[    21.369] (II) event2  - SIGMACHIP USB Keyboard System Control: device is a keyboard
[    21.369] (II) event2  - SIGMACHIP USB Keyboard System Control: device removed
[    21.441] (**) Option "config_info" "udev:/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:1C4F:0002.0002/input/input2/event2"
[    21.441] (II) XINPUT: Adding extended input device "SIGMACHIP USB Keyboard System Control" (type: KEYBOARD, id 8)
[    21.441] (**) Option "xkb_model" "pc105"
[    21.441] (**) Option "xkb_layout" "gb"
[    21.449] (II) event2  - SIGMACHIP USB Keyboard System Control: is tagged by udev as: Keyboard
[    21.449] (II) event2  - SIGMACHIP USB Keyboard System Control: device is a keyboard
[    21.454] (II) config/udev: Adding input device TPK USA LLC Touch Fusion 4. (/dev/input/event3)
[    21.454] (**) TPK USA LLC Touch Fusion 4.: Applying InputClass "libinput touchscreen catchall"
[    21.454] (II) Using input driver 'libinput' for 'TPK USA LLC Touch Fusion 4.'
[    21.454] (**) TPK USA LLC Touch Fusion 4.: always reports core events
[    21.454] (**) Option "Device" "/dev/input/event3"
[    21.454] (**) Option "_source" "server/udev"
[    21.462] (II) event3  - TPK USA LLC Touch Fusion 4.: is tagged by udev as: Touchscreen
[    21.462] (II) event3  - TPK USA LLC Touch Fusion 4.: device is a touch device
[    21.462] (II) event3  - TPK USA LLC Touch Fusion 4.: device removed
[    21.500] (**) Option "config_info" "udev:/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:3912:1121.0003/input/input4/event3"
[    21.500] (II) XINPUT: Adding extended input device "TPK USA LLC Touch Fusion 4." (type: TOUCHSCREEN, id 9)
[    21.501] (**) Option "AccelerationScheme" "none"
[    21.501] (**) TPK USA LLC Touch Fusion 4.: (accel) selected scheme none/0
[    21.501] (**) TPK USA LLC Touch Fusion 4.: (accel) acceleration factor: 2.000
[    21.501] (**) TPK USA LLC Touch Fusion 4.: (accel) acceleration threshold: 4
[    21.508] (II) event3  - TPK USA LLC Touch Fusion 4.: is tagged by udev as: Touchscreen
[    21.508] (II) event3  - TPK USA LLC Touch Fusion 4.: device is a touch device
[    21.512] (II) config/udev: Adding input device TPK USA LLC Touch Fusion 4. (/dev/input/mouse0)
[    21.512] (II) No input driver specified, ignoring this device.
[    21.512] (II) This device may have been added with another device file.
[    21.542] (**) SIGMACHIP USB Keyboard Consumer Control: Applying InputClass "libinput keyboard catchall"
[    21.542] (II) Using input driver 'libinput' for 'SIGMACHIP USB Keyboard Consumer Control'
[    21.542] (**) SIGMACHIP USB Keyboard Consumer Control: always reports core events
[    21.542] (**) Option "Device" "/dev/input/event1"
[    21.542] (**) Option "_source" "_driver/libinput"
[    21.543] (II) libinput: SIGMACHIP USB Keyboard Consumer Control: is a virtual subdevice
[    21.543] (**) Option "config_info" "udev:/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:1C4F:0002.0002/input/input1/event1"
[    21.543] (II) XINPUT: Adding extended input device "SIGMACHIP USB Keyboard Consumer Control" (type: KEYBOARD, id 10)
[    21.543] (**) Option "xkb_model" "pc105"
[    21.543] (**) Option "xkb_layout" "gb"

pi@octopi:~ $ xinit /home/pi/OctoPrint-TouchUI-autostart/start_chromium.xinit

(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE)
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 7 requests (7 known processed) with 0 events remaining.
pi@octopi:~ $

**Comment by modusmoron** [comment]
Try this fix: [https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/445](https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/445)

I've been battling this for the past two days, just found that solution, it worked great!

**Comment by AngeloAna** [comment]
That fixed the problem. Thank you very much!
