### ISSUE TITLE
Support 480x320 screen

### ISSUE THREAD

**Issue by DanielYWoo** [BillyBlaze/OctoPrint-TouchUI#471]
Many users use TouchUI for small and compact TFT screen embedded into the rack, but the UI cannot be fully displayed on such small screens. Is it possible to support from 480x320? This would be the smallest screen widely used I think, most of them are 3.5', very popular.

**Comment by maumontel** [comment]
It will be great,  a small,  adjusted interface for these screens

**Comment by DanielYWoo** [comment]
any updates?
