### ISSUE TITLE
[question] How to create and register icons/bitmaps for TouchUI ?

### ISSUE THREAD

**Issue by yet-another-average-joe** [BillyBlaze/OctoPrint-TouchUI#475]
The question is in the title... How to make or fork a plugin so it is TouchUI-friendly ?

How to get rid of the '?'

IMHO, it would be mandatory for any plugin.

**Comment by cp2004** [comment]
@yet-another-average-joe you can make a request (or pull request) like this one, to add an icon to a plugin https://github.com/cp2004/OctoPrint-EEPROM-Marlin/issues/6
