### ISSUE TITLE
Issues installing Touch UI on Pi3

### ISSUE THREAD

**Issue by kieran1707** [BillyBlaze/OctoPrint-TouchUI#481]
Hello,
I am having issues installing TouchUI on my Pi screen. The screen is working but I do not have the browser working. I get a failed message when I run sudo ~TouchUI-autostart/helpers/install:

Running apt-get update (this will take a while)
Do NOT switch off the Pi or close this console until done!
 - success

Installing dependencies (xinit xinput xserver-xorg xserver-xorg-video-fbdev x11-xserver-utils matchbox unclutter chromium-browser):
 - failed

I have installed chromium-browser but can't get past this point - what am I doing wrong?

Thanks,
Kieran

**Comment by anibluny** [comment]
Run:
sudo apt --fix-broken install

Then again run:
sudo ~TouchUI-autostart/helpers/install

See #333 for the details
