### ISSUE TITLE
TouchUi starts and promptly quits to console

### ISSUE THREAD

**Issue by MrFlint** [BillyBlaze/OctoPrint-TouchUI#49]
Running OctoPi on RPI2 with a 5" touchscreen, after the last update TouchUi no longer starts, just a short blink then goes back to the console. None of the fixes mentioned in the wiki appear to work. OctoPrint server works however, and accessible from the network.

**Comment by BillyBlaze** [comment]
Thanks for reporting! I guess you found the solution already? or did you accidently pressed closed? Also if you did fix the problem, could you share your solution in case somebody else run in this problem?
