### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by wbatzle** [BillyBlaze/OctoPrint-TouchUI#490]
Hello. I am having issues with the screen loading in a funky manner. I have disabled all plugins and even tried safe mode. I was able to finally get the TouchUI to load on the screen using the fixes for IPv6 and the Chrome config. But now all I see is the below. I did have UI Customizer installed. So I decided that it was a plugin issue and rebuilt my pi from scratch. I fully updated it and only applied the TouchUI plugin via commandline provided. I am still having the same issue.

![20210407_125507](https://user-images.githubusercontent.com/18704920/113905001-aee90380-97a0-11eb-820a-3b32af02535e.jpg)

**Comment by BillyBlaze** [comment]
Thanks for reporting. The issue has been fixed.

If you made changes to your default file then restore `8888`
If you changed the script.js file then restore the original files by running `git reset --hard` in the TouchUI-autostart folder.

After that you can [update your bootloader](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Update-your-bootloader) as described in the wiki.
