### ISSUE TITLE
TouchUI autostart install script fails un USB/network filesystem

### ISSUE THREAD

**Issue by Nailig** [BillyBlaze/OctoPrint-TouchUI#495]
On a raspberry pi with a fresh install of octopi and touchui 

The install-step "1-check-mounted-sd" Does not work when you boot from an USB device (at least in my case) or when you boot from network.

If i remove this step from the install script, the script runs without problems on USB/network connected filesystems (in my case)

I propose to leave this step out, or check for available disk size.

octopi 1.5.x 1.6.1
touchui 0.3.17

**Comment by BillyBlaze** [comment]
Thanks for reporting. I have added an extra argument named `--skip-sd-check` to allow the skipping of this step.
