### ISSUE TITLE
When "Enable Customization" is enabled tab bar no longer appears

### ISSUE THREAD

**Issue by beelsebob** [BillyBlaze/OctoPrint-TouchUI#497]
When "Enable Customization" is enabled the tab bar at the top of the screen no longer presents any buttons.  Instead it becomes a solid coloured header bar, and controls disappear under it.

This occurs even with a fresh install of TouchUI with no customisations specified.

**Comment by theHalo** [comment]
Same Problem here. Just a blank, blue bar at the top. Switching off customizations reverts to desktop mode without any tab icons either.

**Comment by avigeilpro** [comment]
> 
> 
> Same Problem here. Just a blank, blue bar at the top. Switching off customizations reverts to desktop mode without any tab icons either.

after switching off customization you have to restart octoprint, and all will be back.

**Comment by theHalo** [comment]
That did the trick. Thanks for the hint.

**Comment by Jahislove** [comment]
same problem here . only blue bar at top without tab icons
switching customization off and restarting octoprint did the job

**Comment by devildant** [comment]
@BillyBlaze still no solution?

**Comment by devildant** [comment]
link to https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/494

**Comment by beelsebob** [comment]
Bumping, because this issue is still valid.

**Comment by BillyBlaze** [comment]
The issue has been fixed on the maintenance branch and will be released a.s.a.p

closing this issue since its a duplicate of #494
