### ISSUE TITLE
Files context menu hidden with Thumbnail plugins 

### ISSUE THREAD

**Issue by gobbledygoober** [BillyBlaze/OctoPrint-TouchUI#504]
If either or both the [CuraThumbnails](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage) or [PrusaSlicerThumbnails](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails)  plugins are enabled, the "swipe left" context menu for the Files area appears black, without the expected controls. Tapping the black area where the controls should be does nothing. 

![642C9487-4A38-4984-A157-BEC8430E4A21](https://user-images.githubusercontent.com/86916654/124604963-73121880-de39-11eb-9c0c-beca45585acf.jpeg)

In the full browser, non-touch view, these plug-ins provide a "gcode thumbnail" in the Files area. 

![99B59A38-DE43-4467-810E-F5213A2CD326](https://user-images.githubusercontent.com/86916654/124605632-1d8a3b80-de3a-11eb-9187-d806feb4b390.jpeg)
![38796C60-EA2B-4F77-A5EE-3BF8F061CFC4](https://user-images.githubusercontent.com/86916654/124605758-3f83be00-de3a-11eb-90ba-59d3dbf9e8a3.jpeg)
![B20867AE-6D45-4EF9-8A51-13FC7D0A022F](https://user-images.githubusercontent.com/86916654/124605633-1e22d200-de3a-11eb-9c53-241cd15fd58c.jpeg)

Is there any relatively easy way for these plug-ins to coexist?

Thanks!

TouchUI 0.3.18
Cura Thumbnails 1.0.1
Slicer Thumbnails 1.0.0
OctoPrint 1.6.1
Python 3.7.3
OctoPi 0.18.0

**Comment by jorwex** [comment]
Can this be re-opened?
