### ISSUE TITLE
Navbar lost after update

### ISSUE THREAD

**Issue by InoxDragoon** [BillyBlaze/OctoPrint-TouchUI#505]
when using Touch UI on my phone and via octoeverywhere on my laptop, i lost the navigation bar, making the plugin almost useless. This happened today, 7/6/21 when upgrading to 0.3.18.
![Screenshot_20210706-153212_Edge](https://user-images.githubusercontent.com/87043404/124669648-fb131500-de6f-11eb-9511-3bd018cf155e.jpg)

**Comment by thedavefulton** [comment]
I'm seeing exactly the same behavior on both mobile devices and the 7" touchscreen attached to the pi. This also began for me immediately after updating the plugin

**Update**: After unselecting `Start TouchUI automatically onload based on touch device` and refreshing on my iPad the nav bar is back. Selecting the same option and reloading doesn't seem to have an impact.

**Comment by BillyBlaze** [comment]
What OctoPrint version is running? This was just fixed in #494 for OctoPrint 1.6.1

**Comment by thedavefulton** [comment]
I'm on `1.6.1`

For my part everything seems to be working fine now. I haven't had any issues past the initial problem right after updating the plugin.

**Comment by InoxDragoon** [comment]
Octoprint 1.6.1. It had me reboot after the update, and that's when things went wonky. However, after a subsequent reboot (also had to reinstall some MIA plug-ins after the update) all is well now. I should note that I've only been using octoprint for a few weeks now, so pardon me if I've missed an unwritten rule about rebooting after a reboot.... Lol

Thanks!
________________________________
