### ISSUE TITLE
TouchUI Website is not displayed on TFT

### ISSUE THREAD

**Issue by kami83** [BillyBlaze/OctoPrint-TouchUI#507]
Hi,

since some time my chromium browser is not displaying the small TFT TouchUI website on my LCD3,5. It is only showing the Big Octopi-Website?

Can someone help. 

BG kami

**Comment by BillyBlaze** [comment]
Hi,

Check the following (if the answer is yes move to the next one):

1. is TouchUI still installed?
2. is TouchUI still active? (e.g. not disabled)
3. is TouchUI working on other devices?

**Comment by kami83** [comment]
Hi, TouchUI is installed. On the LCD i cannot find a button to activate it. On the other devices like my laptop i can activate TouchUI and it is working.

**Comment by BillyBlaze** [comment]
hmm thats really weird.

1. have you modified the bootloader? (if yes; try reverting it to the original state)
2. could you disable all plugins and only activate TouchUI, restart TFT and see if it comes back

**Comment by Fox2525** [comment]
Hi, I have got the exact same problem. I have got a 7 inch touch display, that normally worked fine. After some updates it only opens the normal Octoprint Desktop Website. I also can't toggle back on the screen. With my Laptop and handy I can toggle back and forth and touch ui is working fine there. Haven't made any modifications on the bootloader. I will try to disable soms plugins and see if the problem is still there.

**Comment by kami83** [comment]
Hi, yes there is something wrong in the 0.3.18 version. I reinstalled an older Backup and everything works fine. Only after updating to Octopi 1.6.1 and 0.3.18 i get on my small touchdisplay the same Webview as on my normal browser PC.

How can i switch it. I think TouchUI is not recognizing the small size of the Screen. On my PC Browser i can active and deactived TouchUI normal. Thanks a lot.

Cu kami

**Comment by BillyBlaze** [comment]
is the plugin CustomizerUI perhaps installed?

**Comment by kami83** [comment]
No, this is my plugin list:
 "Firmware Updater",
  "DisplayZ",
  "BetterHeaterTimeout",
  "OctoPod Plugin",
  "Custom Control Editor",
  "TouchUI",
  "Fan Speed Control",
  "Bed Visualizer",
  "Complicated Plugin",
  "SlicerSettingsParser",
  "Filament Sensors Revolutions",
  "Dashboard",
  "Marlin EEPROM Editor",
  "PrintTimeGenius Plugin",
  "Filament Manager",
  "Octolapse"

**Comment by kami83** [comment]
Hi the problem comes from Filament Manager Plugin. If i deactive it, everything works fine.

Thx. 

BG kami
