### ISSUE TITLE
Boot to browser not working.

### ISSUE THREAD

**Issue by wedge71** [BillyBlaze/OctoPrint-TouchUI#508]
Have read through some things here before posting. tried #61 as a step but that fix does not work.

Raspberry Pi4B
Octoprint installed per instructions on webpage using PI imager
LCD - miuzei mpi4008

Screen is working fine. Can watch it boot up. Just will not go from command line into browser.

**Comment by ripvega** [comment]
> Have read through some things here before posting. tried #61 as a step but that fix does not work.
> 
> Raspberry Pi4B
> Octoprint installed per instructions on webpage using PI imager
> LCD - miuzei mpi4008
> 
> Screen is working fine. Can watch it boot up. Just will not go from command line into browser.

I have just done a vanilla install by [following this guide](https://howchoo.com/octoprint/3d-printer-octoprint-touchscreen) and it boots to browser fine.

The command to issue is:
```
git clone https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart.git ~/TouchUI-autostart/
sudo ~/TouchUI-autostart/helpers/install
```
