### ISSUE TITLE
Terminal input doesn't show what I type

### ISSUE THREAD

**Issue by CptanPanic** [BillyBlaze/OctoPrint-TouchUI#51]
Using TouchUI on my nexus 5x, in firefox.  Everything works great except when trying to use the terminal.  What I type doesn't show up, I see the cursor moving, but it seems too small for the font, and nothing shows up until I hit enter, and see the feedback.

**Comment by BillyBlaze** [comment]
Thanks for reporting! Completely forgot about responding. I will fix this in the upcoming release.

**Comment by BillyBlaze** [comment]
I just pushed a fix into the maintenance branch and will release this in 0.3.5 very soon.
