### ISSUE TITLE
Fix for installing TouchUI when other plugins are already enabled.

### ISSUE THREAD

**Issue by StrongbowTexas** [BillyBlaze/OctoPrint-TouchUI#513]
I kept running into this error during the installation (I was running the install in the directory of user "touchui", obviously:

#####
/home/touchui/TouchUI-autostart/helpers/install-steps/6-setup-autologin-as: line 8: [: too many arguments
#####

This error caused the touch screen on my Pi to try to load the UI, but just sat there at "Connecting to TouchUI".

Here's the fix. Apologies for not creating a fork, checking in my fix and creating a pull request, but I know just enough git to know what those words mean. 

#####
touchui@octopi:~/TouchUI-autostart $ git diff
diff --git a/helpers/install-steps/6-setup-autologin-as b/helpers/install-steps/6-setup-autologin-as
index 9d35efa..ca5b08a 100644
--- a/helpers/install-steps/6-setup-autologin-as
+++ b/helpers/install-steps/6-setup-autologin-as
@@ -1,8 +1,8 @@
 #!/bin/bash
 source $DIR/functions/successfull

-OCTOPRINT_EXEC=$(ps -ef | grep octoprint | grep -v grep | awk '{print $9}')
-OCTOPRINT_EXEC_USER=$(ps -ef | grep octoprint | grep -v grep | awk '{print $1}')
+OCTOPRINT_EXEC=$(ps -ef | grep [o]ctoprint | grep "[s]erve\b" | awk '{ print $9 }')
+OCTOPRINT_EXEC_USER=$(ps -ef | grep [o]ctoprint | grep "[s]erve\b" | awk '{ print $1 }')

 echo ""
 if [ -z $OCTOPRINT_EXEC ]

**Comment by BillyBlaze** [comment]
Thanks for reporting. Regardless what github-actions does I will fix this :+1:
