### ISSUE TITLE
 TouchUI opens always, regardless if desktop or on raspberry pi

### ISSUE THREAD

**Issue by user100000** [BillyBlaze/OctoPrint-TouchUI#525]
Octoprint  is installed on  an old  Astrobox touch unit  This has  a Waveshare 3.5 lcd(b)   screen 480x320 and appears to be working fine on there . It has a pi b inside I believe. The main use is simply so I have a wifi connection to the print er in another room

The problem  is my windows 11 Desktop (1920 x 1080) also shows the touch ui interface when I connect  directly to Octoprint via the ip address. This  was mention in issue #280 but never resolved.

I do some times  have the  system fonts s and also the browser fonts due to sight  problems, So it is possible this is confusing  screen resolution detection  but I have also tried   with these window features off.

![TouchUi_desktop](https://user-images.githubusercontent.com/35637647/151196982-925468a9-16bc-43ba-8aeb-92d3f77238eb.jpg)
.

**Comment by bolsoncerrado** [comment]
I'm having the same issue. I have to manually deactivate TouchUI interface when using a computer browser.

I'm on MacOS though.
