### ISSUE TITLE
Can I have a piTablet run the touchui exclusively without octoprint installed?

### ISSUE THREAD

**Issue by ExclusiveOne** [BillyBlaze/OctoPrint-TouchUI#53]
I had a PiTablet running my 3d printer, but i needed to move the printer, so i have a ne pi3 running octoprintwith a pi cam. I have a new pitablet built that I would like to keep at my desk to only run the touchui.
I just have rasbian installed, and I can pull up ocoprint wia browser, but it is just to slow compared
 to having it on octopi

**Comment by BillyBlaze** [comment]
Hello,

Yes, thats possible, install the bootloader on the device you want TouchUI on, then after doing all the steps, edit this file:

https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart/blob/master/load-screen/script.js#L8

Which can be located under `/home/pi/TouchUI-autostart/load-screen/`

Then at line 8, change `localhost` to the IP of your OctoPrint, you might need to login into your router and assign a static IP address to your OctoPrint-Pi, this so that this IP will not change after X amount of hours.

**Comment by ExclusiveOne** [comment]
Do I need to have octoprint installed on the tablet also?

**Comment by ExclusiveOne** [comment]
> sudo update-rc.d touchui defaults
> insserv: Service octoprint has to be enabled to start service touchui
> insserv: exiting now!
> update-rc.d: error: insserv rejected the script header

Getting this on the last step of the install

**Comment by BillyBlaze** [comment]
No, you don't need octoprint to be installed on the tablet, only the TouchUI bootloader.

Oww yeah I forgot that was a dependency in the daemon script.

Edit `/home/pi/TouchUI-autostart/touchui.init`

and remove `$all octoprint` on line 5

Then you can redo this steps.

**Comment by ExclusiveOne** [comment]
for some reason it is still booting to desktop

**Comment by ExclusiveOne** [comment]
I acctually dont think I am getting the load-screen file written right. when I try to pull it up it says it is a directory.

**Comment by BillyBlaze** [comment]
Booting to desktop? I assume you're running Wheezy or Jessie (Full)?

Did you follow the '[make sure you boot to the command line](https://www.raspberrypi.org/documentation/configuration/raspi-config.md)' step?

**Comment by ExclusiveOne** [comment]
I installed noobs. Guess I should start over with Jessie full?

**Comment by BillyBlaze** [comment]
No, not necessary, you can still disable it manually but how is uncharted territory for me.

Btw. I thought NOOBS included Raspbian as default, is the command not found?

**Comment by ExclusiveOne** [comment]
Well I took a step back, re-wrote my card, and got the touchui to auto boot. now when I try to open `/home/pi/TouchUI-autostart/load-screen/` it says it is a directory, and that is where my knowledge runs out! So all I need to do now is learn how to edit that file, and get my ip in there.

**Comment by BillyBlaze** [comment]
yes `load-screen/` is the directory, and you're looking to edit `script.js` on line 8 :wink:

**Comment by ExclusiveOne** [comment]
How fantastic! Ok I got the ip in there, but it still doesn't want to connect on reboot. I might be in left feild, but do I need to creat a user in octoprint to allow the tablet to connect?

**Comment by BillyBlaze** [comment]
Did you install the main TouchUI plugin on the OctoPrint-Pi?

**Comment by ExclusiveOne** [comment]
Yes i have 0.3.4 installed

**Comment by BillyBlaze** [comment]
Hmm, okay could explain a little bit better where you're stuck on? I might misunderstood something.

**Comment by ExclusiveOne** [comment]
This is how I left line 8 `var prefix = "http://192.168.1.3:"+port+"/";` The tablet does it's count to 10 trying to connect, the says connection failed [Screen Image](http://i.imgur.com/ysQBX4k.jpg)

**Comment by BillyBlaze** [comment]
Okay thanks, if you try a computer and manually go to `http://192.168.1.3:5000/` does OctoPrint load? Perhaps you're using OctoPi and is it blocked?

**Comment by ExclusiveOne** [comment]
That has to be it. it is blocked only sometimes i have to give permission to open it though. but it only opens it i use `http://192.168.1.3`

**Comment by BillyBlaze** [comment]
okay, so if you change

`var prefix = "http://localhost:"+port+"/";`

into

`var prefix = "http://192.168.1.3/";`

then it works?

**Comment by ExclusiveOne** [comment]
My computer connects that way in chrome. The tablet does not

**Comment by BillyBlaze** [comment]
and does `http://192.168.1.3/plugin/touchui/ping` work on your computer??

**Comment by ExclusiveOne** [comment]
just a screen that says 

> OK  

on it

**Comment by ExclusiveOne** [comment]
The octopi is on wifi, but that shouldnt affect it should it? I have to tablet connected directly to the router

**Comment by BillyBlaze** [comment]
hmm no that shouldn't affect it, if both devices are connected to the same router.

can you edit `~/TouchUI-autostart/chromium.xinit` and uncomment the 5th line? Then retry everything and after that share the log `~/.config/chromium/chrome_debug.log`??

**Comment by ExclusiveOne** [comment]
To be honest, Im not sure how to share the log. I have it pulled up in putty, but from there i'm not sure unfortunately

**Comment by BillyBlaze** [comment]
You can use Pastebin or just save it as .txt file and drag-and-drop it in github

**Comment by ExclusiveOne** [comment]
is there a simple way to copy the file? Sorry, I still have my training wheels on.

**Comment by BillyBlaze** [comment]
yes http://pastebin.com/

**Comment by ExclusiveOne** [comment]
I mean copy the file content onto clipboard. i cant simply `ctrl+C` because it is multiple pages long

**Comment by BillyBlaze** [comment]
Right click on the title bar (Saying Command Prompt) and click Edit > Mark

**Comment by ExclusiveOne** [comment]
phew that was a learning experience. [Log](https://www.dropbox.com/s/tum8tmey0tsh932/YcRd8qnS.txt?dl=0)

**Comment by BillyBlaze** [comment]
Everything looks fine, maybe you can connect with `http://your-printer-hostname.local/`

I just tested it, and everything worked as expected.

You can also be sure that your tablet can connect to your Pi by pinging it with `ping 192.168...` or `ping yourpintername.local`

**Comment by ExclusiveOne** [comment]
I can ping it, but It wont connect `octopi.local` either. I tried that last night unfortunately.

**Comment by BillyBlaze** [comment]
hmm okay, lets check out the external developers tool. you already have it enabled.

Just run `ssh -L 0.0.0.0:9223:localhost:9222 localhost -N` and open on your computer in the browser the following url: http://192.168.1.5:9223

Please share to me the contents of the console.

**Comment by ExclusiveOne** [comment]
`pi@raspberrypi:~ $ ssh -L 0.0.0.0:9223:localhost:9222 localhost -N
pi@localhost's password:
` 

That URL wont open either.

**Comment by BillyBlaze** [comment]
Try with `sudo`

**Comment by ExclusiveOne** [comment]
`pi@raspberrypi:~ $ sudo ssh -L 0.0.0.0:9223:localhost:9222 localhost -N
The authenticity of host 'localhost (::1)' can't be established.
ECDSA key fingerprint is 1f:9c:0e:a9:07:78:96:5c:71:2e:b6:94:6a:44:91:e8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
root@localhost's password:
Permission denied, please try again.
` 

 I did another fresh install to make sure I wasnt screwing anything up, and I am back to the same spot in my troubles. feeling doomed

**Comment by ExclusiveOne** [comment]
My phone, and other two computers connect to that url no problem, so feeling a bit puzzled now

**Comment by BillyBlaze** [comment]
Ok, try this; copy the files inside the directory `load-screen` to your computer, then open `startup.html`in your Chrome browser. Does it still not connect? Can you then open the developer tools and copy the console from there?

**Comment by ExclusiveOne** [comment]
I'm hoping this is what you are referring to
 `Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #10, waiting 100s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
http://192.168.1.3/webcam/?action=stream&1467533043240 Failed to load resource: net::ERR_ADDRESS_UNREACHABLE`

**Comment by BillyBlaze** [comment]
Almost, can you do it again but this time after you opened the developers tools, can you refresh the page? This so you get all errors / warnings

**Comment by ExclusiveOne** [comment]
Starting dependency resolution...
packed_app.js?1ae0b1f2:11624 ... dependency resolution done
packed_app.js?1ae0b1f2:11976 Initial application setup done, connecting to server...
packed_app.js?1ae0b1f2:10675 Connected to the server
packed_app.js?1ae0b1f2:11963 Finalizing application startup
packed_app.js?1ae0b1f2:11868 Going to bind 24 view models...
packed_app.js?1ae0b1f2:11936 ... binding done
packed_app.js?1ae0b1f2:11955 Application startup complete
packed_app.js?1ae0b1f2:10588 Reconnect trial #0, waiting 0s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #1, waiting 1s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #2, waiting 1s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #3, waiting 2s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #4, waiting 3s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #5, waiting 5s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #6, waiting 8s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #7, waiting 13s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #8, waiting 20s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #9, waiting 40s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10588 Reconnect trial #10, waiting 100s
http://192.168.1.3/sockjs/info Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
http://192.168.1.3/webcam/?action=stream&1467533043240 Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
packed_app.js?1ae0b1f2:10675 Connected to the server

**Comment by BillyBlaze** [comment]
And what error does TouchUI give you now?

Is this consistent with the tablet-pi?

**Comment by ExclusiveOne** [comment]
I don't get an error. it just goes through the loop of trying to connect. then the logo turns red, and says connection failed

**Comment by BillyBlaze** [comment]
yeah the connection failed is the error message I was referring to. So you get error on both devices now?

also the log you just gave me indicates it did got connected, and tries to load OctoPrint. But I guess you have alot of errors connecting to non-TouchUI related stuff:

```
Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
```

**Comment by ExclusiveOne** [comment]
Question. If I can ping the octopi from the tablet, but but cant connect to it. Then it is something router side that is causing my hang up? Im starting to feel like it isnt getting an internet connection

**Comment by BillyBlaze** [comment]
No, if you can ping it, you reach that end-point successfully. Your router could forward ports to a different port but I highly doubt that.

I think it has todo with OctoPi's permissions and closed ports. I tried OctoPI myself but I quickly went back to installing OctoPrint manually.

**Comment by ExclusiveOne** [comment]
I will give that a try when this print is finished. I really appreciate all the help, this has for sure been a learning experience

**Comment by BillyBlaze** [comment]
Any luck on this?

**Comment by ExclusiveOne** [comment]
Unfortunately no so far, but I set it aside for a while. I'm still hanging up at the same point of trying to connect. i can ping it just fine, but the connection failed screen is still all i get

**Comment by BillyBlaze** [comment]
Bummer... What is the output of this command: `wget http://192.168.1.3/plugin/touchui/ping`?

**Comment by BillyBlaze** [comment]
Any information on that command?

**Comment by BillyBlaze** [comment]
Closed due to inactivity; feel free to add a comment. I will still be able to read that.
