### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by vexofp** [BillyBlaze/OctoPrint-TouchUI#535]
@BillyBlaze Are you still maintaining this plugin, or would you be interested in passing the torch to someone else? (Perhaps via a [OctoPrint plugin abandonment issue](https://github.com/OctoPrint/plugins.octoprint.org/issues).)

I ask only because it has been over a year since the last commit, every issue in the last six months has been auto-locked without a reply, and compatibility with latest release of Octoprint has been broken for several months.

Either way, thanks for all your hard work over the years making an awesome plugin! 🙇

**Comment by pzwe2020** [comment]
i would like to take over

**Comment by ender-bit** [comment]
I would like to own this plugin
