### ISSUE TITLE
Touch UI - No Temperature Graph

### ISSUE THREAD

**Issue by leitenky** [BillyBlaze/OctoPrint-TouchUI#537]
When I go to the temperature page in TouchUI the Temperature graph does not display

Touch UI 0.3.18
Octoprint 1.8.6

**Comment by jamesblonde92** [comment]
I am also seeing this issue.

Mobile device: Samsung S21 Ultra
Touch UI 0.3.18
Octoprint 1.8.6
![Screenshot_20221101-105027_Chrome](https://user-images.githubusercontent.com/11891268/199278812-20c4ca85-d5ee-43eb-8068-1547b273b211.jpg)

**Comment by roblandry** [comment]
Same issue. It displays behind at the bottom like the above screenshot

**Comment by shule88** [comment]
I have same issue on mobile, empty space before graph, both on mobile and on RPi3. Anybody have some ideas?

**Comment by bondarchook** [comment]
Still not fixed on latest chrome (android phone - pixel 3a) 
OctoPrint 1.8.6
TouchUI version 0.3.18

Looks same as on screenshot provided by @jamesblonde92

**Comment by roblandry** [comment]
@bondarchook 
https://github.com/OctoPrint/plugins.octoprint.org/issues/1126#issue-1472105657
