### ISSUE TITLE
Webcam STILL not working?

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#55]
So I do have the webcam up and working:

1) flawlesly and streaming thru OctoPrint via a regular PC browser on the CONTROL tab
2) flawlesly by issuing the http://pi-ip-adrress:8080/?action=snapshot as you can see [here](http://i.imgur.com/rxF1jSq.png)
HOWEVER 3) added to snapstream plugin [as adviced](http://i.imgur.com/TAkPHKe.png), delivers [broken image](http://i.imgur.com/FA74IaF.jpg) on the WEBCAM button

any clues?

Thanks!

**Comment by BillyBlaze** [comment]
Hmm yeah that troubleshooting is not flawless I see.. (It assumes the user has HAproxy configured)

I think it's looking at port 5000 and not 8080. If you save the whole url `http://pi-ip-adrress:8080/?action=snapshot` under Snapstream URL, it should work.

**Comment by bolsoncerrado** [comment]
Yep with the whole URL works...

SO may be your guide needs a few reTouchs :D

2016-07-01 19:57 GMT+02:00 Paul de Vries notifications@github.com:
