### ISSUE TITLE
[REQUEST?] Force refresh button?

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#57]
Not sure if this is worth? I find out sometimes the GUI wont refresh and the UI becomes unusable making the printer uncontrollable thru the display touch panel on the raspi, hence I need to use my phone (or a computer), log into the web URL and manually refresh, reboot or restart the server so the GUI refreshes as well. May be a force refresh button on the  TouchUI would help out? Seems it happens when connection with the printer is lost (for example i tend to remote cut power using WeMo switches to the printer) and Octoprint looses connection to the printer, but no matter what I do later via TouchUI / Octoprint via the display touch (reboot, refresh, etc.) Octoprint/Pi wont reboot/restart at all.

**Comment by BillyBlaze** [comment]
Hi,

You can make a System Command in OctoPrint that restarts TouchUI from there.
Read more about this in the [OctoPrint manual](https://github.com/foosel/OctoPrint/wiki/Cookbook:-System-Commands#reboot-the-server-linux)
The command for restarting TouchUI is: `sudo service touchui restart`

**Comment by bolsoncerrado** [comment]
I will try that but the same as raspi won't restart nor reboot nor
shutdown, not sure if this will make anything different. was thinking of a
refresh like a browser  page refresh.

but will report back.

**Comment by BillyBlaze** [comment]
Thanks, any word? (else I will close this issue due to inactivity)

**Comment by bolsoncerrado** [comment]
still have to get into creating the button...

**Comment by BillyBlaze** [comment]
Closed due to inactivity. Please comment to re-open this issue.
