### ISSUE TITLE
Display Language probloem

### ISSUE THREAD

**Issue by today4king** [BillyBlaze/OctoPrint-TouchUI#58]
after apply chinese language to octopi print ,characters become boxes .
I think its cause of chrome not support, trying to figure it out.
Pls could you help me to fix this problem also?

**Comment by BillyBlaze** [comment]
Hello today4king,

I guess you had to change the font to make Chinese work? And all icons are now turning into boxes? How did you change the font? With a Chrome extension?

**Comment by BillyBlaze** [comment]
Any information? If not, after 7 days this issue will be closed due to inactivity.

**Comment by BillyBlaze** [comment]
Closed due to inactivity; feel free to add a comment. I will still be able to read that.
