### ISSUE TITLE
Feature Request: Search box for files

### ISSUE THREAD

**Issue by heathicus** [BillyBlaze/OctoPrint-TouchUI#60]
On the files section, can a search box be added to find files based on filename?  This feature is in the full desktop interface of Octoprint and it would help a lot if it were in the TouchUI interface as well.

**Comment by BillyBlaze** [comment]
Thanks, I agree, I will add this in the 1.0.0 release.

**Comment by BillyBlaze** [comment]
Thanks again for reporting, I have merged your ticket into #39 and I will close this issue for sake of cleaning up the issue tracker!
