### ISSUE TITLE
Touch Events not working on Waveshare 7" v2.1 LCD

### ISSUE THREAD

**Issue by CapnBry** [BillyBlaze/OctoPrint-TouchUI#62]
The new Waveshare 7" LCD version 2.1 now uses a HID device for the touchscreen driver, which means it works out of the box with Raspbian. However, using the TouchUI-autostart script, "clicks" work, but not drags so you can't scroll the TouchUI or access the gcode item slide list. Oddly enough, booting to the full standard Raspbian desktop and launching chromium-browser (no command line options), the touch and drag events work as expected.

To work around this, I force touch events in the same way FT5406 touch events are forced and everything works great!

```
diff --git a/chromium.xinit b/chromium.xinit
index 68e8d24..9d5cfe3 100644
--- a/chromium.xinit
+++ b/chromium.xinit
@@ -13,7 +13,7 @@ sed -i 's/"exit_type": "Crashed"/"exit_type": "None"/' ~/.config/chromium/Defaul

 # Force Chrome to render with touch events
 # Bugfix #46
-TOUCHUI_DEVICE=$(egrep -o "FT5406" /proc/bus/input/devices)
+TOUCHUI_DEVICE=$(egrep -o "ZH851|FT5406" /proc/bus/input/devices)
 if [ -z "$TOUCHUI_DEVICE" ]
 then
        echo "TouchUI: touch events automaticlly detected"
```

**Comment by BillyBlaze** [comment]
Thanks for reporting :+1: 

I immediately committed this to the master branch.

**Comment by BillyBlaze** [comment]
@CapnBry, I got to find a more solid solution for detecting touch events, could you perhaps share your `cat /proc/bus/input/devices`

I am hoping that `H: Handlers=mouse0 event0` will be different on your machine.

**Comment by CapnBry** [comment]
You bet:
```
I: Bus=0003 Vendor=0eef Product=0005 Version=0110
N: Name="BYZHYYZHY By ZH851"
P: Phys=usb-3f980000.usb-1.4/input0
S: Sysfs=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/0003:0EEF:0005.0001/input/input0
U: Uniq=Â§ÃP39112398
H: Handlers=mouse0 event0
B: PROP=2
B: EV=b
B: KEY=400 0 0 0 0 0 0 0 0 0 0
B: ABS=2608000 3
```

**Comment by synman** [comment]
Here's mine:

pi@octopi:~/TouchUI-autostart $ cat /proc/bus/input/devices 
I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="ADS7846 Touchscreen"
P: Phys=spi0.1/input0
S: Sysfs=/devices/platform/soc/20204000.spi/spi_master/spi0/spi0.1/input/input0
U: Uniq=
H: Handlers=mouse0 event0 
B: PROP=0
B: EV=b
B: KEY=400 0 0 0 0 0 0 0 0 0 0
B: ABS=1000003

**Comment by BillyBlaze** [comment]
Thank you both very much!1! Sadly this wont help us...

However, after finding a linux device with touch events I was able to find out a way to detect touch events. ```xinput --long``` will report the classes X11 loads and with touch it will be something like XITouchClass.

I have created a maintenance branch and I was wondering if you guys could try out if this also works for you?

If so, just follow these steps:

1. ```sudo service touchui stop```
1. ```cd ~/TouchUI-autostart/```
1. ```git checkout maintenance origin/maintenance```
1. ```git pull```
1. ```sudo apt-get install xinput```
1. ```sudo xinit ~/TouchUI-autostart/chromium.xinit```

**Comment by synman** [comment]
`pi@octopi:~ $ sudo service touchui stop

pi@octopi:~ $ cd ~/TouchUI-autostart/

pi@octopi:~/TouchUI-autostart $ git checkout maintenance
Branch maintenance set up to track remote branch maintenance from origin.
Switched to a new branch 'maintenance'
pi@octopi:~/TouchUI-autostart $ git pull
Already up-to-date.`

Is this expected?  I am in the process of moving all of this to my P3 from my P1B and had done a checkout of TouchUI moments beforehand  Do we normally pull from the maintenance branch?

**Comment by BillyBlaze** [comment]
No, argh, I forgot to fetch first. I think its a local branch now..

Run:

1. ```git branch --set-upstream maintenance origin/maintenance```
1. ```git pull```

That should grab the new files.

**Comment by synman** [comment]
still up to date... but I see changes in chromium.xinit ... specific to using xinput ;)

weird

**Comment by synman** [comment]
and i can report scrolling works fine

```
pi@octopi:~/TouchUI-autostart $ sudo xinit ~/TouchUI-autostart/chromium.xinit


X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.26-v7+ armv7l Raspbian
Current Operating System: Linux octopi 4.4.46-v7+ #959 SMP Fri Feb 3 17:24:25 GMT 2017 armv7l
Kernel command line: 8250.nr_uarts=0 dma.dmachans=0x7f35 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2709.boardrev=0xa22082 bcm2709.serial=0xd8ef6da3 smsc95xx.macaddr=B8:27:EB:EF:6D:A3 bcm2708_fb.fbswap=1 bcm2709.uart_clock=48000000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
Build Date: 11 November 2016  11:59:59AM
xorg-server 2:1.18.4-2+rpi1 (https://www.debian.org/support) 
Current version of pixman: 0.33.3
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat Feb  4 11:13:25 2017
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
TouchUI: touch events enabled
wm_set_cursor_visibility: visible using XCreateFontCursor
/usr/bin/chromium-browser: line 138: lsb_release: command not found
/usr/bin/chromium-browser: line 139: lsb_release: command not found
[1871:1871:0204/111327:ERROR:gl_surface_glx.cc(381)] glxQueryVersion failed
[1871:1871:0204/111327:ERROR:gl_surface_x11.cc(62)] GLSurfaceGLX::InitializeOneOff failed.
[1871:1871:0204/111327:ERROR:gpu_child_thread.cc(397)] Exiting GPU process due to errors during initialization

(chromium-browser:1823): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
/usr/bin/dbus-launch terminated abnormally without any error message
[1823:1853:0204/111328:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
```

**Comment by BillyBlaze** [comment]
ahh, I haven't seen your edited comment.

Yeah depending on your git setup it will pull the entire remote. So you might already have the new changes.

What is the output of this command ```cat ~/TouchUI-autostart/chromium.xinit | grep XITouchClass```??

**Comment by synman** [comment]
sorry... we're typing over one another... see above

**Comment by synman** [comment]
re:  cat of chromium.xinit

```
pi@octopi:~/TouchUI-autostart $ cat ~/TouchUI-autostart/chromium.xinit | grep XITouchClass
TOUCHUI_DEVICE=$(xinput --list --long | grep XITouchClass)
```

I'll stop editing posts LOL

**Comment by BillyBlaze** [comment]
Ok that is awesome 👍 thank you very much for verifying.

If @CapnBry also could verify if this fix is working, then I will release this bugfix.

**Comment by synman** [comment]
I have an unrelated question regarding SnapStream.  Do you mind if I open a issue for it?

**Comment by CapnBry** [comment]
Works like a champ (update resolves the issue). All I needed to do was this
```
git pull
git checkout maintenance
```

If it matters at all, this is my xinput
```
â   â³ BYZHYYZHY By ZH851                        id=6    [slave  pointer  (2)]
        Reporting 4 classes:
                Class originated from: 6. Type: XIButtonClass
                Buttons supported: 5
                Button labels: "Button Unknown" "Button Unknown" "Button Unknown" "Button Wheel Up" "Button Wheel Down"
                Button state:
                Class originated from: 6. Type: XIValuatorClass
                Detail for Valuator 0:
                  Label: Abs MT Position X
                  Range: 0.000000 - 1024.000000
                  Resolution: 0 units/m
                  Mode: absolute
                  Current value: 208.000000
                Class originated from: 6. Type: XIValuatorClass
                Detail for Valuator 1:
                  Label: Abs MT Position Y
                  Range: 0.000000 - 600.000000
                  Resolution: 0 units/m
                  Mode: absolute
                  Current value: 328.000000
                Class originated from: 6. Type: XITouchClass
                Touch mode: direct
                Max number of touches: 10
```
