### ISSUE TITLE
Virtual Keyboard

### ISSUE THREAD

**Issue by pbrgle1** [BillyBlaze/OctoPrint-TouchUI#63]
The virtual keyboard does not appear even though i have it enablen in touch ui settings (on the official 7" Touchscreen). Am i missing something?

**Comment by BillyBlaze** [comment]
Thanks for reporting, can you provide me the version of TouchUI, OctoPrint and Browser you're using?

**Comment by pbrgle1** [comment]
Both are the latest official versions as of today. I believe im using chromium on a raspberry pi 3. I followed the steps on how to auto-boot to the browser. Also scrolling doesn't seem to work and if i click some external links such as about or bug report, there is no way to get back since there is no navigation bar.

**Comment by BillyBlaze** [comment]
Fixed through IRC:
- Fresh install and the problems where away.
