### ISSUE TITLE
how to change network settings

### ISSUE THREAD

**Issue by Mermalady** [BillyBlaze/OctoPrint-TouchUI#68]
I need to change my network settings- the network that was available is -not- anymore, so I can't SSH into the pi to do it. How do I edit the network file without being able to SSH into it?

**Comment by BillyBlaze** [comment]
Please take a look at the documentation of OctoPi or ask help at OctoPi. TouchUI does not provide this functionality or support questions on OctoPi - [it is a project of itself](https://github.com/guysoft/OctoPi) maintained by [Guy Sheffer](https://github.com/guysoft). You are welcome to discuss all things OctoPi related on the Mailinglist or in the G+ community of OctoPrint.

Long story short: I don't know.
