### ISSUE TITLE
Flowrate and Feedrate Not Sending Commands 

### ISSUE THREAD

**Issue by felixleong** [BillyBlaze/OctoPrint-TouchUI#72]
**Versions:** TouchUI 0.3.4 and Octoprint 1.2.7

**Browser Tested:** Google Chrome 54, Firefox 49 and Microsoft Edge mobile

**Problem:** The flow rate and feed rate text boxes is not sending any commands back to the printer upon confirmation. No error pop-up is shown.

**Reason:** Have bring it up using Google Chrome and it appears that it is due to the `factor` parameter is being sent as a string instead of an int.

This causes Octoprint to respond with a HTTP 400.

**Comment by BillyBlaze** [comment]
Thanks for reporting, I'll look into this issue very soon and if needed a fix in the upcoming 0.3.5 release.

**Comment by BillyBlaze** [comment]
I just pushed a fix into the maintenance branch and will release this in 0.3.5 very soon.

**Comment by jstefanop** [comment]
Hi, any update on 0.3.5 release? I have this issue as well and can only control feedrate through computer browser.  @BillyBlaze

**Comment by BillyBlaze** [comment]
Lol, euhhh, yeah, 24 days ago is not 'very soon' indeed 😄 

I'll try to fix one more open issue and release 0.3.5 directly afterwards.

**Comment by BillyBlaze** [comment]
Thanks for your patience. I have released 0.3.5 👍 

In advance, happy new year everybody!

**Comment by jstefanop** [comment]
@BillyBlaze thanks! I dont see the update being pushed to octoprint software update...is there a way to update manually?

**Comment by jstefanop** [comment]
nevermind...needed to do a force update on the octoprint software update UI

**Comment by BillyBlaze** [comment]
Awesome I was just about to type that 👍
