### ISSUE TITLE
90° rotated webcam image does not get positioned correctly

### ISSUE THREAD

**Issue by joris57** [BillyBlaze/OctoPrint-TouchUI#78]
After selecting the 'Rotate webcam 90 degrees counter clockwise' option, the webcam image does not show completely and partially overlaps the title bar, when the camera tab is selected. Strange is that when the browser is sent to the background (with the camera tab open) and then recalled, the display is ok.

**Comment by BillyBlaze** [comment]
Thanks for reporting, I will look into this before the upcoming release.

**Comment by BillyBlaze** [comment]
btw. do you have some more information about where this happened? (i.e. touchscreen, mobile, computer)
and which browser?

**Comment by BillyBlaze** [comment]
if your quick I could fix this in the upcoming 0.3.5 👍

**Comment by joris57** [comment]
This occurs on 
- any device (tablet, phone or PC)
- touch and non-touch
- Chrome, Microsoft Edge, default Samsung browser (whatever that is)
- cheap endoscope cam and Logitech C270

When switching between BROWSER tabs the image gets correctly positioned, when switching between TOUCHUI tabs (cam and any other tab), the image becomes messed up again.

**Comment by BillyBlaze** [comment]
Thanks for the information, I was able to reproduce the problem and I will fix this in 0.3.5

**Comment by BillyBlaze** [comment]
It has fixed and released in 0.3.5
