### ISSUE TITLE
Full screen mode is not looking as intended on my Nexus 6

### ISSUE THREAD

**Issue by fraternl** [BillyBlaze/OctoPrint-TouchUI#8]
I set my Nexus 6 in full-screen and I believe it isn't displaying as you intended...
Some stuff should be on 1 screen without the need for scrolling.
I made several screenshots to make this clear.

Great stuff.... 
I hope you can fix this.

![2015-10-29 22 24 16](https://cloud.githubusercontent.com/assets/8692856/10833850/4d5ff9fe-7e95-11e5-9d64-322c6b4d550f.png)
![2015-10-29 22 26 06](https://cloud.githubusercontent.com/assets/8692856/10833867/5b9fc10c-7e95-11e5-9f84-37e9bd29e9de.png)
![2015-10-29 22 24 23](https://cloud.githubusercontent.com/assets/8692856/10833866/5b9f8660-7e95-11e5-8abc-08bc8b3d3bae.png)
![2015-10-29 22 24 58](https://cloud.githubusercontent.com/assets/8692856/10833868/5b9fe038-7e95-11e5-82dd-bc671b006479.png)
![2015-10-29 22 25 15](https://cloud.githubusercontent.com/assets/8692856/10833869/5ba0018a-7e95-11e5-9101-eccd0c9f9d7d.png)
![2015-10-29 22 25 21](https://cloud.githubusercontent.com/assets/8692856/10833871/5ba61be2-7e95-11e5-8c57-782f23c5a767.png)
![2015-10-29 22 25 43](https://cloud.githubusercontent.com/assets/8692856/10833870/5ba26132-7e95-11e5-9f15-34af47beb3a5.png)
![2015-10-29 22 25 52](https://cloud.githubusercontent.com/assets/8692856/10833872/5bb3bf90-7e95-11e5-8f98-84ac60873b2d.png)

**Comment by BillyBlaze** [comment]
Thanks for reporting, I'll look into this a bit more.

**Comment by BillyBlaze** [comment]
This problem is resolved in v0.2.1
