### ISSUE TITLE
Webcam stopped showing up

### ISSUE THREAD

**Issue by mrp192** [BillyBlaze/OctoPrint-TouchUI#82]
So I accidentally uninstalled TouchUI and now I cant see my webcam. Any ideas on where to start looking to fix it?

**Comment by BillyBlaze** [comment]
And you have restarted OctoPrint? And refreshed your browser?

**Comment by mrp192** [comment]
Yes I have this is what it shows me. 
![img_0176](https://cloud.githubusercontent.com/assets/18508896/21583446/d24fc7aa-d035-11e6-8ac3-e6dca1663f9e.PNG)

**Comment by BillyBlaze** [comment]
Wow that is really weird. So, to get this right, you uninstalled TouchUI, installed it again, restarted everything, and then the controls appears within the webcam tab, without a webcam image?

**Comment by mrp192** [comment]
I can be on whatever tab. Then if I click the webcam tab it just show the last tab I was on.

**Comment by BillyBlaze** [comment]
Hmm, ok that indicates that something is going wrong with creating the webcam container.

Do you have other plugins installed beside the bundled ones?

**Comment by mrp192** [comment]
yes

**Comment by bizziebis** [comment]
I have this same issue, for me it never worked so I didn't pay much attention to it. But now I see this issue I suppose that it should actually work.

**Comment by BillyBlaze** [comment]
Thanks for reporting, I really need some more information about installed plugins, os-, and browser versions.

**Comment by bizziebis** [comment]
Just did some testing with disabling plugins. Turns out that in my case it's caused by [Slicer](https://github.com/kennethjiang/OctoPrint-Slicer) plugin. I use it always, that's why my webcam never worked with Touch UI,

**Comment by BillyBlaze** [comment]
Ahh the Slicer plugin strikes again, its a great plugin, sadly it breaks on some certain browsers.

**Comment by mrp192** [comment]
HAha so I just disabled slicer and that was it. I never use it. Pretty sure it had a update recently.

**Comment by BillyBlaze** [comment]
ok since the Slicer plugin isn't 'officially' supported by TouchUI I will close this issue. I'll try to add support in the 1.0.0 version. (Also there is a new feature stop on the 0.x.x branch)
