### ISSUE TITLE
Upgrading / Installing TouchUI

### ISSUE THREAD

**Issue by TiEr92** [BillyBlaze/OctoPrint-TouchUI#83]
Hi, 
i tried to update touch ui today. but i get the following error: 

Installing the plugin from URL "unknown" failed: Could not parse output from pip

**Comment by BillyBlaze** [comment]
Hello,

Sorry this is not the fault of TouchUI there seems to be some issue with your `pip` configuration. I have absolutely no clue about `pip` and it's better if you would ask this at OctoPrint so that anyone familiar with PIP can help you sort out this problem.

Good luck!
