### ISSUE TITLE
[Request] Requesting removal of the "would you like to go fullscreen" popup

### ISSUE THREAD

**Issue by ntoff** [BillyBlaze/OctoPrint-TouchUI#85]
Requesting the "would you like to go fullscreen" popup be removed as per conversation on reddit.

Reason: Sometimes I use touchui's interface in a browser that doesn't have the ability to be clicked on (it just displays URL sources) and the popup is permanently there with no way to click "no" (or to click "yes" either) and since there's an option in the settings to go fullscreen, I feel the popup is no longer needed.

**Comment by BillyBlaze** [comment]
Thanks for creating the ticket 👍 

As previously said, this legacy code can be removed due to "kiosk mode" on touchscreen devices. (Epiphany users have to find a workaround, e.g. install a script that execute F12, or install Chromium)

**Comment by gretel** [comment]
@BillyBlaze kioskize epiphany is a bit tricky - following http://raspberrypi.stackexchange.com/a/43336/8018 works fine for me.

**Comment by BillyBlaze** [comment]
@gretel awesome, thanks for the info!

@ntoff I will remove this in the upcoming 0.3.6 release!

**Comment by BillyBlaze** [comment]
This is fixed in the latest 0.3.6 release.
