### ISSUE TITLE
current version not usable with epiphany-browser

### ISSUE THREAD

**Issue by gretel** [BillyBlaze/OctoPrint-TouchUI#87]
is epiphany supposed to be supported? the control and camera tabs are not usable. i'd send screenshots if helpful - using updated **octopi**. chromium works fine - but slow on the rpi3.

**Comment by BillyBlaze** [comment]
Epiphany is still supported, but slowly turning into deprecation if they do need keep up with the latest webkit engine.

Anyhow, I did check TouchUI in Epiphany and both the controls and the camera tab are working for me. Could you disable other plugins to make sure they're not the culprit. If they're not, I need some more information to reproduce your issue.

**Comment by BillyBlaze** [comment]
Any information? If not, after 7 days this issue will be closed due to inactivity.
