### ISSUE TITLE
suggestion: show warning if "gcode visualizer" is enabled

### ISSUE THREAD

**Issue by gretel** [BillyBlaze/OctoPrint-TouchUI#88]
this really seems to drag down slow machines when enabled therefore i suggest showing a collapsable warning or similar.

**Comment by BillyBlaze** [comment]
Thanks for the suggestion. We need to disable this plugin in touchscreen mode.

**Comment by BillyBlaze** [comment]
So, Yeah, I was also here confused with the plugin "STL Viewer".

In touchscreen mode, the default gcode viewer will already be disabled.
See; https://github.com/BillyBlaze/OctoPrint-TouchUI/blob/master/source/js/components/touchscreen.js#L36

**Comment by BillyBlaze** [comment]
If it is not disabled in touchscreen mode then we might have found out your issue for #91 👍

**Comment by gretel** [comment]
guess both ('gcode visualizer' and 'stl viewer') will impact performance and in relation to the size of the data. the latter one does not have a limiting option at the present time.
i suggest thinking about how to let the backend handle the lesser requirements of alternative UIs - like not delivering heavy components at all.

**Comment by BillyBlaze** [comment]
Yeah, the latter is giving TouchUI a bit of an issue. I will definitely give a warning, or even better, disable STL viewer in touchscreen mode.

For now I have add'd this to checklist of #39

**Comment by jstefanop** [comment]
seems like the gcode visualizer is still loading with current version of octoprint (1.3.1). What is the easiest way to completely disable the visualizer on the local device (i still want it to load on other devices that load ocroprint, the pi just cant handle loading it locally on chromium).

**Comment by BillyBlaze** [comment]
Thanks, I can also confirm that the gcode visualizer currently loads in touchscreen mode.

I will fix this and make a new release.

**Comment by BillyBlaze** [comment]
This is fixed in the latest 0.3.6 release.
