### ISSUE TITLE
suggestion: option to disable camera tab

### ISSUE THREAD

**Issue by gretel** [BillyBlaze/OctoPrint-TouchUI#89]
in my case the touchscreen is mounted on the printer so i do not require the camera tab at all. i wonder if not including it at all would reduce performance cost a bit.

**Comment by BillyBlaze** [comment]
OctoPrint only loads a (M)JPEG file and we only move the webcam container (if it exists). Also OctoPrint doesn't load the image if the webcam tab is not active.

Therefor performance won't make any difference (only a few milliseconds during start-up). So I thank you for your suggestion but the effort is just to much for that tiny bit.
