### ISSUE TITLE
[REQUEST] Move "Logout" option away from System options

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#90]
For one reason or another, in my Pi setup using the official display and touchui, i tend to click more times on the user logout option than on system -> reboot/restart/whatever :( the'yre too close! 

and this is a headache since i then have to log in again, type in user and pass on the built in keyb and then be careful and able to reboot/restart the service....

Any chances to move the logout to the very most bottom?

**Comment by BillyBlaze** [comment]
Thanks for asking but the menu will be totally different on touchscreen devices in 1.0.0, so please cope with this for now untill I released that one 👍
