### ISSUE TITLE
PSU Control Compatibility

### ISSUE THREAD

**Issue by KriLL3** [BillyBlaze/OctoPrint-TouchUI#93]
I've recently started using PSU control: https://github.com/kantlivelong/OctoPrint-PSUControl which automatically turns the printer's power off when idle (and on when you use a command that needs power) and gives a new button next to settings and system in the desktop UI that lets you toggle the printer on/off, doesn't show up in touchUI. Making these 2 plugins compatible would be nice.

**Comment by BillyBlaze** [comment]
Thanks for reporting, since #97 is a duplication of this issue therefor I am closing this one and continue on in that thread.
