### ISSUE TITLE
Menu has no text (plugin: 0.3.5, octopi: 1.3.1 safari on iOS10.2.1)

### ISSUE THREAD

**Issue by KriLL3** [BillyBlaze/OctoPrint-TouchUI#94]
Menu looks like this for me:

http://i.imgur.com/TJMgBzZ.png

Oddly enough the text in the rest of the UI is fine, seems to only affect the menu,

**Comment by BillyBlaze** [comment]
Thanks for reporting, since #97 is a duplication of this issue therefor I am closing this one and continue on in that thread.
