### ISSUE TITLE
Camera does not work -- local or network when in TouchUI mode

### ISSUE THREAD

**Issue by synman** [BillyBlaze/OctoPrint-TouchUI#95]
Following the instructions as provided on the wiki, including checking the URLs for m-jpeg streamer, I am not getting anything from my pi camera.

Works fine in full UI mode.  Any pointers regarding what I may have misconfigured?

**Comment by synman** [comment]
<img width="654" alt="screen shot 2017-02-04 at 11 28 29 am" src="https://cloud.githubusercontent.com/assets/1299716/22619918/3a812bf0-eacd-11e6-8433-d7819c1e9855.png">

And when I activate TouchUI using full Chrome on my MBP, I get this:

<img width="1550" alt="screen shot 2017-02-04 at 11 30 05 am" src="https://cloud.githubusercontent.com/assets/1299716/22619921/5e699282-eacd-11e6-81da-33874babdc7f.png">

Chromium at least tries to do stuff but it appears on full chrome whatever js/css operation is being performed on #webcam is completely ignored.

If I have time I'll dig deeper into this myself today.  More than happy to help.

**Comment by synman** [comment]
just went through the closed issues list... I see this may be related to the Slicer plug-in.... I have it installed and will disable it now to diagnose.

**Comment by synman** [comment]
ok, so disabling slicer fixed the Camera view on full Chrome, i.e. my MBP, however it doesn't matter what I put in SnapStream's config (/webcam/?action=snapshot and /?action=snapshot) I cannot get a snapshot to render over chromium (LCD).

http://octopi.local/webcam/?action=snapshot works (as mapped through haproxy)
http://octopi.local:8080/?action=snapshot works (when bypassing haproxy and going directly to jpeg-streamer)

Toggling the "use snapstream" checkbox in the plugin's settings also has no effect.

**Comment by synman** [comment]
I guess you can close this... 

when using a fully qualified URL it works fine.  The only problem I see with this is that I'm currently relying on DHCP and on devices without bonjour (my android phone for example) I can't use the avahi hostname (octopi).

I plan on setting a reservation for the octopi at some point anyway so this is totally manageable for me.

**Comment by BillyBlaze** [comment]
Hi, I'm glad you have figured this one out. I never completely understood OctoPi's security since I always built my own. Please do feel free to clarify any Wiki instructions.
