### ISSUE TITLE
xinput_calibration doesn't work after killing TouchUI service

### ISSUE THREAD

**Issue by SnowsongWolf** [BillyBlaze/OctoPrint-TouchUI#96]
I'm using Raspberry Pi 2B with the 7 inch touchscreen (I think the official one, been a while, sues FT5406 memory based driver).

I'm not very knowledgeable in things Linux but while following the calibration tutorial I found that I kept getting the "Cannot connect to x server" error message after killing the TouchUI service.  What confused me was it also killed the xinput --list command which was previously working fine.

What I determined was that xinput_calibration ran normally without killing TouchUI and generated the config values I needed.

**Comment by BillyBlaze** [comment]
Thanks for reporting! Yes, you're spot on, xinput_calibration can no longer work if TouchUI is not running, these instructions became obsolete after Debian Jessie got released.

I did  -just now - add a calibration start-up script, so X11 knows exactly to what instance it needs to attach itself. I have updated the Wiki, so this should be easier from now on.

**Comment by synman** [comment]
I would think this is because the window manager gets torn down when touchui shuts down... there's no xwindows session... no window manager, hence "cannot connect to x server".

fire up the matchbox window manager and try again.  I'm sure it'll work just fine.
