### ISSUE TITLE
TouchUI and PSU Control do not play nicely together

### ISSUE THREAD

**Issue by synman** [BillyBlaze/OctoPrint-TouchUI#97]
I have also opened this as an issue in the PSU Control repo but there is currently a problem between TouchUI and PSU Control. When on a low density touchscreen (3.5 LCD attached to the Pi) with PSU Control and TouchUI active when you try to open the System/Settings/Logon spanner (see attached) the entire context menu is blanked out.

You can also simulate this fairly easily by just shrinking your browser's width (see attached).

<img width="406" alt="screen shot 2017-02-10 at 6 02 16 pm" src="https://cloud.githubusercontent.com/assets/1299716/22847528/70d2204a-efbb-11e6-9d1b-634e96abe77f.png">

**Comment by synman** [comment]
Here's this issue for this on PSU Control:

https://github.com/kantlivelong/OctoPrint-PSUControl/issues/8

**Comment by synman** [comment]
Here you can see what is going on....

<img width="904" alt="screen shot 2017-02-10 at 6 20 20 pm" src="https://cloud.githubusercontent.com/assets/1299716/22847809/a2b4db78-efbd-11e6-8cd3-956ebf1e0224.png">

**Comment by BillyBlaze** [comment]
Thanks for reporting.

It's fixed in the maintenance branch and will be released a.s.a.p.

**Comment by synman** [comment]
you rock!

**Comment by synman** [comment]
pulled maintenance down and the context menu is now displaying with proper dimensions.  Oddly, GCode Viewer has disappeared from my touchscreen display but is still visible on my phone.

Did it not make the cut?

**Comment by BillyBlaze** [comment]
Yes, everything is like it should be. The GCode Viewer is enabled when you're no in Touchscreen mode. If you would like to enable Touchscreen mode for your mobile too, then enable it in the TouchUI Settings modal.
